# Deep Learning Experiments: MNIST & FashionMNIST

This notebook trains ResNet-18 and ResNet-50 models on MNIST and FashionMNIST datasets.
It uses a 70-10-20 train-val-test split and performs a grid search over specified hyperparameters.

**Requirements:**
- GPU Runtime (Google Colab: Runtime > Change runtime type > GPU)
- PyTorch, Torchvision, Scikit-learn, Pandas, tqdm

In [1]:
import warnings
warnings.filterwarnings('ignore', category=UserWarning, module='torchvision')

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, ConcatDataset, random_split
from torchvision import datasets, transforms, models
import pandas as pd
import numpy as np
import time
from tqdm.notebook import tqdm
from IPython.display import display
import gc  # For garbage collection

# Set pandas display options for 6 decimal places
pd.set_option('display.float_format', '{:.6f}'.format)

# Check for GPU and optimize CUDA settings
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

if device.type == 'cuda':
    # GPU Optimization Settings
    torch.backends.cudnn.benchmark = True  # Auto-tune convolution algorithms
    torch.backends.cuda.matmul.allow_tf32 = True  # Allow TF32 for faster matmul
    torch.backends.cudnn.allow_tf32 = True  # Allow TF32 for cuDNN
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")
    print("CUDA optimizations enabled: cudnn.benchmark=True, TF32=True")
else:
    print("WARNING: It is highly recommended to run this notebook with a GPU!")

from sklearn.metrics import accuracy_score
from sklearn.svm import SVC

Using device: cuda
GPU: Tesla T4
GPU Memory: 15.83 GB
CUDA optimizations enabled: cudnn.benchmark=True, TF32=True

## 1. Data Preparation
We define a function to load the datasets and split them into 70% Train, 10% Validation, and 20% Test.

In [2]:
def get_dataloaders(dataset_name, batch_size, pin_memory=True, num_workers=0):
    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.5,), (0.5,)) 
    ])

    if dataset_name == 'MNIST':
        train_part = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
        test_part = datasets.MNIST(root='./data', train=False, download=True, transform=transform)
    elif dataset_name == 'FashionMNIST':
        train_part = datasets.FashionMNIST(root='./data', train=True, download=True, transform=transform)
        test_part = datasets.FashionMNIST(root='./data', train=False, download=True, transform=transform)
    else:
        raise ValueError("Unknown dataset")

    full_dataset = ConcatDataset([train_part, test_part])
    total_len = len(full_dataset)
    train_len = int(0.7 * total_len)
    val_len = int(0.1 * total_len)
    test_len = total_len - train_len - val_len
    
    generator = torch.Generator().manual_seed(42)
    train_set, val_set, test_set = random_split(full_dataset, [train_len, val_len, test_len], generator=generator)
    
    # DataLoaders with configurable pin_memory
    train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True, pin_memory=pin_memory, num_workers=num_workers)
    val_loader = DataLoader(val_set, batch_size=batch_size, shuffle=False, pin_memory=pin_memory, num_workers=num_workers)
    test_loader = DataLoader(test_set, batch_size=batch_size, shuffle=False, pin_memory=pin_memory, num_workers=num_workers)
    
    return train_loader, val_loader, test_loader

## 2. Model Definition
We use ResNet-18 and ResNet-50. Since these models expect 3-channel input (RGB) and our datasets are grayscale (1-channel), we modify the first convolutional layer to accept 1 input channel. Using `weights=None` (no pretrained weights) to avoid the deprecated `pretrained` argument.

In [3]:
def get_model(model_name, num_classes=10, target_device=None):
    """Create ResNet model with memory-optimized settings"""
    if target_device is None:
        target_device = device  # Use global device if not specified
    
    if model_name == 'ResNet18':
        model = models.resnet18(weights=None)
    elif model_name == 'ResNet50':
        model = models.resnet50(weights=None)
    else:
        raise ValueError("Unknown model")
    
    # Modify first layer: 3 input channels -> 1 input channel
    model.conv1 = nn.Conv2d(1, 64, kernel_size=7, stride=2, padding=3, bias=False)
    
    # Modify final fully connected layer for number of classes
    num_ftrs = model.fc.in_features
    model.fc = nn.Linear(num_ftrs, num_classes)
    
    return model.to(target_device)

## 3. Training and Evaluation Functions
Includes Automatic Mixed Precision (AMP) for efficiency.

In [4]:
def train_one_epoch(model, loader, optimizer, criterion, scaler, epoch_idx, num_epochs, target_device=None):
    """Train one epoch with memory optimization"""
    if target_device is None:
        target_device = device  # Use global device if not specified
    
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0
    
    # Progress bar - set leave=True to keep progress bars visible
    pbar = tqdm(loader, desc=f"Epoch {epoch_idx+1}/{num_epochs} [Train]", leave=True)
    
    for inputs, labels in pbar:
        inputs, labels = inputs.to(target_device, non_blocking=True), labels.to(target_device, non_blocking=True)
        
        optimizer.zero_grad(set_to_none=True)  # Memory optimization: more efficient than zero_grad()
        
        # AMP Context (Updated for new PyTorch versions)
        amp_enabled = (target_device.type == 'cuda')
        with torch.amp.autocast('cuda', enabled=amp_enabled):
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        
        running_loss += loss.item() * inputs.size(0)
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()
        
        # Update progress bar
        pbar.set_postfix({'loss': running_loss/total, 'acc': correct/total})
        
    return running_loss / total, correct / total

def evaluate(model, loader, criterion, target_device=None):
    """Evaluate model with memory optimization"""
    if target_device is None:
        target_device = device  # Use global device if not specified
    
    model.eval()
    running_loss = 0.0
    correct = 0
    total = 0
    
    with torch.no_grad():
        for inputs, labels in loader:
            inputs, labels = inputs.to(target_device, non_blocking=True), labels.to(target_device, non_blocking=True)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            
            running_loss += loss.item() * inputs.size(0)
            _, predicted = outputs.max(1)
            total += labels.size(0)
            correct += predicted.eq(labels).sum().item()
            
    return running_loss / total, correct / total

## 4. Run Experiments
We iterate through the configurations for both MNIST and FashionMNIST.

In [5]:
from sklearn.metrics import f1_score, precision_score, recall_score, classification_report, confusion_matrix

# --- Helper function to display training curves as text ---
def display_training_summary(train_losses, train_accs, val_losses, val_accs, config_str):
    """Display training curves as text summary"""
    print(f"\n    📊 Training Summary for: {config_str}")
    print("    " + "-" * 60)
    print(f"    {'Epoch':<8} {'Train Loss':<12} {'Train Acc':<12} {'Val Loss':<12} {'Val Acc':<12}")
    print("    " + "-" * 60)
    for i in range(len(train_losses)):
        print(f"    {i+1:<8} {train_losses[i]:<12.6f} {train_accs[i]:<12.6f} {val_losses[i]:<12.6f} {val_accs[i]:<12.6f}")
    print("    " + "-" * 60)

def display_metrics_summary(metrics_dict, config_str):
    """Display evaluation metrics as text summary"""
    print(f"\n    📈 Evaluation Metrics:")
    print(f"    ├── Accuracy:  {metrics_dict['accuracy']:.6f}")
    print(f"    ├── F1 Score:  {metrics_dict['f1']:.6f}")
    print(f"    ├── Precision: {metrics_dict['precision']:.6f}")
    print(f"    └── Recall:    {metrics_dict['recall']:.6f}")

# --- MAIN EXPERIMENT GRID for Q1(a) ---
import os

# Ensure directories exist
os.makedirs('models', exist_ok=True)

# ============== RESUME SUPPORT ==============
# Load existing results if available
RESUME_FROM = 1  # Set to the experiment number to resume from (1-indexed)
CSV_PATH = 'grid_search_results_q1a.csv'

if os.path.exists(CSV_PATH) and RESUME_FROM > 1:
    print(f"Loading existing results from {CSV_PATH}...")
    df_existing = pd.read_csv(CSV_PATH)
    results = df_existing.to_dict('records')
    print(f"Loaded {len(results)} existing results. Resuming from experiment #{RESUME_FROM}")
else:
    results = []
    RESUME_FROM = 1
# ============================================

# Hyperparameters
datasets_list = ['MNIST', 'FashionMNIST']
models_list = ['ResNet18', 'ResNet50']
batch_sizes = [16, 32]
optimizers_list = ['SGD', 'Adam']
lrs = [0.001, 0.0001]
pin_memories = [False, True]
epochs_list = [2, 5]

# Constant
USE_AMP = True

# Detect Device and apply GPU optimizations
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Running on {device}")

if device.type == 'cuda':
    torch.backends.cudnn.benchmark = True
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True

start_time_glob = time.time()

# Calculate total number of experiments for progress tracking
total_experiments = (len(datasets_list) * len(batch_sizes) * len(pin_memories) * 
                     len(optimizers_list) * len(lrs) * len(epochs_list) * len(models_list))
current_experiment = 0
print(f"Total experiments to run: {total_experiments}")
print(f"Skipping experiments 1-{RESUME_FROM-1}, starting from #{RESUME_FROM}")
print("=" * 70)

for dataset_name in datasets_list:
    for batch_size in batch_sizes:
        for pin_mem in pin_memories:
            # Prepare Data Loaders once per config
            train_loader, val_loader, test_loader = get_dataloaders(dataset_name, batch_size, pin_memory=pin_mem)
            
            for opt_name in optimizers_list:
                for lr in lrs:
                    for epochs_to_run in epochs_list:
                        for model_name in models_list:
                            current_experiment += 1
                            
                            # Skip already completed experiments
                            if current_experiment < RESUME_FROM:
                                continue
                            
                            progress_pct = (current_experiment / total_experiments) * 100
                            
                            config_str = (f"{dataset_name} | {model_name} | BS={batch_size} | "
                                          f"{opt_name} | LR={lr} | PinMem={pin_mem} | Ep={epochs_to_run}")
                            short_config = f"{dataset_name}_{model_name}_bs{batch_size}_{opt_name}_lr{lr}_pin{pin_mem}_ep{epochs_to_run}"
                            
                            print(f"\n[{current_experiment}/{total_experiments}] ({progress_pct:.1f}%) >>> Running: {config_str}")
                            
                            try:
                                # Init Model
                                model = get_model(model_name).to(device)
                                criterion = nn.CrossEntropyLoss()
                                
                                # Init Optimizer
                                if opt_name == 'SGD':
                                    optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0.9)
                                else:
                                    optimizer = optim.Adam(model.parameters(), lr=lr)
                                
                                # Scaler for AMP
                                scaler = torch.amp.GradScaler('cuda', enabled=USE_AMP)
                                
                                # Training history for this config
                                train_losses, train_accs = [], []
                                val_losses, val_accs = [], []
                                
                                # Train
                                t0 = time.time()
                                for epoch in range(epochs_to_run):
                                    train_loss, train_acc = train_one_epoch(model, train_loader, optimizer, criterion, scaler, epoch, epochs_to_run)
                                    val_loss, val_acc = evaluate(model, val_loader, criterion)
                                    train_losses.append(train_loss)
                                    train_accs.append(train_acc)
                                    val_losses.append(val_loss)
                                    val_accs.append(val_acc)
                                    
                                    # Print epoch summary immediately
                                    print(f"    Epoch {epoch+1}/{epochs_to_run} - Train Loss: {train_loss:.4f}, Train Acc: {100*train_acc:.2f}%, Val Loss: {val_loss:.4f}, Val Acc: {100*val_acc:.2f}%")
                                    
                                duration = time.time() - t0
                                
                                # Final Evaluate on test set
                                test_loss, test_acc = evaluate(model, test_loader, criterion)
                                
                                print(f"    ✅ Done! Val Acc: {val_acc:.6f} | Test Acc: {test_acc:.6f} | Time: {duration:.2f}s")
                                
                                # Calculate F1, Precision, Recall on Test Set
                                model.eval()
                                all_preds = []
                                all_labels = []
                                with torch.no_grad():
                                    for inputs, labels in test_loader:
                                        inputs, labels = inputs.to(device, non_blocking=True), labels.to(device, non_blocking=True)
                                        outputs = model(inputs)
                                        _, preds = torch.max(outputs, 1)
                                        all_preds.extend(preds.cpu().numpy())
                                        all_labels.extend(labels.cpu().numpy())
                                
                                f1 = f1_score(all_labels, all_preds, average='weighted')
                                precision = precision_score(all_labels, all_preds, average='weighted')
                                recall = recall_score(all_labels, all_preds, average='weighted')
                                
                                # --- DISPLAY TRAINING CURVES AS TEXT ---
                                display_training_summary(train_losses, train_accs, val_losses, val_accs, config_str)
                                
                                # --- DISPLAY EVALUATION METRICS AS TEXT ---
                                metrics_dict = {
                                    'accuracy': test_acc,
                                    'f1': f1,
                                    'precision': precision,
                                    'recall': recall
                                }
                                display_metrics_summary(metrics_dict, config_str)
                                
                                # Estimated time remaining
                                elapsed = time.time() - start_time_glob
                                completed_since_resume = current_experiment - RESUME_FROM + 1
                                avg_time_per_exp = elapsed / completed_since_resume
                                remaining_exp = total_experiments - current_experiment
                                eta_seconds = avg_time_per_exp * remaining_exp
                                eta_minutes = eta_seconds / 60
                                print(f"\n    ⏱️  ETA: {eta_minutes:.1f} min remaining ({remaining_exp} experiments left)")
                                
                                # SAVE MODEL
                                save_name = f"{short_config}.pth"
                                save_path = os.path.join('models', save_name)
                                torch.save(model.state_dict(), save_path)
                                print(f"    💾 Saved model to {save_path}")
                                
                                # Store Result
                                results.append({
                                    'Dataset': dataset_name,
                                    'Batch Size': batch_size,
                                    'Optimizer': opt_name,
                                    'Learning Rate': lr,
                                    'Pin Memory': pin_mem,
                                    'Epochs': epochs_to_run,
                                    'Model': model_name,
                                    'Test Accuracy': round(test_acc * 100, 6),
                                    'Training Time (s)': round(duration, 6),
                                    'Model Path': save_path,
                                    'F1 Score': round(f1, 6),
                                    'Precision': round(precision, 6),
                                    'Recall': round(recall, 6)
                                })
                                
                                # Save after each experiment to avoid losing progress
                                df_res = pd.DataFrame(results)
                                df_res.to_csv(CSV_PATH, index=False)
                                
                                # ===== MEMORY CLEANUP =====
                                del model, optimizer, criterion, scaler
                                del train_losses, train_accs, val_losses, val_accs
                                del all_preds, all_labels
                                
                                if torch.cuda.is_available():
                                    torch.cuda.empty_cache()
                                gc.collect()
                                # ==========================
                                
                            except Exception as e:
                                print(f"❌ Error in {config_str}: {e}")
                                import traceback
                                traceback.print_exc()
                                
                                if torch.cuda.is_available():
                                    torch.cuda.empty_cache()
                                gc.collect()
            
            # Clear data loaders
            del train_loader, val_loader, test_loader
            gc.collect()

total_time = time.time() - start_time_glob
print(f"\n{'=' * 70}")
print(f"✅ All Q1(a) Experiments Completed: {current_experiment}/{total_experiments}")
print(f"⏱️  Total Time: {total_time/60:.2f} minutes")
print(f"{'=' * 70}")

Running on cuda
Total experiments to run: 128
Skipping experiments 1-0, starting from #1
======================================================================

100%|██████████| 9.91M/9.91M [00:00<00:00, 41.5MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 1.17MB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 10.5MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 10.6MB/s]

[1/128] (0.8%) >>> Running: MNIST | ResNet18 | BS=16 | SGD | LR=0.001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.1673, Train Acc: 94.74%, Val Loss: 0.0565, Val Acc: 98.17%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.0575, Train Acc: 98.28%, Val Loss: 0.0459, Val Acc: 98.61%
    ✅ Done! Val Acc: 0.986143 | Test Acc: 0.984571 | Time: 117.83s

    📊 Training Summary for: MNIST | ResNet18 | BS=16 | SGD | LR=0.001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.167329     0.947429     0.056465     0.981714
    2        0.057510     0.982776     0.045924     0.986143
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.984571
    ├── F1 Score:  0.984559
    ├── Precision: 0.984693
    └── Recall:    0.984571

    ⏱️  ETA: 278.5 min remaining (127 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs16_SGD_lr0.001_pinFalse_ep2.pth

[2/128] (1.6%) >>> Running: MNIST | ResNet50 | BS=16 | SGD | LR=0.001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.4661, Train Acc: 86.65%, Val Loss: 0.0714, Val Acc: 97.69%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.0913, Train Acc: 97.28%, Val Loss: 0.0641, Val Acc: 98.14%
    ✅ Done! Val Acc: 0.981429 | Test Acc: 0.979429 | Time: 199.78s

    📊 Training Summary for: MNIST | ResNet50 | BS=16 | SGD | LR=0.001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.466121     0.866490     0.071428     0.976857
    2        0.091282     0.972755     0.064110     0.981429
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.979429
    ├── F1 Score:  0.979402
    ├── Precision: 0.979619
    └── Recall:    0.979429

    ⏱️  ETA: 365.4 min remaining (126 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs16_SGD_lr0.001_pinFalse_ep2.pth

[3/128] (2.3%) >>> Running: MNIST | ResNet18 | BS=16 | SGD | LR=0.001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.1680, Train Acc: 94.79%, Val Loss: 0.0523, Val Acc: 98.54%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.0573, Train Acc: 98.32%, Val Loss: 0.0462, Val Acc: 98.63%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0365, Train Acc: 98.85%, Val Loss: 0.0343, Val Acc: 99.06%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0232, Train Acc: 99.29%, Val Loss: 0.0379, Val Acc: 99.00%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0166, Train Acc: 99.47%, Val Loss: 0.0326, Val Acc: 99.01%
    ✅ Done! Val Acc: 0.990143 | Test Acc: 0.988929 | Time: 247.30s

    📊 Training Summary for: MNIST | ResNet18 | BS=16 | SGD | LR=0.001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.168010     0.947878     0.052334     0.985429
    2        0.057333     0.983224     0.046236     0.986286
    3        0.036515     0.988510     0.034309     0.990571
    4        0.023248     0.992898     0.037936     0.990000
    5        0.016628     0.994714     0.032552     0.990143
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.988929
    ├── F1 Score:  0.988922
    ├── Precision: 0.988969
    └── Recall:    0.988929

    ⏱️  ETA: 421.7 min remaining (125 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs16_SGD_lr0.001_pinFalse_ep5.pth

[4/128] (3.1%) >>> Running: MNIST | ResNet50 | BS=16 | SGD | LR=0.001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.4646, Train Acc: 86.83%, Val Loss: 0.0867, Val Acc: 97.57%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.0929, Train Acc: 97.29%, Val Loss: 0.0732, Val Acc: 97.90%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0585, Train Acc: 98.23%, Val Loss: 0.0724, Val Acc: 97.94%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0404, Train Acc: 98.74%, Val Loss: 0.0436, Val Acc: 98.84%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0255, Train Acc: 99.24%, Val Loss: 0.0551, Val Acc: 98.59%
    ✅ Done! Val Acc: 0.985857 | Test Acc: 0.985500 | Time: 480.44s

    📊 Training Summary for: MNIST | ResNet50 | BS=16 | SGD | LR=0.001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.464576     0.868286     0.086694     0.975714
    2        0.092865     0.972898     0.073230     0.979000
    3        0.058533     0.982347     0.072391     0.979429
    4        0.040419     0.987388     0.043646     0.988429
    5        0.025495     0.992408     0.055145     0.985857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.985500
    ├── F1 Score:  0.985480
    ├── Precision: 0.985588
    └── Recall:    0.985500

    ⏱️  ETA: 570.6 min remaining (124 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs16_SGD_lr0.001_pinFalse_ep5.pth

[5/128] (3.9%) >>> Running: MNIST | ResNet18 | BS=16 | SGD | LR=0.0001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.3562, Train Acc: 89.54%, Val Loss: 0.1084, Val Acc: 96.89%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.1207, Train Acc: 96.37%, Val Loss: 0.0737, Val Acc: 97.81%
    ✅ Done! Val Acc: 0.978143 | Test Acc: 0.979071 | Time: 98.52s

    📊 Training Summary for: MNIST | ResNet18 | BS=16 | SGD | LR=0.0001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.356155     0.895429     0.108415     0.968857
    2        0.120685     0.963735     0.073732     0.978143
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.979071
    ├── F1 Score:  0.979063
    ├── Precision: 0.979101
    └── Recall:    0.979071

    ⏱️  ETA: 498.0 min remaining (123 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs16_SGD_lr0.0001_pinFalse_ep2.pth

[6/128] (4.7%) >>> Running: MNIST | ResNet50 | BS=16 | SGD | LR=0.0001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.7829, Train Acc: 73.74%, Val Loss: 0.2134, Val Acc: 93.84%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.2437, Train Acc: 92.48%, Val Loss: 0.1219, Val Acc: 96.37%
    ✅ Done! Val Acc: 0.963714 | Test Acc: 0.962357 | Time: 191.94s

    📊 Training Summary for: MNIST | ResNet50 | BS=16 | SGD | LR=0.0001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.782908     0.737449     0.213421     0.938429
    2        0.243670     0.924816     0.121863     0.963714
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.962357
    ├── F1 Score:  0.962295
    ├── Precision: 0.962366
    └── Recall:    0.962357

    ⏱️  ETA: 482.3 min remaining (122 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs16_SGD_lr0.0001_pinFalse_ep2.pth

[7/128] (5.5%) >>> Running: MNIST | ResNet18 | BS=16 | SGD | LR=0.0001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.3587, Train Acc: 89.52%, Val Loss: 0.1089, Val Acc: 96.69%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.1203, Train Acc: 96.39%, Val Loss: 0.0769, Val Acc: 97.77%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0821, Train Acc: 97.53%, Val Loss: 0.0640, Val Acc: 98.09%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0590, Train Acc: 98.27%, Val Loss: 0.0557, Val Acc: 98.36%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0467, Train Acc: 98.62%, Val Loss: 0.0534, Val Acc: 98.31%
    ✅ Done! Val Acc: 0.983143 | Test Acc: 0.984429 | Time: 247.15s

    📊 Training Summary for: MNIST | ResNet18 | BS=16 | SGD | LR=0.0001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.358699     0.895204     0.108914     0.966857
    2        0.120317     0.963878     0.076862     0.977714
    3        0.082051     0.975265     0.064027     0.980857
    4        0.059037     0.982714     0.055685     0.983571
    5        0.046710     0.986184     0.053385     0.983143
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.984429
    ├── F1 Score:  0.984422
    ├── Precision: 0.984445
    └── Recall:    0.984429

    ⏱️  ETA: 484.7 min remaining (121 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs16_SGD_lr0.0001_pinFalse_ep5.pth

[8/128] (6.2%) >>> Running: MNIST | ResNet50 | BS=16 | SGD | LR=0.0001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.7639, Train Acc: 74.73%, Val Loss: 0.2000, Val Acc: 94.19%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.2284, Train Acc: 92.92%, Val Loss: 0.1228, Val Acc: 96.13%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.1565, Train Acc: 95.12%, Val Loss: 0.0898, Val Acc: 97.29%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.1213, Train Acc: 96.18%, Val Loss: 0.0774, Val Acc: 97.47%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0963, Train Acc: 97.02%, Val Loss: 0.0710, Val Acc: 97.96%
    ✅ Done! Val Acc: 0.979571 | Test Acc: 0.979071 | Time: 477.93s

    📊 Training Summary for: MNIST | ResNet50 | BS=16 | SGD | LR=0.0001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.763933     0.747265     0.200015     0.941857
    2        0.228407     0.929184     0.122773     0.961286
    3        0.156517     0.951184     0.089786     0.972857
    4        0.121323     0.961776     0.077445     0.974714
    5        0.096326     0.970163     0.071031     0.979571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.979071
    ├── F1 Score:  0.979051
    ├── Precision: 0.979120
    └── Recall:    0.979071

    ⏱️  ETA: 544.2 min remaining (120 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs16_SGD_lr0.0001_pinFalse_ep5.pth

[9/128] (7.0%) >>> Running: MNIST | ResNet18 | BS=16 | Adam | LR=0.001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.1882, Train Acc: 94.44%, Val Loss: 0.0747, Val Acc: 97.91%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.0923, Train Acc: 97.47%, Val Loss: 0.0580, Val Acc: 98.31%
    ✅ Done! Val Acc: 0.983143 | Test Acc: 0.983643 | Time: 111.91s

    📊 Training Summary for: MNIST | ResNet18 | BS=16 | Adam | LR=0.001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.188216     0.944429     0.074722     0.979143
    2        0.092307     0.974673     0.057974     0.983143
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.983643
    ├── F1 Score:  0.983615
    ├── Precision: 0.983765
    └── Recall:    0.983643

    ⏱️  ETA: 507.0 min remaining (119 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs16_Adam_lr0.001_pinFalse_ep2.pth

[10/128] (7.8%) >>> Running: MNIST | ResNet50 | BS=16 | Adam | LR=0.001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.4481, Train Acc: 88.59%, Val Loss: 0.2171, Val Acc: 93.84%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.2320, Train Acc: 94.66%, Val Loss: 0.3555, Val Acc: 92.40%
    ✅ Done! Val Acc: 0.924000 | Test Acc: 0.929571 | Time: 218.97s

    📊 Training Summary for: MNIST | ResNet50 | BS=16 | Adam | LR=0.001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.448120     0.885939     0.217065     0.938429
    2        0.232044     0.946633     0.355502     0.924000
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.929571
    ├── F1 Score:  0.928042
    ├── Precision: 0.938517
    └── Recall:    0.929571

    ⏱️  ETA: 498.8 min remaining (118 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs16_Adam_lr0.001_pinFalse_ep2.pth

[11/128] (8.6%) >>> Running: MNIST | ResNet18 | BS=16 | Adam | LR=0.001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.1943, Train Acc: 94.33%, Val Loss: 0.0965, Val Acc: 96.97%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.0943, Train Acc: 97.36%, Val Loss: 0.0460, Val Acc: 98.53%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0651, Train Acc: 98.13%, Val Loss: 0.0501, Val Acc: 98.61%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0562, Train Acc: 98.51%, Val Loss: 0.0510, Val Acc: 98.67%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0412, Train Acc: 98.85%, Val Loss: 0.0316, Val Acc: 99.10%
    ✅ Done! Val Acc: 0.991000 | Test Acc: 0.990143 | Time: 279.89s

    📊 Training Summary for: MNIST | ResNet18 | BS=16 | Adam | LR=0.001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.194281     0.943306     0.096527     0.969714
    2        0.094339     0.973592     0.045979     0.985286
    3        0.065145     0.981306     0.050146     0.986143
    4        0.056194     0.985082     0.051048     0.986714
    5        0.041163     0.988510     0.031597     0.991000
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.990143
    ├── F1 Score:  0.990150
    ├── Precision: 0.990194
    └── Recall:    0.990143

    ⏱️  ETA: 501.3 min remaining (117 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs16_Adam_lr0.001_pinFalse_ep5.pth

[12/128] (9.4%) >>> Running: MNIST | ResNet50 | BS=16 | Adam | LR=0.001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.4258, Train Acc: 89.10%, Val Loss: 0.1736, Val Acc: 95.01%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.2409, Train Acc: 94.72%, Val Loss: 0.1016, Val Acc: 97.19%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.1486, Train Acc: 96.29%, Val Loss: 0.0650, Val Acc: 98.46%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.1184, Train Acc: 97.19%, Val Loss: 0.0488, Val Acc: 98.74%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.1076, Train Acc: 97.44%, Val Loss: 0.0797, Val Acc: 97.90%
    ✅ Done! Val Acc: 0.979000 | Test Acc: 0.974143 | Time: 547.37s

    📊 Training Summary for: MNIST | ResNet50 | BS=16 | Adam | LR=0.001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.425767     0.890980     0.173630     0.950143
    2        0.240858     0.947224     0.101641     0.971857
    3        0.148621     0.962918     0.064973     0.984571
    4        0.118401     0.971898     0.048803     0.987429
    5        0.107575     0.974408     0.079717     0.979000
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.974143
    ├── F1 Score:  0.974149
    ├── Precision: 0.974612
    └── Recall:    0.974143

    ⏱️  ETA: 546.5 min remaining (116 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs16_Adam_lr0.001_pinFalse_ep5.pth

[13/128] (10.2%) >>> Running: MNIST | ResNet18 | BS=16 | Adam | LR=0.0001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.1979, Train Acc: 93.96%, Val Loss: 0.0713, Val Acc: 97.91%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.0795, Train Acc: 97.52%, Val Loss: 0.0473, Val Acc: 98.59%
    ✅ Done! Val Acc: 0.985857 | Test Acc: 0.985643 | Time: 112.08s

    📊 Training Summary for: MNIST | ResNet18 | BS=16 | Adam | LR=0.0001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.197870     0.939571     0.071338     0.979143
    2        0.079525     0.975204     0.047275     0.985857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.985643
    ├── F1 Score:  0.985637
    ├── Precision: 0.985687
    └── Recall:    0.985643

    ⏱️  ETA: 518.3 min remaining (115 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs16_Adam_lr0.0001_pinFalse_ep2.pth

[14/128] (10.9%) >>> Running: MNIST | ResNet50 | BS=16 | Adam | LR=0.0001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.7387, Train Acc: 75.50%, Val Loss: 0.2312, Val Acc: 92.77%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.2133, Train Acc: 93.27%, Val Loss: 0.1082, Val Acc: 96.29%
    ✅ Done! Val Acc: 0.962857 | Test Acc: 0.962571 | Time: 219.65s

    📊 Training Summary for: MNIST | ResNet50 | BS=16 | Adam | LR=0.0001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.738750     0.754980     0.231153     0.927714
    2        0.213309     0.932735     0.108205     0.962857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.962571
    ├── F1 Score:  0.962579
    ├── Precision: 0.963046
    └── Recall:    0.962571

    ⏱️  ETA: 509.2 min remaining (114 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs16_Adam_lr0.0001_pinFalse_ep2.pth

[15/128] (11.7%) >>> Running: MNIST | ResNet18 | BS=16 | Adam | LR=0.0001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.1944, Train Acc: 94.08%, Val Loss: 0.0837, Val Acc: 97.34%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.0765, Train Acc: 97.65%, Val Loss: 0.0622, Val Acc: 98.09%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0512, Train Acc: 98.41%, Val Loss: 0.0530, Val Acc: 98.36%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0403, Train Acc: 98.77%, Val Loss: 0.0399, Val Acc: 98.73%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0309, Train Acc: 99.07%, Val Loss: 0.0508, Val Acc: 98.47%
    ✅ Done! Val Acc: 0.984714 | Test Acc: 0.985786 | Time: 279.90s

    📊 Training Summary for: MNIST | ResNet18 | BS=16 | Adam | LR=0.0001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.194445     0.940755     0.083686     0.973429
    2        0.076466     0.976490     0.062151     0.980857
    3        0.051191     0.984082     0.052979     0.983571
    4        0.040296     0.987694     0.039884     0.987286
    5        0.030906     0.990694     0.050797     0.984714
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.985786
    ├── F1 Score:  0.985750
    ├── Precision: 0.985879
    └── Recall:    0.985786

    ⏱️  ETA: 507.7 min remaining (113 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs16_Adam_lr0.0001_pinFalse_ep5.pth

[16/128] (12.5%) >>> Running: MNIST | ResNet50 | BS=16 | Adam | LR=0.0001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.6939, Train Acc: 76.98%, Val Loss: 0.2089, Val Acc: 93.49%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.2053, Train Acc: 93.69%, Val Loss: 0.1245, Val Acc: 96.09%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.1262, Train Acc: 96.22%, Val Loss: 0.0866, Val Acc: 97.53%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0898, Train Acc: 97.42%, Val Loss: 0.0768, Val Acc: 97.76%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0645, Train Acc: 98.18%, Val Loss: 0.0782, Val Acc: 97.77%
    ✅ Done! Val Acc: 0.977714 | Test Acc: 0.977429 | Time: 549.73s

    📊 Training Summary for: MNIST | ResNet50 | BS=16 | Adam | LR=0.0001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.693931     0.769776     0.208873     0.934857
    2        0.205344     0.936918     0.124495     0.960857
    3        0.126197     0.962163     0.086640     0.975286
    4        0.089821     0.974204     0.076770     0.977571
    5        0.064518     0.981816     0.078188     0.977714
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.977429
    ├── F1 Score:  0.977483
    ├── Precision: 0.977813
    └── Recall:    0.977429

    ⏱️  ETA: 537.8 min remaining (112 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs16_Adam_lr0.0001_pinFalse_ep5.pth

[17/128] (13.3%) >>> Running: MNIST | ResNet18 | BS=16 | SGD | LR=0.001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.1712, Train Acc: 94.64%, Val Loss: 0.0502, Val Acc: 98.46%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.0559, Train Acc: 98.28%, Val Loss: 0.0462, Val Acc: 98.57%
    ✅ Done! Val Acc: 0.985714 | Test Acc: 0.985929 | Time: 99.02s

    📊 Training Summary for: MNIST | ResNet18 | BS=16 | SGD | LR=0.001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.171177     0.946388     0.050207     0.984571
    2        0.055948     0.982837     0.046178     0.985714
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.985929
    ├── F1 Score:  0.985922
    ├── Precision: 0.986024
    └── Recall:    0.985929

    ⏱️  ETA: 513.8 min remaining (111 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs16_SGD_lr0.001_pinTrue_ep2.pth

[18/128] (14.1%) >>> Running: MNIST | ResNet50 | BS=16 | SGD | LR=0.001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.3912, Train Acc: 88.79%, Val Loss: 0.0782, Val Acc: 97.69%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.0859, Train Acc: 97.43%, Val Loss: 0.0598, Val Acc: 98.10%
    ✅ Done! Val Acc: 0.981000 | Test Acc: 0.979929 | Time: 191.21s

    📊 Training Summary for: MNIST | ResNet50 | BS=16 | SGD | LR=0.001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.391150     0.887939     0.078241     0.976857
    2        0.085893     0.974286     0.059834     0.981000
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.979929
    ├── F1 Score:  0.979912
    ├── Precision: 0.980045
    └── Recall:    0.979929

    ⏱️  ETA: 502.1 min remaining (110 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs16_SGD_lr0.001_pinTrue_ep2.pth

[19/128] (14.8%) >>> Running: MNIST | ResNet18 | BS=16 | SGD | LR=0.001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.1695, Train Acc: 94.80%, Val Loss: 0.0576, Val Acc: 98.14%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.0556, Train Acc: 98.27%, Val Loss: 0.0385, Val Acc: 98.91%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0343, Train Acc: 98.89%, Val Loss: 0.0366, Val Acc: 99.01%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0235, Train Acc: 99.23%, Val Loss: 0.0338, Val Acc: 99.06%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0179, Train Acc: 99.46%, Val Loss: 0.0406, Val Acc: 98.94%
    ✅ Done! Val Acc: 0.989429 | Test Acc: 0.989500 | Time: 246.67s

    📊 Training Summary for: MNIST | ResNet18 | BS=16 | SGD | LR=0.001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.169466     0.948000     0.057647     0.981429
    2        0.055626     0.982653     0.038501     0.989143
    3        0.034272     0.988939     0.036606     0.990143
    4        0.023478     0.992327     0.033829     0.990571
    5        0.017880     0.994633     0.040569     0.989429
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.989500
    ├── F1 Score:  0.989486
    ├── Precision: 0.989534
    └── Recall:    0.989500

    ⏱️  ETA: 496.0 min remaining (109 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs16_SGD_lr0.001_pinTrue_ep5.pth

[20/128] (15.6%) >>> Running: MNIST | ResNet50 | BS=16 | SGD | LR=0.001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.4075, Train Acc: 88.44%, Val Loss: 0.0829, Val Acc: 97.53%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.0919, Train Acc: 97.32%, Val Loss: 0.0562, Val Acc: 98.39%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0557, Train Acc: 98.24%, Val Loss: 0.0497, Val Acc: 98.51%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0389, Train Acc: 98.76%, Val Loss: 0.0495, Val Acc: 98.64%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0309, Train Acc: 99.02%, Val Loss: 0.0514, Val Acc: 98.56%
    ✅ Done! Val Acc: 0.985571 | Test Acc: 0.984929 | Time: 476.94s

    📊 Training Summary for: MNIST | ResNet50 | BS=16 | SGD | LR=0.001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.407545     0.884367     0.082947     0.975286
    2        0.091866     0.973224     0.056247     0.983857
    3        0.055658     0.982429     0.049663     0.985143
    4        0.038868     0.987571     0.049510     0.986429
    5        0.030909     0.990184     0.051424     0.985571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.984929
    ├── F1 Score:  0.984926
    ├── Precision: 0.985014
    └── Recall:    0.984929

    ⏱️  ETA: 511.3 min remaining (108 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs16_SGD_lr0.001_pinTrue_ep5.pth

[21/128] (16.4%) >>> Running: MNIST | ResNet18 | BS=16 | SGD | LR=0.0001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.3621, Train Acc: 89.27%, Val Loss: 0.1025, Val Acc: 97.26%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.1232, Train Acc: 96.31%, Val Loss: 0.0688, Val Acc: 98.09%
    ✅ Done! Val Acc: 0.980857 | Test Acc: 0.977143 | Time: 98.01s

    📊 Training Summary for: MNIST | ResNet18 | BS=16 | SGD | LR=0.0001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.362120     0.892714     0.102479     0.972571
    2        0.123173     0.963122     0.068818     0.980857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.977143
    ├── F1 Score:  0.977135
    ├── Precision: 0.977207
    └── Recall:    0.977143

    ⏱️  ETA: 491.8 min remaining (107 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs16_SGD_lr0.0001_pinTrue_ep2.pth

[22/128] (17.2%) >>> Running: MNIST | ResNet50 | BS=16 | SGD | LR=0.0001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.7475, Train Acc: 75.18%, Val Loss: 0.1864, Val Acc: 94.49%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.2275, Train Acc: 92.91%, Val Loss: 0.1117, Val Acc: 96.83%
    ✅ Done! Val Acc: 0.968286 | Test Acc: 0.961857 | Time: 190.48s

    📊 Training Summary for: MNIST | ResNet50 | BS=16 | SGD | LR=0.0001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.747511     0.751776     0.186414     0.944857
    2        0.227542     0.929122     0.111678     0.968286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.961857
    ├── F1 Score:  0.961790
    ├── Precision: 0.962302
    └── Recall:    0.961857

    ⏱️  ETA: 481.7 min remaining (106 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs16_SGD_lr0.0001_pinTrue_ep2.pth

[23/128] (18.0%) >>> Running: MNIST | ResNet18 | BS=16 | SGD | LR=0.0001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.3486, Train Acc: 89.78%, Val Loss: 0.1060, Val Acc: 96.93%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.1164, Train Acc: 96.53%, Val Loss: 0.0775, Val Acc: 97.60%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0784, Train Acc: 97.69%, Val Loss: 0.0615, Val Acc: 98.27%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0580, Train Acc: 98.22%, Val Loss: 0.0569, Val Acc: 98.26%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0427, Train Acc: 98.74%, Val Loss: 0.0529, Val Acc: 98.44%
    ✅ Done! Val Acc: 0.984429 | Test Acc: 0.984786 | Time: 246.14s

    📊 Training Summary for: MNIST | ResNet18 | BS=16 | SGD | LR=0.0001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.348620     0.897755     0.106023     0.969286
    2        0.116369     0.965265     0.077547     0.976000
    3        0.078362     0.976878     0.061549     0.982714
    4        0.058027     0.982245     0.056854     0.982571
    5        0.042670     0.987367     0.052862     0.984429
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.984786
    ├── F1 Score:  0.984783
    ├── Precision: 0.984809
    └── Recall:    0.984786

    ⏱️  ETA: 476.0 min remaining (105 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs16_SGD_lr0.0001_pinTrue_ep5.pth

[24/128] (18.8%) >>> Running: MNIST | ResNet50 | BS=16 | SGD | LR=0.0001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.7766, Train Acc: 74.25%, Val Loss: 0.2179, Val Acc: 93.57%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.2437, Train Acc: 92.35%, Val Loss: 0.1315, Val Acc: 95.86%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.1675, Train Acc: 94.73%, Val Loss: 0.1032, Val Acc: 96.89%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.1276, Train Acc: 96.04%, Val Loss: 0.0895, Val Acc: 97.33%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.1003, Train Acc: 96.88%, Val Loss: 0.0764, Val Acc: 97.67%
    ✅ Done! Val Acc: 0.976714 | Test Acc: 0.976643 | Time: 477.64s

    📊 Training Summary for: MNIST | ResNet50 | BS=16 | SGD | LR=0.0001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.776583     0.742510     0.217898     0.935714
    2        0.243704     0.923469     0.131497     0.958571
    3        0.167452     0.947347     0.103244     0.968857
    4        0.127567     0.960429     0.089540     0.973286
    5        0.100299     0.968796     0.076377     0.976714
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.976643
    ├── F1 Score:  0.976619
    ├── Precision: 0.976655
    └── Recall:    0.976643

    ⏱️  ETA: 487.5 min remaining (104 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs16_SGD_lr0.0001_pinTrue_ep5.pth

[25/128] (19.5%) >>> Running: MNIST | ResNet18 | BS=16 | Adam | LR=0.001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.1895, Train Acc: 94.54%, Val Loss: 0.0691, Val Acc: 98.14%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.0897, Train Acc: 97.48%, Val Loss: 0.0542, Val Acc: 98.60%
    ✅ Done! Val Acc: 0.986000 | Test Acc: 0.983214 | Time: 111.78s

    📊 Training Summary for: MNIST | ResNet18 | BS=16 | Adam | LR=0.001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.189518     0.945388     0.069139     0.981429
    2        0.089732     0.974816     0.054196     0.986000
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.983214
    ├── F1 Score:  0.983209
    ├── Precision: 0.983333
    └── Recall:    0.983214

    ⏱️  ETA: 472.0 min remaining (103 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs16_Adam_lr0.001_pinTrue_ep2.pth

[26/128] (20.3%) >>> Running: MNIST | ResNet50 | BS=16 | Adam | LR=0.001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.4209, Train Acc: 89.40%, Val Loss: 0.1205, Val Acc: 96.54%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.2370, Train Acc: 94.35%, Val Loss: 0.2625, Val Acc: 94.54%
    ✅ Done! Val Acc: 0.945429 | Test Acc: 0.947571 | Time: 219.79s

    📊 Training Summary for: MNIST | ResNet50 | BS=16 | Adam | LR=0.001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.420864     0.894020     0.120538     0.965429
    2        0.236999     0.943490     0.262459     0.945429
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.947571
    ├── F1 Score:  0.947435
    ├── Precision: 0.951283
    └── Recall:    0.947571

    ⏱️  ETA: 464.9 min remaining (102 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs16_Adam_lr0.001_pinTrue_ep2.pth

[27/128] (21.1%) >>> Running: MNIST | ResNet18 | BS=16 | Adam | LR=0.001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.1994, Train Acc: 94.22%, Val Loss: 0.0685, Val Acc: 97.96%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.0943, Train Acc: 97.40%, Val Loss: 0.0559, Val Acc: 98.34%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0696, Train Acc: 98.09%, Val Loss: 0.0500, Val Acc: 98.47%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0556, Train Acc: 98.49%, Val Loss: 0.0467, Val Acc: 98.67%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0396, Train Acc: 98.89%, Val Loss: 0.0432, Val Acc: 98.81%
    ✅ Done! Val Acc: 0.988143 | Test Acc: 0.985214 | Time: 281.35s

    📊 Training Summary for: MNIST | ResNet18 | BS=16 | Adam | LR=0.001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.199366     0.942224     0.068522     0.979571
    2        0.094320     0.974020     0.055921     0.983429
    3        0.069609     0.980918     0.050010     0.984714
    4        0.055592     0.984898     0.046667     0.986714
    5        0.039555     0.988939     0.043205     0.988143
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.985214
    ├── F1 Score:  0.985203
    ├── Precision: 0.985323
    └── Recall:    0.985214

    ⏱️  ETA: 461.6 min remaining (101 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs16_Adam_lr0.001_pinTrue_ep5.pth

[28/128] (21.9%) >>> Running: MNIST | ResNet50 | BS=16 | Adam | LR=0.001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.4164, Train Acc: 89.62%, Val Loss: 0.2229, Val Acc: 94.16%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.2619, Train Acc: 94.39%, Val Loss: 0.1039, Val Acc: 97.26%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.1747, Train Acc: 95.85%, Val Loss: 0.1917, Val Acc: 94.36%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.1137, Train Acc: 96.98%, Val Loss: 0.0550, Val Acc: 98.61%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0925, Train Acc: 97.56%, Val Loss: 0.0556, Val Acc: 98.27%
    ✅ Done! Val Acc: 0.982714 | Test Acc: 0.983143 | Time: 550.71s

    📊 Training Summary for: MNIST | ResNet50 | BS=16 | Adam | LR=0.001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.416387     0.896184     0.222932     0.941571
    2        0.261940     0.943898     0.103877     0.972571
    3        0.174720     0.958531     0.191688     0.943571
    4        0.113694     0.969755     0.055047     0.986143
    5        0.092500     0.975592     0.055641     0.982714
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.983143
    ├── F1 Score:  0.983137
    ├── Precision: 0.983200
    └── Recall:    0.983143

    ⏱️  ETA: 474.5 min remaining (100 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs16_Adam_lr0.001_pinTrue_ep5.pth

[29/128] (22.7%) >>> Running: MNIST | ResNet18 | BS=16 | Adam | LR=0.0001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.2045, Train Acc: 93.71%, Val Loss: 0.0801, Val Acc: 97.40%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.0763, Train Acc: 97.65%, Val Loss: 0.0544, Val Acc: 98.29%
    ✅ Done! Val Acc: 0.982857 | Test Acc: 0.983500 | Time: 112.32s

    📊 Training Summary for: MNIST | ResNet18 | BS=16 | Adam | LR=0.0001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.204484     0.937143     0.080094     0.974000
    2        0.076330     0.976469     0.054392     0.982857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.983500
    ├── F1 Score:  0.983498
    ├── Precision: 0.983524
    └── Recall:    0.983500

    ⏱️  ETA: 460.6 min remaining (99 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs16_Adam_lr0.0001_pinTrue_ep2.pth

[30/128] (23.4%) >>> Running: MNIST | ResNet50 | BS=16 | Adam | LR=0.0001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.7232, Train Acc: 76.15%, Val Loss: 0.2172, Val Acc: 92.91%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.2179, Train Acc: 93.18%, Val Loss: 0.1272, Val Acc: 95.96%
    ✅ Done! Val Acc: 0.959571 | Test Acc: 0.956929 | Time: 219.35s

    📊 Training Summary for: MNIST | ResNet50 | BS=16 | Adam | LR=0.0001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.723206     0.761510     0.217174     0.929143
    2        0.217891     0.931796     0.127205     0.959571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.956929
    ├── F1 Score:  0.956840
    ├── Precision: 0.957508
    └── Recall:    0.956929

    ⏱️  ETA: 453.6 min remaining (98 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs16_Adam_lr0.0001_pinTrue_ep2.pth

[31/128] (24.2%) >>> Running: MNIST | ResNet18 | BS=16 | Adam | LR=0.0001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.2056, Train Acc: 93.52%, Val Loss: 0.0756, Val Acc: 97.80%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.0757, Train Acc: 97.66%, Val Loss: 0.0540, Val Acc: 98.40%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0554, Train Acc: 98.28%, Val Loss: 0.0406, Val Acc: 98.63%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0420, Train Acc: 98.61%, Val Loss: 0.0593, Val Acc: 98.09%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0302, Train Acc: 99.06%, Val Loss: 0.0371, Val Acc: 98.93%
    ✅ Done! Val Acc: 0.989286 | Test Acc: 0.987571 | Time: 279.81s

    📊 Training Summary for: MNIST | ResNet18 | BS=16 | Adam | LR=0.0001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.205628     0.935245     0.075615     0.978000
    2        0.075671     0.976571     0.053966     0.984000
    3        0.055431     0.982776     0.040609     0.986286
    4        0.041963     0.986143     0.059322     0.980857
    5        0.030178     0.990551     0.037058     0.989286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.987571
    ├── F1 Score:  0.987564
    ├── Precision: 0.987598
    └── Recall:    0.987571

    ⏱️  ETA: 449.7 min remaining (97 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs16_Adam_lr0.0001_pinTrue_ep5.pth

[32/128] (25.0%) >>> Running: MNIST | ResNet50 | BS=16 | Adam | LR=0.0001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.7277, Train Acc: 75.82%, Val Loss: 0.2315, Val Acc: 92.49%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.2118, Train Acc: 93.54%, Val Loss: 0.1251, Val Acc: 96.30%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.1269, Train Acc: 96.20%, Val Loss: 0.0775, Val Acc: 97.84%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0875, Train Acc: 97.46%, Val Loss: 0.0723, Val Acc: 97.97%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0638, Train Acc: 98.16%, Val Loss: 0.0741, Val Acc: 98.03%
    ✅ Done! Val Acc: 0.980286 | Test Acc: 0.977357 | Time: 549.82s

    📊 Training Summary for: MNIST | ResNet50 | BS=16 | Adam | LR=0.0001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.727674     0.758245     0.231493     0.924857
    2        0.211779     0.935367     0.125093     0.963000
    3        0.126893     0.961980     0.077519     0.978429
    4        0.087509     0.974633     0.072262     0.979714
    5        0.063811     0.981592     0.074144     0.980286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.977357
    ├── F1 Score:  0.977407
    ├── Precision: 0.977772
    └── Recall:    0.977357

    ⏱️  ETA: 459.5 min remaining (96 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs16_Adam_lr0.0001_pinTrue_ep5.pth

[33/128] (25.8%) >>> Running: MNIST | ResNet18 | BS=32 | SGD | LR=0.001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.1656, Train Acc: 94.90%, Val Loss: 0.0584, Val Acc: 98.39%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.0508, Train Acc: 98.39%, Val Loss: 0.0451, Val Acc: 98.41%
    ✅ Done! Val Acc: 0.984143 | Test Acc: 0.986357 | Time: 67.73s

    📊 Training Summary for: MNIST | ResNet18 | BS=32 | SGD | LR=0.001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.165632     0.949020     0.058364     0.983857
    2        0.050784     0.983898     0.045062     0.984143
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.986357
    ├── F1 Score:  0.986360
    ├── Precision: 0.986401
    └── Recall:    0.986357

    ⏱️  ETA: 444.6 min remaining (95 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs32_SGD_lr0.001_pinFalse_ep2.pth

[34/128] (26.6%) >>> Running: MNIST | ResNet50 | BS=32 | SGD | LR=0.001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.4106, Train Acc: 87.00%, Val Loss: 0.0967, Val Acc: 97.21%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.1008, Train Acc: 96.93%, Val Loss: 0.0693, Val Acc: 97.86%
    ✅ Done! Val Acc: 0.978571 | Test Acc: 0.979643 | Time: 109.96s

    📊 Training Summary for: MNIST | ResNet50 | BS=32 | SGD | LR=0.001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.410637     0.869959     0.096727     0.972143
    2        0.100792     0.969347     0.069342     0.978571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.979643
    ├── F1 Score:  0.979632
    ├── Precision: 0.979748
    └── Recall:    0.979643

    ⏱️  ETA: 432.6 min remaining (94 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs32_SGD_lr0.001_pinFalse_ep2.pth

[35/128] (27.3%) >>> Running: MNIST | ResNet18 | BS=32 | SGD | LR=0.001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.1673, Train Acc: 94.90%, Val Loss: 0.0595, Val Acc: 97.99%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.0575, Train Acc: 98.21%, Val Loss: 0.0470, Val Acc: 98.50%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0290, Train Acc: 99.07%, Val Loss: 0.0397, Val Acc: 98.79%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0178, Train Acc: 99.44%, Val Loss: 0.0414, Val Acc: 98.81%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0136, Train Acc: 99.56%, Val Loss: 0.0381, Val Acc: 98.86%
    ✅ Done! Val Acc: 0.988571 | Test Acc: 0.988214 | Time: 151.39s

    📊 Training Summary for: MNIST | ResNet18 | BS=32 | SGD | LR=0.001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.167267     0.949041     0.059514     0.979857
    2        0.057496     0.982102     0.046993     0.985000
    3        0.029047     0.990714     0.039689     0.987857
    4        0.017824     0.994367     0.041433     0.988143
    5        0.013615     0.995633     0.038056     0.988571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.988214
    ├── F1 Score:  0.988217
    ├── Precision: 0.988240
    └── Recall:    0.988214

    ⏱️  ETA: 422.9 min remaining (93 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs32_SGD_lr0.001_pinFalse_ep5.pth

[36/128] (28.1%) >>> Running: MNIST | ResNet50 | BS=32 | SGD | LR=0.001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.4085, Train Acc: 87.21%, Val Loss: 0.1081, Val Acc: 96.61%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.0964, Train Acc: 97.00%, Val Loss: 0.0767, Val Acc: 97.86%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0561, Train Acc: 98.25%, Val Loss: 0.0595, Val Acc: 98.34%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0380, Train Acc: 98.76%, Val Loss: 0.0544, Val Acc: 98.16%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0246, Train Acc: 99.23%, Val Loss: 0.0514, Val Acc: 98.59%
    ✅ Done! Val Acc: 0.985857 | Test Acc: 0.987000 | Time: 269.34s

    📊 Training Summary for: MNIST | ResNet50 | BS=32 | SGD | LR=0.001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.408484     0.872061     0.108104     0.966143
    2        0.096435     0.970041     0.076715     0.978571
    3        0.056123     0.982531     0.059514     0.983429
    4        0.038000     0.987551     0.054434     0.981571
    5        0.024570     0.992347     0.051386     0.985857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.987000
    ├── F1 Score:  0.986984
    ├── Precision: 0.987025
    └── Recall:    0.987000

    ⏱️  ETA: 418.7 min remaining (92 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs32_SGD_lr0.001_pinFalse_ep5.pth

[37/128] (28.9%) >>> Running: MNIST | ResNet18 | BS=32 | SGD | LR=0.0001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.4515, Train Acc: 87.37%, Val Loss: 0.1419, Val Acc: 96.11%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.1354, Train Acc: 96.02%, Val Loss: 0.0919, Val Acc: 97.29%
    ✅ Done! Val Acc: 0.972857 | Test Acc: 0.970286 | Time: 60.67s

    📊 Training Summary for: MNIST | ResNet18 | BS=32 | SGD | LR=0.0001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.451471     0.873735     0.141950     0.961143
    2        0.135412     0.960204     0.091946     0.972857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.970286
    ├── F1 Score:  0.970255
    ├── Precision: 0.970373
    └── Recall:    0.970286

    ⏱️  ETA: 405.8 min remaining (91 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs32_SGD_lr0.0001_pinFalse_ep2.pth

[38/128] (29.7%) >>> Running: MNIST | ResNet50 | BS=32 | SGD | LR=0.0001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 1.1901, Train Acc: 60.05%, Val Loss: 0.4127, Val Acc: 87.40%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.3453, Train Acc: 89.21%, Val Loss: 0.2132, Val Acc: 93.34%
    ✅ Done! Val Acc: 0.933429 | Test Acc: 0.933643 | Time: 107.23s

    📊 Training Summary for: MNIST | ResNet50 | BS=32 | SGD | LR=0.0001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        1.190067     0.600490     0.412679     0.874000
    2        0.345319     0.892143     0.213204     0.933429
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.933643
    ├── F1 Score:  0.933532
    ├── Precision: 0.933738
    └── Recall:    0.933643

    ⏱️  ETA: 395.5 min remaining (90 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs32_SGD_lr0.0001_pinFalse_ep2.pth

[39/128] (30.5%) >>> Running: MNIST | ResNet18 | BS=32 | SGD | LR=0.0001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.4523, Train Acc: 87.22%, Val Loss: 0.1461, Val Acc: 95.86%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.1397, Train Acc: 95.94%, Val Loss: 0.0989, Val Acc: 97.13%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0943, Train Acc: 97.23%, Val Loss: 0.0835, Val Acc: 97.61%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0689, Train Acc: 98.06%, Val Loss: 0.0730, Val Acc: 97.80%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0541, Train Acc: 98.47%, Val Loss: 0.0691, Val Acc: 97.90%
    ✅ Done! Val Acc: 0.979000 | Test Acc: 0.976286 | Time: 151.94s

    📊 Training Summary for: MNIST | ResNet18 | BS=32 | SGD | LR=0.0001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.452332     0.872224     0.146072     0.958571
    2        0.139710     0.959408     0.098931     0.971286
    3        0.094347     0.972347     0.083494     0.976143
    4        0.068909     0.980551     0.073022     0.978000
    5        0.054059     0.984694     0.069125     0.979000
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.976286
    ├── F1 Score:  0.976263
    ├── Precision: 0.976326
    └── Recall:    0.976286

    ⏱️  ETA: 387.2 min remaining (89 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs32_SGD_lr0.0001_pinFalse_ep5.pth

[40/128] (31.2%) >>> Running: MNIST | ResNet50 | BS=32 | SGD | LR=0.0001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 1.1015, Train Acc: 63.27%, Val Loss: 0.3274, Val Acc: 90.56%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.2823, Train Acc: 91.19%, Val Loss: 0.1839, Val Acc: 94.06%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.1866, Train Acc: 94.09%, Val Loss: 0.1360, Val Acc: 95.83%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.1399, Train Acc: 95.62%, Val Loss: 0.1208, Val Acc: 96.46%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.1113, Train Acc: 96.39%, Val Loss: 0.1051, Val Acc: 96.87%
    ✅ Done! Val Acc: 0.968714 | Test Acc: 0.968214 | Time: 266.91s

    📊 Training Summary for: MNIST | ResNet50 | BS=32 | SGD | LR=0.0001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        1.101540     0.632653     0.327356     0.905571
    2        0.282322     0.911878     0.183852     0.940571
    3        0.186610     0.940898     0.135991     0.958286
    4        0.139945     0.956245     0.120788     0.964571
    5        0.111282     0.963878     0.105084     0.968714
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.968214
    ├── F1 Score:  0.968192
    ├── Precision: 0.968242
    └── Recall:    0.968214

    ⏱️  ETA: 383.5 min remaining (88 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs32_SGD_lr0.0001_pinFalse_ep5.pth

[41/128] (32.0%) >>> Running: MNIST | ResNet18 | BS=32 | Adam | LR=0.001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.1663, Train Acc: 95.14%, Val Loss: 0.0911, Val Acc: 97.20%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.0752, Train Acc: 97.86%, Val Loss: 0.0661, Val Acc: 98.23%
    ✅ Done! Val Acc: 0.982286 | Test Acc: 0.979500 | Time: 67.03s

    📊 Training Summary for: MNIST | ResNet18 | BS=32 | Adam | LR=0.001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.166342     0.951408     0.091077     0.972000
    2        0.075230     0.978551     0.066085     0.982286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.979500
    ├── F1 Score:  0.979437
    ├── Precision: 0.979854
    └── Recall:    0.979500

    ⏱️  ETA: 372.6 min remaining (87 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs32_Adam_lr0.001_pinFalse_ep2.pth

[42/128] (32.8%) >>> Running: MNIST | ResNet50 | BS=32 | Adam | LR=0.001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.3238, Train Acc: 91.03%, Val Loss: 0.1472, Val Acc: 95.77%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.2046, Train Acc: 95.40%, Val Loss: 0.1268, Val Acc: 96.17%
    ✅ Done! Val Acc: 0.961714 | Test Acc: 0.960429 | Time: 120.78s

    📊 Training Summary for: MNIST | ResNet50 | BS=32 | Adam | LR=0.001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.323773     0.910265     0.147208     0.957714
    2        0.204603     0.954000     0.126777     0.961714
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.960429
    ├── F1 Score:  0.960422
    ├── Precision: 0.961640
    └── Recall:    0.960429

    ⏱️  ETA: 364.1 min remaining (86 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs32_Adam_lr0.001_pinFalse_ep2.pth

[43/128] (33.6%) >>> Running: MNIST | ResNet18 | BS=32 | Adam | LR=0.001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.1640, Train Acc: 95.08%, Val Loss: 0.0805, Val Acc: 97.51%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.0739, Train Acc: 97.85%, Val Loss: 0.0589, Val Acc: 98.21%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0541, Train Acc: 98.39%, Val Loss: 0.0458, Val Acc: 98.67%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0474, Train Acc: 98.63%, Val Loss: 0.0420, Val Acc: 98.80%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0416, Train Acc: 98.81%, Val Loss: 0.0375, Val Acc: 98.81%
    ✅ Done! Val Acc: 0.988143 | Test Acc: 0.987786 | Time: 167.44s

    📊 Training Summary for: MNIST | ResNet18 | BS=32 | Adam | LR=0.001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.164000     0.950796     0.080549     0.975143
    2        0.073933     0.978510     0.058949     0.982143
    3        0.054133     0.983898     0.045752     0.986714
    4        0.047392     0.986306     0.041995     0.988000
    5        0.041594     0.988061     0.037541     0.988143
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.987786
    ├── F1 Score:  0.987774
    ├── Precision: 0.987875
    └── Recall:    0.987786

    ⏱️  ETA: 357.3 min remaining (85 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs32_Adam_lr0.001_pinFalse_ep5.pth

[44/128] (34.4%) >>> Running: MNIST | ResNet50 | BS=32 | Adam | LR=0.001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.3420, Train Acc: 90.94%, Val Loss: 0.1526, Val Acc: 95.81%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.1157, Train Acc: 96.95%, Val Loss: 0.0588, Val Acc: 98.21%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.1077, Train Acc: 97.18%, Val Loss: 0.0547, Val Acc: 98.30%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.1918, Train Acc: 95.83%, Val Loss: 0.0916, Val Acc: 97.54%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0758, Train Acc: 97.97%, Val Loss: 0.0492, Val Acc: 98.69%
    ✅ Done! Val Acc: 0.986857 | Test Acc: 0.985357 | Time: 301.58s

    📊 Training Summary for: MNIST | ResNet50 | BS=32 | Adam | LR=0.001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.341973     0.909449     0.152585     0.958143
    2        0.115697     0.969490     0.058843     0.982143
    3        0.107665     0.971755     0.054712     0.983000
    4        0.191820     0.958347     0.091589     0.975429
    5        0.075830     0.979714     0.049156     0.986857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.985357
    ├── F1 Score:  0.985354
    ├── Precision: 0.985445
    └── Recall:    0.985357

    ⏱️  ETA: 355.1 min remaining (84 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs32_Adam_lr0.001_pinFalse_ep5.pth

[45/128] (35.2%) >>> Running: MNIST | ResNet18 | BS=32 | Adam | LR=0.0001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.1876, Train Acc: 94.31%, Val Loss: 0.0815, Val Acc: 97.54%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.0692, Train Acc: 97.78%, Val Loss: 0.0662, Val Acc: 98.11%
    ✅ Done! Val Acc: 0.981143 | Test Acc: 0.978429 | Time: 66.25s

    📊 Training Summary for: MNIST | ResNet18 | BS=32 | Adam | LR=0.0001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.187637     0.943143     0.081502     0.975429
    2        0.069237     0.977816     0.066208     0.981143
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.978429
    ├── F1 Score:  0.978422
    ├── Precision: 0.978713
    └── Recall:    0.978429

    ⏱️  ETA: 345.4 min remaining (83 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs32_Adam_lr0.0001_pinFalse_ep2.pth

[46/128] (35.9%) >>> Running: MNIST | ResNet50 | BS=32 | Adam | LR=0.0001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.7247, Train Acc: 75.82%, Val Loss: 0.2399, Val Acc: 92.39%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.2149, Train Acc: 93.13%, Val Loss: 0.1504, Val Acc: 95.19%
    ✅ Done! Val Acc: 0.951857 | Test Acc: 0.952571 | Time: 120.63s

    📊 Training Summary for: MNIST | ResNet50 | BS=32 | Adam | LR=0.0001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.724687     0.758184     0.239948     0.923857
    2        0.214915     0.931327     0.150403     0.951857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.952571
    ├── F1 Score:  0.952540
    ├── Precision: 0.952824
    └── Recall:    0.952571

    ⏱️  ETA: 337.7 min remaining (82 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs32_Adam_lr0.0001_pinFalse_ep2.pth

[47/128] (36.7%) >>> Running: MNIST | ResNet18 | BS=32 | Adam | LR=0.0001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.1873, Train Acc: 94.22%, Val Loss: 0.0699, Val Acc: 97.83%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.0695, Train Acc: 97.85%, Val Loss: 0.0598, Val Acc: 98.11%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0462, Train Acc: 98.54%, Val Loss: 0.0592, Val Acc: 98.46%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0356, Train Acc: 98.83%, Val Loss: 0.0465, Val Acc: 98.61%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0293, Train Acc: 99.09%, Val Loss: 0.0415, Val Acc: 98.76%
    ✅ Done! Val Acc: 0.987571 | Test Acc: 0.986571 | Time: 166.39s

    📊 Training Summary for: MNIST | ResNet18 | BS=32 | Adam | LR=0.0001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.187343     0.942224     0.069883     0.978286
    2        0.069515     0.978510     0.059786     0.981143
    3        0.046163     0.985449     0.059158     0.984571
    4        0.035569     0.988347     0.046527     0.986143
    5        0.029256     0.990939     0.041545     0.987571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.986571
    ├── F1 Score:  0.986566
    ├── Precision: 0.986625
    └── Recall:    0.986571

    ⏱️  ETA: 331.5 min remaining (81 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs32_Adam_lr0.0001_pinFalse_ep5.pth

[48/128] (37.5%) >>> Running: MNIST | ResNet50 | BS=32 | Adam | LR=0.0001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.7848, Train Acc: 73.69%, Val Loss: 0.2829, Val Acc: 90.84%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.2409, Train Acc: 92.37%, Val Loss: 0.1566, Val Acc: 95.27%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.1286, Train Acc: 95.88%, Val Loss: 0.1287, Val Acc: 95.87%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0953, Train Acc: 96.96%, Val Loss: 0.0949, Val Acc: 97.20%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0673, Train Acc: 97.86%, Val Loss: 0.1031, Val Acc: 96.93%
    ✅ Done! Val Acc: 0.969286 | Test Acc: 0.969857 | Time: 302.12s

    📊 Training Summary for: MNIST | ResNet50 | BS=32 | Adam | LR=0.0001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.784775     0.736857     0.282862     0.908429
    2        0.240850     0.923735     0.156618     0.952714
    3        0.128614     0.958755     0.128691     0.958714
    4        0.095275     0.969592     0.094863     0.972000
    5        0.067303     0.978633     0.103083     0.969286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.969857
    ├── F1 Score:  0.969786
    ├── Precision: 0.970106
    └── Recall:    0.969857

    ⏱️  ETA: 329.3 min remaining (80 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs32_Adam_lr0.0001_pinFalse_ep5.pth

[49/128] (38.3%) >>> Running: MNIST | ResNet18 | BS=32 | SGD | LR=0.001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.1654, Train Acc: 94.88%, Val Loss: 0.0599, Val Acc: 97.99%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.0513, Train Acc: 98.42%, Val Loss: 0.0492, Val Acc: 98.53%
    ✅ Done! Val Acc: 0.985286 | Test Acc: 0.986429 | Time: 60.59s

    📊 Training Summary for: MNIST | ResNet18 | BS=32 | SGD | LR=0.001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.165445     0.948776     0.059940     0.979857
    2        0.051321     0.984245     0.049177     0.985286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.986429
    ├── F1 Score:  0.986419
    ├── Precision: 0.986448
    └── Recall:    0.986429

    ⏱️  ETA: 320.5 min remaining (79 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs32_SGD_lr0.001_pinTrue_ep2.pth

[50/128] (39.1%) >>> Running: MNIST | ResNet50 | BS=32 | SGD | LR=0.001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.4417, Train Acc: 86.19%, Val Loss: 0.1201, Val Acc: 96.47%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.1069, Train Acc: 96.68%, Val Loss: 0.0697, Val Acc: 97.97%
    ✅ Done! Val Acc: 0.979714 | Test Acc: 0.978071 | Time: 106.85s

    📊 Training Summary for: MNIST | ResNet50 | BS=32 | SGD | LR=0.001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.441652     0.861939     0.120131     0.964714
    2        0.106906     0.966796     0.069730     0.979714
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.978071
    ├── F1 Score:  0.978073
    ├── Precision: 0.978192
    └── Recall:    0.978071

    ⏱️  ETA: 313.2 min remaining (78 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs32_SGD_lr0.001_pinTrue_ep2.pth

[51/128] (39.8%) >>> Running: MNIST | ResNet18 | BS=32 | SGD | LR=0.001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.1730, Train Acc: 94.56%, Val Loss: 0.0572, Val Acc: 98.33%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.0547, Train Acc: 98.33%, Val Loss: 0.0432, Val Acc: 98.69%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0302, Train Acc: 99.03%, Val Loss: 0.0389, Val Acc: 98.77%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0196, Train Acc: 99.43%, Val Loss: 0.0391, Val Acc: 98.96%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0139, Train Acc: 99.54%, Val Loss: 0.0417, Val Acc: 98.76%
    ✅ Done! Val Acc: 0.987571 | Test Acc: 0.987214 | Time: 150.73s

    📊 Training Summary for: MNIST | ResNet18 | BS=32 | SGD | LR=0.001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.173033     0.945612     0.057247     0.983286
    2        0.054737     0.983265     0.043229     0.986857
    3        0.030211     0.990347     0.038889     0.987714
    4        0.019641     0.994327     0.039063     0.989571
    5        0.013910     0.995408     0.041699     0.987571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.987214
    ├── F1 Score:  0.987208
    ├── Precision: 0.987223
    └── Recall:    0.987214

    ⏱️  ETA: 307.1 min remaining (77 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs32_SGD_lr0.001_pinTrue_ep5.pth

[52/128] (40.6%) >>> Running: MNIST | ResNet50 | BS=32 | SGD | LR=0.001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.3663, Train Acc: 88.36%, Val Loss: 0.1019, Val Acc: 96.81%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.0941, Train Acc: 97.07%, Val Loss: 0.0847, Val Acc: 97.24%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0534, Train Acc: 98.34%, Val Loss: 0.0640, Val Acc: 98.31%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0358, Train Acc: 98.83%, Val Loss: 0.0557, Val Acc: 98.27%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0294, Train Acc: 99.03%, Val Loss: 0.0541, Val Acc: 98.47%
    ✅ Done! Val Acc: 0.984714 | Test Acc: 0.985714 | Time: 266.12s

    📊 Training Summary for: MNIST | ResNet50 | BS=32 | SGD | LR=0.001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.366337     0.883592     0.101866     0.968143
    2        0.094057     0.970653     0.084674     0.972429
    3        0.053443     0.983388     0.063951     0.983143
    4        0.035773     0.988265     0.055692     0.982714
    5        0.029449     0.990306     0.054102     0.984714
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.985714
    ├── F1 Score:  0.985710
    ├── Precision: 0.985758
    └── Recall:    0.985714

    ⏱️  ETA: 304.1 min remaining (76 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs32_SGD_lr0.001_pinTrue_ep5.pth

[53/128] (41.4%) >>> Running: MNIST | ResNet18 | BS=32 | SGD | LR=0.0001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.4489, Train Acc: 87.22%, Val Loss: 0.1375, Val Acc: 96.10%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.1355, Train Acc: 96.01%, Val Loss: 0.0897, Val Acc: 97.51%
    ✅ Done! Val Acc: 0.975143 | Test Acc: 0.970357 | Time: 60.01s

    📊 Training Summary for: MNIST | ResNet18 | BS=32 | SGD | LR=0.0001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.448900     0.872163     0.137469     0.961000
    2        0.135534     0.960102     0.089690     0.975143
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.970357
    ├── F1 Score:  0.970341
    ├── Precision: 0.970416
    └── Recall:    0.970357

    ⏱️  ETA: 296.1 min remaining (75 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs32_SGD_lr0.0001_pinTrue_ep2.pth

[54/128] (42.2%) >>> Running: MNIST | ResNet50 | BS=32 | SGD | LR=0.0001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 1.1265, Train Acc: 62.07%, Val Loss: 0.3552, Val Acc: 89.07%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.3015, Train Acc: 90.52%, Val Loss: 0.1907, Val Acc: 94.29%
    ✅ Done! Val Acc: 0.942857 | Test Acc: 0.939857 | Time: 105.76s

    📊 Training Summary for: MNIST | ResNet50 | BS=32 | SGD | LR=0.0001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        1.126468     0.620694     0.355177     0.890714
    2        0.301473     0.905184     0.190748     0.942857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.939857
    ├── F1 Score:  0.939961
    ├── Precision: 0.940583
    └── Recall:    0.939857

    ⏱️  ETA: 289.4 min remaining (74 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs32_SGD_lr0.0001_pinTrue_ep2.pth

[55/128] (43.0%) >>> Running: MNIST | ResNet18 | BS=32 | SGD | LR=0.0001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.4800, Train Acc: 86.20%, Val Loss: 0.1553, Val Acc: 95.70%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.1439, Train Acc: 95.71%, Val Loss: 0.1039, Val Acc: 96.87%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0965, Train Acc: 97.23%, Val Loss: 0.0811, Val Acc: 97.49%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0707, Train Acc: 97.91%, Val Loss: 0.0716, Val Acc: 97.69%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0542, Train Acc: 98.40%, Val Loss: 0.0657, Val Acc: 97.89%
    ✅ Done! Val Acc: 0.978857 | Test Acc: 0.979143 | Time: 150.19s

    📊 Training Summary for: MNIST | ResNet18 | BS=32 | SGD | LR=0.0001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.480029     0.861980     0.155315     0.957000
    2        0.143850     0.957122     0.103927     0.968714
    3        0.096507     0.972347     0.081103     0.974857
    4        0.070710     0.979122     0.071633     0.976857
    5        0.054206     0.984041     0.065659     0.978857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.979143
    ├── F1 Score:  0.979132
    ├── Precision: 0.979140
    └── Recall:    0.979143

    ⏱️  ETA: 283.8 min remaining (73 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs32_SGD_lr0.0001_pinTrue_ep5.pth

[56/128] (43.8%) >>> Running: MNIST | ResNet50 | BS=32 | SGD | LR=0.0001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 1.1257, Train Acc: 62.54%, Val Loss: 0.3554, Val Acc: 88.30%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.3008, Train Acc: 90.64%, Val Loss: 0.1849, Val Acc: 94.04%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.1920, Train Acc: 94.05%, Val Loss: 0.1424, Val Acc: 95.57%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.1457, Train Acc: 95.39%, Val Loss: 0.1077, Val Acc: 96.54%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.1126, Train Acc: 96.42%, Val Loss: 0.0966, Val Acc: 97.00%
    ✅ Done! Val Acc: 0.970000 | Test Acc: 0.968714 | Time: 264.69s

    📊 Training Summary for: MNIST | ResNet50 | BS=32 | SGD | LR=0.0001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        1.125651     0.625429     0.355407     0.883000
    2        0.300820     0.906367     0.184937     0.940429
    3        0.192010     0.940469     0.142395     0.955714
    4        0.145661     0.953898     0.107715     0.965429
    5        0.112641     0.964184     0.096553     0.970000
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.968714
    ├── F1 Score:  0.968665
    ├── Precision: 0.968713
    └── Recall:    0.968714

    ⏱️  ETA: 280.9 min remaining (72 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs32_SGD_lr0.0001_pinTrue_ep5.pth

[57/128] (44.5%) >>> Running: MNIST | ResNet18 | BS=32 | Adam | LR=0.001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.1676, Train Acc: 95.13%, Val Loss: 0.1796, Val Acc: 94.44%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.0724, Train Acc: 97.86%, Val Loss: 0.1134, Val Acc: 96.44%
    ✅ Done! Val Acc: 0.964429 | Test Acc: 0.963571 | Time: 66.75s

    📊 Training Summary for: MNIST | ResNet18 | BS=32 | Adam | LR=0.001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.167621     0.951327     0.179585     0.944429
    2        0.072362     0.978571     0.113373     0.964429
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.963571
    ├── F1 Score:  0.963037
    ├── Precision: 0.967317
    └── Recall:    0.963571

    ⏱️  ETA: 273.7 min remaining (71 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs32_Adam_lr0.001_pinTrue_ep2.pth

[58/128] (45.3%) >>> Running: MNIST | ResNet50 | BS=32 | Adam | LR=0.001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.3566, Train Acc: 90.21%, Val Loss: 0.0865, Val Acc: 97.80%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.1535, Train Acc: 96.16%, Val Loss: 0.1404, Val Acc: 96.20%
    ✅ Done! Val Acc: 0.962000 | Test Acc: 0.964571 | Time: 120.52s

    📊 Training Summary for: MNIST | ResNet50 | BS=32 | Adam | LR=0.001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.356580     0.902102     0.086500     0.978000
    2        0.153502     0.961612     0.140424     0.962000
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.964571
    ├── F1 Score:  0.964603
    ├── Precision: 0.965661
    └── Recall:    0.964571

    ⏱️  ETA: 267.8 min remaining (70 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs32_Adam_lr0.001_pinTrue_ep2.pth

[59/128] (46.1%) >>> Running: MNIST | ResNet18 | BS=32 | Adam | LR=0.001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.1639, Train Acc: 95.05%, Val Loss: 0.0790, Val Acc: 97.90%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.0771, Train Acc: 97.77%, Val Loss: 0.0677, Val Acc: 97.99%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0595, Train Acc: 98.28%, Val Loss: 0.0584, Val Acc: 98.43%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0507, Train Acc: 98.51%, Val Loss: 0.0546, Val Acc: 98.49%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0399, Train Acc: 98.84%, Val Loss: 0.0872, Val Acc: 98.07%
    ✅ Done! Val Acc: 0.980714 | Test Acc: 0.978357 | Time: 166.51s

    📊 Training Summary for: MNIST | ResNet18 | BS=32 | Adam | LR=0.001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.163943     0.950531     0.078994     0.979000
    2        0.077118     0.977714     0.067679     0.979857
    3        0.059468     0.982796     0.058431     0.984286
    4        0.050658     0.985143     0.054577     0.984857
    5        0.039917     0.988388     0.087215     0.980714
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.978357
    ├── F1 Score:  0.978409
    ├── Precision: 0.979208
    └── Recall:    0.978357

    ⏱️  ETA: 263.0 min remaining (69 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs32_Adam_lr0.001_pinTrue_ep5.pth

[60/128] (46.9%) >>> Running: MNIST | ResNet50 | BS=32 | Adam | LR=0.001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.3593, Train Acc: 90.38%, Val Loss: 0.0820, Val Acc: 97.61%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.1736, Train Acc: 95.73%, Val Loss: 0.0773, Val Acc: 97.94%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.1023, Train Acc: 97.40%, Val Loss: 0.0652, Val Acc: 98.19%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.1501, Train Acc: 96.66%, Val Loss: 0.0680, Val Acc: 98.31%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0756, Train Acc: 97.92%, Val Loss: 0.0922, Val Acc: 97.61%
    ✅ Done! Val Acc: 0.976143 | Test Acc: 0.977714 | Time: 302.22s

    📊 Training Summary for: MNIST | ResNet50 | BS=32 | Adam | LR=0.001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.359287     0.903755     0.081979     0.976143
    2        0.173624     0.957327     0.077348     0.979429
    3        0.102336     0.974020     0.065212     0.981857
    4        0.150098     0.966633     0.067965     0.983143
    5        0.075616     0.979184     0.092230     0.976143
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.977714
    ├── F1 Score:  0.977702
    ├── Precision: 0.977954
    └── Recall:    0.977714

    ⏱️  ETA: 260.8 min remaining (68 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs32_Adam_lr0.001_pinTrue_ep5.pth

[61/128] (47.7%) >>> Running: MNIST | ResNet18 | BS=32 | Adam | LR=0.0001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.1824, Train Acc: 94.42%, Val Loss: 0.0731, Val Acc: 97.89%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.0676, Train Acc: 97.86%, Val Loss: 0.0614, Val Acc: 98.06%
    ✅ Done! Val Acc: 0.980571 | Test Acc: 0.980286 | Time: 66.28s

    📊 Training Summary for: MNIST | ResNet18 | BS=32 | Adam | LR=0.0001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.182364     0.944245     0.073060     0.978857
    2        0.067595     0.978612     0.061411     0.980571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.980286
    ├── F1 Score:  0.980289
    ├── Precision: 0.980486
    └── Recall:    0.980286

    ⏱️  ETA: 254.1 min remaining (67 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs32_Adam_lr0.0001_pinTrue_ep2.pth

[62/128] (48.4%) >>> Running: MNIST | ResNet50 | BS=32 | Adam | LR=0.0001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.7287, Train Acc: 75.57%, Val Loss: 0.2770, Val Acc: 90.86%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.2163, Train Acc: 93.00%, Val Loss: 0.1514, Val Acc: 95.14%
    ✅ Done! Val Acc: 0.951429 | Test Acc: 0.950714 | Time: 120.87s

    📊 Training Summary for: MNIST | ResNet50 | BS=32 | Adam | LR=0.0001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.728670     0.755673     0.277038     0.908571
    2        0.216338     0.930041     0.151411     0.951429
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.950714
    ├── F1 Score:  0.950744
    ├── Precision: 0.951371
    └── Recall:    0.950714

    ⏱️  ETA: 248.6 min remaining (66 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs32_Adam_lr0.0001_pinTrue_ep2.pth

[63/128] (49.2%) >>> Running: MNIST | ResNet18 | BS=32 | Adam | LR=0.0001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.1836, Train Acc: 94.43%, Val Loss: 0.0768, Val Acc: 97.60%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.0656, Train Acc: 97.87%, Val Loss: 0.0637, Val Acc: 97.94%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.0442, Train Acc: 98.53%, Val Loss: 0.0631, Val Acc: 98.07%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0326, Train Acc: 98.93%, Val Loss: 0.0495, Val Acc: 98.53%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0271, Train Acc: 99.15%, Val Loss: 0.0365, Val Acc: 98.87%
    ✅ Done! Val Acc: 0.988714 | Test Acc: 0.985286 | Time: 166.54s

    📊 Training Summary for: MNIST | ResNet18 | BS=32 | Adam | LR=0.0001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.183621     0.944286     0.076843     0.976000
    2        0.065580     0.978714     0.063738     0.979429
    3        0.044166     0.985347     0.063130     0.980714
    4        0.032579     0.989347     0.049504     0.985286
    5        0.027079     0.991531     0.036526     0.988714
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.985286
    ├── F1 Score:  0.985283
    ├── Precision: 0.985303
    └── Recall:    0.985286

    ⏱️  ETA: 244.0 min remaining (65 experiments left)
    💾 Saved model to models/MNIST_ResNet18_bs32_Adam_lr0.0001_pinTrue_ep5.pth

[64/128] (50.0%) >>> Running: MNIST | ResNet50 | BS=32 | Adam | LR=0.0001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.7577, Train Acc: 74.79%, Val Loss: 0.2845, Val Acc: 90.77%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.2229, Train Acc: 92.76%, Val Loss: 0.1464, Val Acc: 95.37%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.1235, Train Acc: 95.96%, Val Loss: 0.1107, Val Acc: 96.67%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.0869, Train Acc: 97.17%, Val Loss: 0.0976, Val Acc: 96.91%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.0686, Train Acc: 97.82%, Val Loss: 0.0950, Val Acc: 97.23%
    ✅ Done! Val Acc: 0.972286 | Test Acc: 0.970214 | Time: 302.25s

    📊 Training Summary for: MNIST | ResNet50 | BS=32 | Adam | LR=0.0001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.757701     0.747898     0.284461     0.907714
    2        0.222863     0.927633     0.146388     0.953714
    3        0.123478     0.959592     0.110713     0.966714
    4        0.086905     0.971735     0.097629     0.969143
    5        0.068648     0.978224     0.094967     0.972286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.970214
    ├── F1 Score:  0.970160
    ├── Precision: 0.970628
    └── Recall:    0.970214

    ⏱️  ETA: 241.7 min remaining (64 experiments left)
    💾 Saved model to models/MNIST_ResNet50_bs32_Adam_lr0.0001_pinTrue_ep5.pth

100%|██████████| 26.4M/26.4M [00:01<00:00, 17.0MB/s]
100%|██████████| 29.5k/29.5k [00:00<00:00, 271kB/s]
100%|██████████| 4.42M/4.42M [00:00<00:00, 5.05MB/s]
100%|██████████| 5.15k/5.15k [00:00<00:00, 13.7MB/s]

[65/128] (50.8%) >>> Running: FashionMNIST | ResNet18 | BS=16 | SGD | LR=0.001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.5116, Train Acc: 81.67%, Val Loss: 0.3321, Val Acc: 87.44%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.3320, Train Acc: 87.81%, Val Loss: 0.2745, Val Acc: 89.40%
    ✅ Done! Val Acc: 0.894000 | Test Acc: 0.894000 | Time: 98.19s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=16 | SGD | LR=0.001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.511577     0.816735     0.332090     0.874429
    2        0.331954     0.878082     0.274523     0.894000
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.894000
    ├── F1 Score:  0.894051
    ├── Precision: 0.894558
    └── Recall:    0.894000

    ⏱️  ETA: 236.1 min remaining (63 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs16_SGD_lr0.001_pinFalse_ep2.pth

[66/128] (51.6%) >>> Running: FashionMNIST | ResNet50 | BS=16 | SGD | LR=0.001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.9125, Train Acc: 71.16%, Val Loss: 0.4902, Val Acc: 82.91%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.4875, Train Acc: 82.48%, Val Loss: 0.4523, Val Acc: 83.83%
    ✅ Done! Val Acc: 0.838286 | Test Acc: 0.836714 | Time: 190.70s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=16 | SGD | LR=0.001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.912466     0.711612     0.490196     0.829143
    2        0.487531     0.824796     0.452316     0.838286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.836714
    ├── F1 Score:  0.820441
    ├── Precision: 0.854032
    └── Recall:    0.836714

    ⏱️  ETA: 232.1 min remaining (62 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs16_SGD_lr0.001_pinFalse_ep2.pth

[67/128] (52.3%) >>> Running: FashionMNIST | ResNet18 | BS=16 | SGD | LR=0.001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.5142, Train Acc: 81.51%, Val Loss: 0.3590, Val Acc: 86.57%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.3391, Train Acc: 87.68%, Val Loss: 0.3158, Val Acc: 87.87%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.2838, Train Acc: 89.39%, Val Loss: 0.2770, Val Acc: 89.70%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.2494, Train Acc: 90.74%, Val Loss: 0.2769, Val Acc: 89.63%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.2230, Train Acc: 91.71%, Val Loss: 0.2711, Val Acc: 89.94%
    ✅ Done! Val Acc: 0.899429 | Test Acc: 0.896500 | Time: 245.49s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=16 | SGD | LR=0.001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.514190     0.815082     0.358962     0.865714
    2        0.339124     0.876796     0.315798     0.878714
    3        0.283804     0.893857     0.276956     0.897000
    4        0.249355     0.907388     0.276911     0.896286
    5        0.223048     0.917082     0.271055     0.899429
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.896500
    ├── F1 Score:  0.896473
    ├── Precision: 0.898374
    └── Recall:    0.896500

    ⏱️  ETA: 228.9 min remaining (61 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs16_SGD_lr0.001_pinFalse_ep5.pth

[68/128] (53.1%) >>> Running: FashionMNIST | ResNet50 | BS=16 | SGD | LR=0.001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.9223, Train Acc: 70.83%, Val Loss: 0.8840, Val Acc: 74.50%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.4840, Train Acc: 82.62%, Val Loss: 0.3889, Val Acc: 85.51%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.3968, Train Acc: 85.60%, Val Loss: 0.3436, Val Acc: 86.94%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.3452, Train Acc: 87.07%, Val Loss: 0.3261, Val Acc: 87.74%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.3175, Train Acc: 88.08%, Val Loss: 0.3121, Val Acc: 88.79%
    ✅ Done! Val Acc: 0.887857 | Test Acc: 0.887000 | Time: 476.39s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=16 | SGD | LR=0.001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.922301     0.708327     0.884041     0.745000
    2        0.484047     0.826163     0.388873     0.855143
    3        0.396754     0.855959     0.343587     0.869429
    4        0.345236     0.870694     0.326105     0.877429
    5        0.317546     0.880796     0.312121     0.887857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.887000
    ├── F1 Score:  0.886764
    ├── Precision: 0.886921
    └── Recall:    0.887000

    ⏱️  ETA: 229.0 min remaining (60 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs16_SGD_lr0.001_pinFalse_ep5.pth

[69/128] (53.9%) >>> Running: FashionMNIST | ResNet18 | BS=16 | SGD | LR=0.0001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.6369, Train Acc: 78.01%, Val Loss: 0.4037, Val Acc: 85.23%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.4138, Train Acc: 85.24%, Val Loss: 0.3612, Val Acc: 87.23%
    ✅ Done! Val Acc: 0.872286 | Test Acc: 0.871500 | Time: 98.32s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=16 | SGD | LR=0.0001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.636919     0.780143     0.403700     0.852286
    2        0.413834     0.852388     0.361154     0.872286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.871500
    ├── F1 Score:  0.871071
    ├── Precision: 0.870881
    └── Recall:    0.871500

    ⏱️  ETA: 223.5 min remaining (59 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs16_SGD_lr0.0001_pinFalse_ep2.pth

[70/128] (54.7%) >>> Running: FashionMNIST | ResNet50 | BS=16 | SGD | LR=0.0001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 1.0459, Train Acc: 62.09%, Val Loss: 0.6256, Val Acc: 77.51%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.6598, Train Acc: 76.04%, Val Loss: 0.5176, Val Acc: 81.41%
    ✅ Done! Val Acc: 0.814143 | Test Acc: 0.812929 | Time: 190.86s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=16 | SGD | LR=0.0001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        1.045909     0.620857     0.625597     0.775143
    2        0.659797     0.760408     0.517553     0.814143
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.812929
    ├── F1 Score:  0.807287
    ├── Precision: 0.809795
    └── Recall:    0.812929

    ⏱️  ETA: 219.5 min remaining (58 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs16_SGD_lr0.0001_pinFalse_ep2.pth

[71/128] (55.5%) >>> Running: FashionMNIST | ResNet18 | BS=16 | SGD | LR=0.0001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.6329, Train Acc: 78.11%, Val Loss: 0.4070, Val Acc: 85.39%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.4208, Train Acc: 84.92%, Val Loss: 0.3556, Val Acc: 87.23%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.3544, Train Acc: 87.24%, Val Loss: 0.3336, Val Acc: 87.91%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.3090, Train Acc: 88.80%, Val Loss: 0.3155, Val Acc: 88.41%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.2765, Train Acc: 90.05%, Val Loss: 0.3177, Val Acc: 88.97%
    ✅ Done! Val Acc: 0.889714 | Test Acc: 0.884143 | Time: 245.79s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=16 | SGD | LR=0.0001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.632941     0.781082     0.407011     0.853857
    2        0.420830     0.849184     0.355630     0.872286
    3        0.354428     0.872408     0.333564     0.879143
    4        0.308993     0.887959     0.315469     0.884143
    5        0.276542     0.900510     0.317709     0.889714
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.884143
    ├── F1 Score:  0.883466
    ├── Precision: 0.883937
    └── Recall:    0.884143

    ⏱️  ETA: 216.1 min remaining (57 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs16_SGD_lr0.0001_pinFalse_ep5.pth

[72/128] (56.2%) >>> Running: FashionMNIST | ResNet50 | BS=16 | SGD | LR=0.0001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 1.0430, Train Acc: 62.30%, Val Loss: 0.6202, Val Acc: 77.44%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.6526, Train Acc: 76.04%, Val Loss: 0.5183, Val Acc: 81.01%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.5694, Train Acc: 79.09%, Val Loss: 0.4545, Val Acc: 83.10%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.5133, Train Acc: 81.33%, Val Loss: 0.4422, Val Acc: 83.93%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.4704, Train Acc: 82.78%, Val Loss: 0.3958, Val Acc: 85.33%
    ✅ Done! Val Acc: 0.853286 | Test Acc: 0.856000 | Time: 478.10s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=16 | SGD | LR=0.0001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        1.042997     0.623000     0.620156     0.774429
    2        0.652629     0.760388     0.518324     0.810143
    3        0.569352     0.790939     0.454465     0.831000
    4        0.513264     0.813265     0.442181     0.839286
    5        0.470368     0.827837     0.395796     0.853286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.856000
    ├── F1 Score:  0.854903
    ├── Precision: 0.854140
    └── Recall:    0.856000

    ⏱️  ETA: 215.8 min remaining (56 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs16_SGD_lr0.0001_pinFalse_ep5.pth

[73/128] (57.0%) >>> Running: FashionMNIST | ResNet18 | BS=16 | Adam | LR=0.001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.5159, Train Acc: 81.76%, Val Loss: 0.3714, Val Acc: 86.70%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.3658, Train Acc: 86.91%, Val Loss: 0.3023, Val Acc: 89.13%
    ✅ Done! Val Acc: 0.891286 | Test Acc: 0.883643 | Time: 111.02s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=16 | Adam | LR=0.001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.515933     0.817592     0.371353     0.867000
    2        0.365770     0.869102     0.302260     0.891286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.883643
    ├── F1 Score:  0.884508
    ├── Precision: 0.887121
    └── Recall:    0.883643

    ⏱️  ETA: 210.5 min remaining (55 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs16_Adam_lr0.001_pinFalse_ep2.pth

[74/128] (57.8%) >>> Running: FashionMNIST | ResNet50 | BS=16 | Adam | LR=0.001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.8584, Train Acc: 73.97%, Val Loss: 0.4929, Val Acc: 82.76%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.5809, Train Acc: 81.03%, Val Loss: 0.3837, Val Acc: 85.54%
    ✅ Done! Val Acc: 0.855429 | Test Acc: 0.859071 | Time: 219.82s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=16 | Adam | LR=0.001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.858370     0.739735     0.492928     0.827571
    2        0.580915     0.810265     0.383724     0.855429
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.859071
    ├── F1 Score:  0.861324
    ├── Precision: 0.868184
    └── Recall:    0.859071

    ⏱️  ETA: 206.8 min remaining (54 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs16_Adam_lr0.001_pinFalse_ep2.pth

[75/128] (58.6%) >>> Running: FashionMNIST | ResNet18 | BS=16 | Adam | LR=0.001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.5112, Train Acc: 82.04%, Val Loss: 0.3775, Val Acc: 86.21%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.3663, Train Acc: 87.04%, Val Loss: 0.3648, Val Acc: 86.54%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.3129, Train Acc: 88.71%, Val Loss: 0.2944, Val Acc: 88.97%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.2759, Train Acc: 89.96%, Val Loss: 0.2719, Val Acc: 90.44%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.2466, Train Acc: 91.07%, Val Loss: 0.2503, Val Acc: 90.31%
    ✅ Done! Val Acc: 0.903143 | Test Acc: 0.905714 | Time: 277.51s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=16 | Adam | LR=0.001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.511248     0.820449     0.377481     0.862143
    2        0.366293     0.870408     0.364763     0.865429
    3        0.312913     0.887102     0.294380     0.889714
    4        0.275940     0.899551     0.271868     0.904429
    5        0.246588     0.910673     0.250293     0.903143
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.905714
    ├── F1 Score:  0.905674
    ├── Precision: 0.907526
    └── Recall:    0.905714

    ⏱️  ETA: 203.7 min remaining (53 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs16_Adam_lr0.001_pinFalse_ep5.pth

[76/128] (59.4%) >>> Running: FashionMNIST | ResNet50 | BS=16 | Adam | LR=0.001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.8961, Train Acc: 72.61%, Val Loss: 0.4706, Val Acc: 82.66%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.5781, Train Acc: 80.96%, Val Loss: 0.4368, Val Acc: 84.41%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.4934, Train Acc: 83.44%, Val Loss: 0.3404, Val Acc: 87.44%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.3930, Train Acc: 86.22%, Val Loss: 0.3193, Val Acc: 87.56%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.3540, Train Acc: 87.70%, Val Loss: 0.3616, Val Acc: 86.50%
    ✅ Done! Val Acc: 0.865000 | Test Acc: 0.863786 | Time: 547.89s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=16 | Adam | LR=0.001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.896111     0.726122     0.470599     0.826571
    2        0.578091     0.809571     0.436830     0.844143
    3        0.493433     0.834449     0.340398     0.874429
    4        0.393041     0.862245     0.319277     0.875571
    5        0.353980     0.877000     0.361585     0.865000
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.863786
    ├── F1 Score:  0.863902
    ├── Precision: 0.865983
    └── Recall:    0.863786

    ⏱️  ETA: 203.6 min remaining (52 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs16_Adam_lr0.001_pinFalse_ep5.pth

[77/128] (60.2%) >>> Running: FashionMNIST | ResNet18 | BS=16 | Adam | LR=0.0001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.4990, Train Acc: 82.17%, Val Loss: 0.3322, Val Acc: 87.36%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.3436, Train Acc: 87.47%, Val Loss: 0.3182, Val Acc: 88.11%
    ✅ Done! Val Acc: 0.881143 | Test Acc: 0.882071 | Time: 111.23s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=16 | Adam | LR=0.0001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.498963     0.821714     0.332185     0.873571
    2        0.343627     0.874653     0.318205     0.881143
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.882071
    ├── F1 Score:  0.883011
    ├── Precision: 0.886422
    └── Recall:    0.882071

    ⏱️  ETA: 198.5 min remaining (51 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs16_Adam_lr0.0001_pinFalse_ep2.pth

[78/128] (60.9%) >>> Running: FashionMNIST | ResNet50 | BS=16 | Adam | LR=0.0001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.9397, Train Acc: 66.16%, Val Loss: 0.5369, Val Acc: 80.74%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.5442, Train Acc: 80.44%, Val Loss: 0.4540, Val Acc: 84.11%
    ✅ Done! Val Acc: 0.841143 | Test Acc: 0.835571 | Time: 219.63s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=16 | Adam | LR=0.0001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.939724     0.661633     0.536938     0.807429
    2        0.544173     0.804449     0.453985     0.841143
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.835571
    ├── F1 Score:  0.834082
    ├── Precision: 0.838974
    └── Recall:    0.835571

    ⏱️  ETA: 194.6 min remaining (50 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs16_Adam_lr0.0001_pinFalse_ep2.pth

[79/128] (61.7%) >>> Running: FashionMNIST | ResNet18 | BS=16 | Adam | LR=0.0001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.5043, Train Acc: 81.94%, Val Loss: 0.3510, Val Acc: 86.69%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.3420, Train Acc: 87.51%, Val Loss: 0.2986, Val Acc: 88.96%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.2852, Train Acc: 89.48%, Val Loss: 0.2916, Val Acc: 89.26%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.2436, Train Acc: 90.93%, Val Loss: 0.2579, Val Acc: 90.30%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.2089, Train Acc: 92.17%, Val Loss: 0.2880, Val Acc: 89.53%
    ✅ Done! Val Acc: 0.895286 | Test Acc: 0.890429 | Time: 277.46s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=16 | Adam | LR=0.0001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.504273     0.819367     0.351040     0.866857
    2        0.342035     0.875082     0.298617     0.889571
    3        0.285231     0.894816     0.291613     0.892571
    4        0.243617     0.909286     0.257901     0.903000
    5        0.208946     0.921714     0.287955     0.895286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.890429
    ├── F1 Score:  0.890280
    ├── Precision: 0.891741
    └── Recall:    0.890429

    ⏱️  ETA: 191.3 min remaining (49 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs16_Adam_lr0.0001_pinFalse_ep5.pth

[80/128] (62.5%) >>> Running: FashionMNIST | ResNet50 | BS=16 | Adam | LR=0.0001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.9042, Train Acc: 67.45%, Val Loss: 0.5613, Val Acc: 79.81%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.5256, Train Acc: 81.14%, Val Loss: 0.4347, Val Acc: 83.96%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.4160, Train Acc: 85.08%, Val Loss: 0.3483, Val Acc: 86.71%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.3599, Train Acc: 86.93%, Val Loss: 0.3351, Val Acc: 87.81%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.3111, Train Acc: 88.76%, Val Loss: 0.3280, Val Acc: 88.13%
    ✅ Done! Val Acc: 0.881286 | Test Acc: 0.877214 | Time: 546.45s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=16 | Adam | LR=0.0001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.904244     0.674531     0.561268     0.798143
    2        0.525604     0.811429     0.434684     0.839571
    3        0.415985     0.850796     0.348337     0.867143
    4        0.359902     0.869327     0.335106     0.878143
    5        0.311077     0.887612     0.327984     0.881286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.877214
    ├── F1 Score:  0.876625
    ├── Precision: 0.878773
    └── Recall:    0.877214

    ⏱️  ETA: 190.7 min remaining (48 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs16_Adam_lr0.0001_pinFalse_ep5.pth

[81/128] (63.3%) >>> Running: FashionMNIST | ResNet18 | BS=16 | SGD | LR=0.001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.5097, Train Acc: 81.82%, Val Loss: 0.3362, Val Acc: 87.77%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.3397, Train Acc: 87.54%, Val Loss: 0.3022, Val Acc: 88.63%
    ✅ Done! Val Acc: 0.886286 | Test Acc: 0.888571 | Time: 98.26s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=16 | SGD | LR=0.001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.509668     0.818184     0.336155     0.877714
    2        0.339682     0.875408     0.302226     0.886286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.888571
    ├── F1 Score:  0.887369
    ├── Precision: 0.888674
    └── Recall:    0.888571

    ⏱️  ETA: 185.5 min remaining (47 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs16_SGD_lr0.001_pinTrue_ep2.pth

[82/128] (64.1%) >>> Running: FashionMNIST | ResNet50 | BS=16 | SGD | LR=0.001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.8369, Train Acc: 73.27%, Val Loss: 0.4233, Val Acc: 83.89%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.4576, Train Acc: 83.76%, Val Loss: 0.3759, Val Acc: 86.49%
    ✅ Done! Val Acc: 0.864857 | Test Acc: 0.862357 | Time: 190.63s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=16 | SGD | LR=0.001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.836907     0.732735     0.423334     0.838857
    2        0.457647     0.837551     0.375932     0.864857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.862357
    ├── F1 Score:  0.858336
    ├── Precision: 0.860758
    └── Recall:    0.862357

    ⏱️  ETA: 181.3 min remaining (46 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs16_SGD_lr0.001_pinTrue_ep2.pth

[83/128] (64.8%) >>> Running: FashionMNIST | ResNet18 | BS=16 | SGD | LR=0.001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.5080, Train Acc: 81.85%, Val Loss: 0.3460, Val Acc: 87.03%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.3384, Train Acc: 87.78%, Val Loss: 0.3078, Val Acc: 88.44%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.2791, Train Acc: 89.70%, Val Loss: 0.2913, Val Acc: 89.06%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.2474, Train Acc: 90.91%, Val Loss: 0.2898, Val Acc: 89.53%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.2241, Train Acc: 91.59%, Val Loss: 0.2708, Val Acc: 90.30%
    ✅ Done! Val Acc: 0.903000 | Test Acc: 0.900643 | Time: 245.21s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=16 | SGD | LR=0.001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.507960     0.818490     0.346016     0.870286
    2        0.338432     0.877776     0.307801     0.884429
    3        0.279113     0.896959     0.291345     0.890571
    4        0.247394     0.909061     0.289834     0.895286
    5        0.224102     0.915939     0.270809     0.903000
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.900643
    ├── F1 Score:  0.900476
    ├── Precision: 0.901485
    └── Recall:    0.900643

    ⏱️  ETA: 177.5 min remaining (45 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs16_SGD_lr0.001_pinTrue_ep5.pth

[84/128] (65.6%) >>> Running: FashionMNIST | ResNet50 | BS=16 | SGD | LR=0.001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.8801, Train Acc: 72.24%, Val Loss: 0.4268, Val Acc: 84.36%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.4652, Train Acc: 83.41%, Val Loss: 0.3602, Val Acc: 86.76%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.3777, Train Acc: 86.35%, Val Loss: 0.3113, Val Acc: 88.59%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.3309, Train Acc: 87.83%, Val Loss: 0.2978, Val Acc: 88.97%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.2965, Train Acc: 88.94%, Val Loss: 0.2855, Val Acc: 89.41%
    ✅ Done! Val Acc: 0.894143 | Test Acc: 0.890214 | Time: 477.36s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=16 | SGD | LR=0.001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.880113     0.722367     0.426771     0.843571
    2        0.465225     0.834102     0.360202     0.867571
    3        0.377720     0.863490     0.311318     0.885857
    4        0.330876     0.878306     0.297789     0.889714
    5        0.296507     0.889388     0.285500     0.894143
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.890214
    ├── F1 Score:  0.890181
    ├── Precision: 0.890573
    └── Recall:    0.890214

    ⏱️  ETA: 175.8 min remaining (44 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs16_SGD_lr0.001_pinTrue_ep5.pth

[85/128] (66.4%) >>> Running: FashionMNIST | ResNet18 | BS=16 | SGD | LR=0.0001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.6351, Train Acc: 78.10%, Val Loss: 0.4096, Val Acc: 85.10%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.4167, Train Acc: 85.18%, Val Loss: 0.3618, Val Acc: 86.83%
    ✅ Done! Val Acc: 0.868286 | Test Acc: 0.867571 | Time: 98.36s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=16 | SGD | LR=0.0001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.635074     0.781041     0.409633     0.851000
    2        0.416708     0.851776     0.361759     0.868286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.867571
    ├── F1 Score:  0.867620
    ├── Precision: 0.868277
    └── Recall:    0.867571

    ⏱️  ETA: 170.7 min remaining (43 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs16_SGD_lr0.0001_pinTrue_ep2.pth

[86/128] (67.2%) >>> Running: FashionMNIST | ResNet50 | BS=16 | SGD | LR=0.0001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 1.0533, Train Acc: 61.63%, Val Loss: 0.6093, Val Acc: 77.39%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.6758, Train Acc: 75.36%, Val Loss: 0.5044, Val Acc: 81.23%
    ✅ Done! Val Acc: 0.812286 | Test Acc: 0.807500 | Time: 190.93s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=16 | SGD | LR=0.0001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        1.053314     0.616265     0.609299     0.773857
    2        0.675752     0.753612     0.504398     0.812286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.807500
    ├── F1 Score:  0.803080
    ├── Precision: 0.804164
    └── Recall:    0.807500

    ⏱️  ETA: 166.5 min remaining (42 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs16_SGD_lr0.0001_pinTrue_ep2.pth

[87/128] (68.0%) >>> Running: FashionMNIST | ResNet18 | BS=16 | SGD | LR=0.0001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.6367, Train Acc: 77.80%, Val Loss: 0.3967, Val Acc: 85.61%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.4150, Train Acc: 85.17%, Val Loss: 0.3438, Val Acc: 87.27%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.3497, Train Acc: 87.44%, Val Loss: 0.3266, Val Acc: 87.80%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.3074, Train Acc: 88.84%, Val Loss: 0.3140, Val Acc: 88.84%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.2767, Train Acc: 89.93%, Val Loss: 0.2986, Val Acc: 89.21%
    ✅ Done! Val Acc: 0.892143 | Test Acc: 0.886571 | Time: 245.12s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=16 | SGD | LR=0.0001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.636694     0.778041     0.396667     0.856143
    2        0.415033     0.851653     0.343755     0.872714
    3        0.349699     0.874367     0.326644     0.878000
    4        0.307364     0.888429     0.314020     0.888429
    5        0.276688     0.899327     0.298628     0.892143
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.886571
    ├── F1 Score:  0.886557
    ├── Precision: 0.886802
    └── Recall:    0.886571

    ⏱️  ETA: 162.7 min remaining (41 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs16_SGD_lr0.0001_pinTrue_ep5.pth

[88/128] (68.8%) >>> Running: FashionMNIST | ResNet50 | BS=16 | SGD | LR=0.0001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 1.0261, Train Acc: 62.73%, Val Loss: 0.6131, Val Acc: 77.01%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.6555, Train Acc: 76.14%, Val Loss: 0.5024, Val Acc: 81.84%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.5648, Train Acc: 79.43%, Val Loss: 0.4585, Val Acc: 82.60%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.5026, Train Acc: 81.59%, Val Loss: 0.4215, Val Acc: 84.36%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.4616, Train Acc: 83.25%, Val Loss: 0.3975, Val Acc: 84.97%
    ✅ Done! Val Acc: 0.849714 | Test Acc: 0.851143 | Time: 478.08s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=16 | SGD | LR=0.0001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        1.026107     0.627327     0.613091     0.770143
    2        0.655510     0.761429     0.502420     0.818429
    3        0.564822     0.794286     0.458466     0.826000
    4        0.502635     0.815918     0.421505     0.843571
    5        0.461560     0.832510     0.397454     0.849714
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.851143
    ├── F1 Score:  0.849861
    ├── Precision: 0.851429
    └── Recall:    0.851143

    ⏱️  ETA: 160.7 min remaining (40 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs16_SGD_lr0.0001_pinTrue_ep5.pth

[89/128] (69.5%) >>> Running: FashionMNIST | ResNet18 | BS=16 | Adam | LR=0.001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.5112, Train Acc: 81.90%, Val Loss: 0.3517, Val Acc: 86.60%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.3592, Train Acc: 87.28%, Val Loss: 0.3464, Val Acc: 86.26%
    ✅ Done! Val Acc: 0.862571 | Test Acc: 0.869786 | Time: 111.53s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=16 | Adam | LR=0.001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.511181     0.819041     0.351728     0.866000
    2        0.359229     0.872816     0.346441     0.862571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.869786
    ├── F1 Score:  0.871596
    ├── Precision: 0.878517
    └── Recall:    0.869786

    ⏱️  ETA: 155.8 min remaining (39 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs16_Adam_lr0.001_pinTrue_ep2.pth

[90/128] (70.3%) >>> Running: FashionMNIST | ResNet50 | BS=16 | Adam | LR=0.001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.7910, Train Acc: 75.52%, Val Loss: 0.4124, Val Acc: 84.69%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.5752, Train Acc: 81.49%, Val Loss: 0.3961, Val Acc: 85.16%
    ✅ Done! Val Acc: 0.851571 | Test Acc: 0.855000 | Time: 219.92s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=16 | Adam | LR=0.001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.791017     0.755224     0.412368     0.846857
    2        0.575237     0.814898     0.396091     0.851571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.855000
    ├── F1 Score:  0.855832
    ├── Precision: 0.857601
    └── Recall:    0.855000

    ⏱️  ETA: 151.8 min remaining (38 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs16_Adam_lr0.001_pinTrue_ep2.pth

[91/128] (71.1%) >>> Running: FashionMNIST | ResNet18 | BS=16 | Adam | LR=0.001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.5172, Train Acc: 81.81%, Val Loss: 0.4075, Val Acc: 83.56%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.3637, Train Acc: 86.98%, Val Loss: 0.3148, Val Acc: 88.57%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.3171, Train Acc: 88.58%, Val Loss: 0.3064, Val Acc: 89.07%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.2778, Train Acc: 89.86%, Val Loss: 0.2866, Val Acc: 89.46%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.2538, Train Acc: 90.85%, Val Loss: 0.3013, Val Acc: 89.04%
    ✅ Done! Val Acc: 0.890429 | Test Acc: 0.893929 | Time: 278.20s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=16 | Adam | LR=0.001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.517220     0.818122     0.407500     0.835571
    2        0.363702     0.869776     0.314825     0.885714
    3        0.317083     0.885776     0.306443     0.890714
    4        0.277830     0.898633     0.286552     0.894571
    5        0.253763     0.908510     0.301316     0.890429
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.893929
    ├── F1 Score:  0.892964
    ├── Precision: 0.896845
    └── Recall:    0.893929

    ⏱️  ETA: 148.1 min remaining (37 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs16_Adam_lr0.001_pinTrue_ep5.pth

[92/128] (71.9%) >>> Running: FashionMNIST | ResNet50 | BS=16 | Adam | LR=0.001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.8802, Train Acc: 73.55%, Val Loss: 0.6691, Val Acc: 78.87%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.7015, Train Acc: 77.16%, Val Loss: 0.4647, Val Acc: 83.77%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.4887, Train Acc: 83.27%, Val Loss: 0.3595, Val Acc: 87.03%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.4530, Train Acc: 84.68%, Val Loss: 1.0533, Val Acc: 82.61%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.3910, Train Acc: 86.28%, Val Loss: 0.3333, Val Acc: 87.34%
    ✅ Done! Val Acc: 0.873429 | Test Acc: 0.874214 | Time: 552.13s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=16 | Adam | LR=0.001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.880242     0.735469     0.669125     0.788714
    2        0.701473     0.771612     0.464708     0.837714
    3        0.488655     0.832694     0.359498     0.870286
    4        0.453004     0.846816     1.053338     0.826143
    5        0.390968     0.862837     0.333305     0.873429
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.874214
    ├── F1 Score:  0.873544
    ├── Precision: 0.877529
    └── Recall:    0.874214

    ⏱️  ETA: 146.3 min remaining (36 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs16_Adam_lr0.001_pinTrue_ep5.pth

[93/128] (72.7%) >>> Running: FashionMNIST | ResNet18 | BS=16 | Adam | LR=0.0001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.5044, Train Acc: 81.98%, Val Loss: 0.3625, Val Acc: 86.94%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.3444, Train Acc: 87.40%, Val Loss: 0.3527, Val Acc: 86.60%
    ✅ Done! Val Acc: 0.866000 | Test Acc: 0.860714 | Time: 111.26s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=16 | Adam | LR=0.0001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.504445     0.819755     0.362517     0.869429
    2        0.344405     0.873980     0.352743     0.866000
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.860714
    ├── F1 Score:  0.862070
    ├── Precision: 0.870631
    └── Recall:    0.860714

    ⏱️  ETA: 141.4 min remaining (35 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs16_Adam_lr0.0001_pinTrue_ep2.pth

[94/128] (73.4%) >>> Running: FashionMNIST | ResNet50 | BS=16 | Adam | LR=0.0001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.9180, Train Acc: 66.81%, Val Loss: 0.5580, Val Acc: 79.36%

Epoch 2/2 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.5369, Train Acc: 80.63%, Val Loss: 0.4487, Val Acc: 83.69%
    ✅ Done! Val Acc: 0.836857 | Test Acc: 0.838643 | Time: 219.92s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=16 | Adam | LR=0.0001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.917952     0.668122     0.557980     0.793571
    2        0.536898     0.806347     0.448723     0.836857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.838643
    ├── F1 Score:  0.840186
    ├── Precision: 0.845841
    └── Recall:    0.838643

    ⏱️  ETA: 137.4 min remaining (34 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs16_Adam_lr0.0001_pinTrue_ep2.pth

[95/128] (74.2%) >>> Running: FashionMNIST | ResNet18 | BS=16 | Adam | LR=0.0001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.5035, Train Acc: 82.23%, Val Loss: 0.3844, Val Acc: 85.10%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.3418, Train Acc: 87.55%, Val Loss: 0.2965, Val Acc: 88.91%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.2821, Train Acc: 89.69%, Val Loss: 0.3018, Val Acc: 88.59%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.2386, Train Acc: 91.20%, Val Loss: 0.3000, Val Acc: 89.37%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.2026, Train Acc: 92.44%, Val Loss: 0.2887, Val Acc: 89.77%
    ✅ Done! Val Acc: 0.897714 | Test Acc: 0.893500 | Time: 278.84s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=16 | Adam | LR=0.0001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.503525     0.822265     0.384437     0.851000
    2        0.341795     0.875469     0.296546     0.889143
    3        0.282084     0.896878     0.301844     0.885857
    4        0.238597     0.912000     0.299974     0.893714
    5        0.202649     0.924367     0.288735     0.897714
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.893500
    ├── F1 Score:  0.893168
    ├── Precision: 0.893754
    └── Recall:    0.893500

    ⏱️  ETA: 133.6 min remaining (33 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs16_Adam_lr0.0001_pinTrue_ep5.pth

[96/128] (75.0%) >>> Running: FashionMNIST | ResNet50 | BS=16 | Adam | LR=0.0001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.9182, Train Acc: 66.83%, Val Loss: 0.5698, Val Acc: 78.59%

Epoch 2/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.5449, Train Acc: 80.36%, Val Loss: 0.4488, Val Acc: 83.14%

Epoch 3/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.4402, Train Acc: 84.17%, Val Loss: 0.4034, Val Acc: 85.50%

Epoch 4/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.3737, Train Acc: 86.48%, Val Loss: 0.3242, Val Acc: 87.91%

Epoch 5/5 [Train]:   0%|          | 0/3063 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.3199, Train Acc: 88.34%, Val Loss: 0.3321, Val Acc: 88.03%
    ✅ Done! Val Acc: 0.880286 | Test Acc: 0.879143 | Time: 550.82s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=16 | Adam | LR=0.0001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.918213     0.668306     0.569820     0.785857
    2        0.544944     0.803633     0.448833     0.831429
    3        0.440172     0.841694     0.403412     0.855000
    4        0.373699     0.864837     0.324199     0.879143
    5        0.319880     0.883449     0.332099     0.880286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.879143
    ├── F1 Score:  0.879494
    ├── Precision: 0.882717
    └── Recall:    0.879143

    ⏱️  ETA: 131.4 min remaining (32 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs16_Adam_lr0.0001_pinTrue_ep5.pth

[97/128] (75.8%) >>> Running: FashionMNIST | ResNet18 | BS=32 | SGD | LR=0.001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.4867, Train Acc: 82.33%, Val Loss: 0.3406, Val Acc: 87.04%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.3286, Train Acc: 87.84%, Val Loss: 0.2941, Val Acc: 89.04%
    ✅ Done! Val Acc: 0.890429 | Test Acc: 0.888786 | Time: 59.82s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=32 | SGD | LR=0.001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.486676     0.823347     0.340626     0.870429
    2        0.328580     0.878408     0.294139     0.890429
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.888786
    ├── F1 Score:  0.888125
    ├── Precision: 0.888303
    └── Recall:    0.888786

    ⏱️  ETA: 126.3 min remaining (31 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs32_SGD_lr0.001_pinFalse_ep2.pth

[98/128] (76.6%) >>> Running: FashionMNIST | ResNet50 | BS=32 | SGD | LR=0.001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.8198, Train Acc: 71.88%, Val Loss: 0.5005, Val Acc: 81.87%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.4925, Train Acc: 82.48%, Val Loss: 0.4032, Val Acc: 84.97%
    ✅ Done! Val Acc: 0.849714 | Test Acc: 0.851786 | Time: 106.78s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=32 | SGD | LR=0.001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.819769     0.718755     0.500494     0.818714
    2        0.492535     0.824755     0.403207     0.849714
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.851786
    ├── F1 Score:  0.849851
    ├── Precision: 0.853348
    └── Recall:    0.851786

    ⏱️  ETA: 121.6 min remaining (30 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs32_SGD_lr0.001_pinFalse_ep2.pth

[99/128] (77.3%) >>> Running: FashionMNIST | ResNet18 | BS=32 | SGD | LR=0.001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.4855, Train Acc: 82.52%, Val Loss: 0.3423, Val Acc: 87.49%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.3274, Train Acc: 87.93%, Val Loss: 0.3249, Val Acc: 87.71%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.2741, Train Acc: 89.81%, Val Loss: 0.2876, Val Acc: 89.24%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.2369, Train Acc: 91.08%, Val Loss: 0.3098, Val Acc: 88.89%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.2042, Train Acc: 92.37%, Val Loss: 0.2803, Val Acc: 90.21%
    ✅ Done! Val Acc: 0.902143 | Test Acc: 0.899286 | Time: 149.36s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=32 | SGD | LR=0.001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.485455     0.825245     0.342275     0.874857
    2        0.327368     0.879306     0.324942     0.877143
    3        0.274149     0.898102     0.287578     0.892429
    4        0.236947     0.910837     0.309807     0.888857
    5        0.204198     0.923653     0.280277     0.902143
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.899286
    ├── F1 Score:  0.899268
    ├── Precision: 0.900383
    └── Recall:    0.899286

    ⏱️  ETA: 117.1 min remaining (29 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs32_SGD_lr0.001_pinFalse_ep5.pth

[100/128] (78.1%) >>> Running: FashionMNIST | ResNet50 | BS=32 | SGD | LR=0.001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.8040, Train Acc: 72.25%, Val Loss: 0.4874, Val Acc: 82.56%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.4758, Train Acc: 83.01%, Val Loss: 0.3849, Val Acc: 85.77%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.3835, Train Acc: 86.05%, Val Loss: 0.3411, Val Acc: 87.56%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.3316, Train Acc: 87.77%, Val Loss: 0.3250, Val Acc: 87.80%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.2943, Train Acc: 89.09%, Val Loss: 0.2997, Val Acc: 89.03%
    ✅ Done! Val Acc: 0.890286 | Test Acc: 0.892929 | Time: 266.28s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=32 | SGD | LR=0.001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.803963     0.722510     0.487376     0.825571
    2        0.475796     0.830082     0.384939     0.857714
    3        0.383544     0.860510     0.341105     0.875571
    4        0.331640     0.877714     0.324975     0.878000
    5        0.294276     0.890857     0.299657     0.890286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.892929
    ├── F1 Score:  0.892771
    ├── Precision: 0.892938
    └── Recall:    0.892929

    ⏱️  ETA: 113.3 min remaining (28 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs32_SGD_lr0.001_pinFalse_ep5.pth

[101/128] (78.9%) >>> Running: FashionMNIST | ResNet18 | BS=32 | SGD | LR=0.0001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.7077, Train Acc: 75.75%, Val Loss: 0.4425, Val Acc: 84.13%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.4338, Train Acc: 84.55%, Val Loss: 0.3832, Val Acc: 86.24%
    ✅ Done! Val Acc: 0.862429 | Test Acc: 0.858000 | Time: 59.81s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=32 | SGD | LR=0.0001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.707696     0.757490     0.442550     0.841286
    2        0.433826     0.845531     0.383156     0.862429
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.858000
    ├── F1 Score:  0.857158
    ├── Precision: 0.857945
    └── Recall:    0.858000

    ⏱️  ETA: 108.4 min remaining (27 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs32_SGD_lr0.0001_pinFalse_ep2.pth

[102/128] (79.7%) >>> Running: FashionMNIST | ResNet50 | BS=32 | SGD | LR=0.0001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 1.2295, Train Acc: 55.94%, Val Loss: 0.7269, Val Acc: 73.09%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.6781, Train Acc: 74.87%, Val Loss: 0.5696, Val Acc: 78.83%
    ✅ Done! Val Acc: 0.788286 | Test Acc: 0.788714 | Time: 106.74s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=32 | SGD | LR=0.0001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        1.229527     0.559388     0.726903     0.730857
    2        0.678135     0.748735     0.569580     0.788286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.788714
    ├── F1 Score:  0.784027
    ├── Precision: 0.787953
    └── Recall:    0.788714

    ⏱️  ETA: 103.9 min remaining (26 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs32_SGD_lr0.0001_pinFalse_ep2.pth

[103/128] (80.5%) >>> Running: FashionMNIST | ResNet18 | BS=32 | SGD | LR=0.0001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.7074, Train Acc: 75.91%, Val Loss: 0.4558, Val Acc: 83.47%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.4304, Train Acc: 84.62%, Val Loss: 0.3963, Val Acc: 85.43%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.3608, Train Acc: 87.17%, Val Loss: 0.3711, Val Acc: 86.60%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.3181, Train Acc: 88.55%, Val Loss: 0.3554, Val Acc: 87.03%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.2792, Train Acc: 89.96%, Val Loss: 0.3468, Val Acc: 87.36%
    ✅ Done! Val Acc: 0.873571 | Test Acc: 0.874929 | Time: 149.54s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=32 | SGD | LR=0.0001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.707411     0.759102     0.455758     0.834714
    2        0.430425     0.846224     0.396279     0.854286
    3        0.360808     0.871694     0.371082     0.866000
    4        0.318149     0.885490     0.355402     0.870286
    5        0.279187     0.899551     0.346836     0.873571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.874929
    ├── F1 Score:  0.874757
    ├── Precision: 0.875259
    └── Recall:    0.874929

    ⏱️  ETA: 99.6 min remaining (25 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs32_SGD_lr0.0001_pinFalse_ep5.pth

[104/128] (81.2%) >>> Running: FashionMNIST | ResNet50 | BS=32 | SGD | LR=0.0001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 1.2204, Train Acc: 56.09%, Val Loss: 0.7169, Val Acc: 72.57%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.7042, Train Acc: 73.80%, Val Loss: 0.5832, Val Acc: 78.44%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.5872, Train Acc: 78.48%, Val Loss: 0.4939, Val Acc: 82.20%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.5235, Train Acc: 80.90%, Val Loss: 0.4589, Val Acc: 83.01%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.4770, Train Acc: 82.56%, Val Loss: 0.4393, Val Acc: 83.66%
    ✅ Done! Val Acc: 0.836571 | Test Acc: 0.836000 | Time: 267.80s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=32 | SGD | LR=0.0001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        1.220370     0.560878     0.716906     0.725714
    2        0.704211     0.737959     0.583234     0.784429
    3        0.587158     0.784755     0.493942     0.822000
    4        0.523545     0.808959     0.458939     0.830143
    5        0.477048     0.825571     0.439298     0.836571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.836000
    ├── F1 Score:  0.835374
    ├── Precision: 0.835570
    └── Recall:    0.836000

    ⏱️  ETA: 95.7 min remaining (24 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs32_SGD_lr0.0001_pinFalse_ep5.pth

[105/128] (82.0%) >>> Running: FashionMNIST | ResNet18 | BS=32 | Adam | LR=0.001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.4751, Train Acc: 83.09%, Val Loss: 0.3572, Val Acc: 87.23%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.3354, Train Acc: 87.74%, Val Loss: 0.3058, Val Acc: 88.76%
    ✅ Done! Val Acc: 0.887571 | Test Acc: 0.887643 | Time: 65.94s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=32 | Adam | LR=0.001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.475072     0.830878     0.357234     0.872286
    2        0.335380     0.877408     0.305841     0.887571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.887643
    ├── F1 Score:  0.886781
    ├── Precision: 0.887672
    └── Recall:    0.887643

    ⏱️  ETA: 91.2 min remaining (23 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs32_Adam_lr0.001_pinFalse_ep2.pth

[106/128] (82.8%) >>> Running: FashionMNIST | ResNet50 | BS=32 | Adam | LR=0.001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.7235, Train Acc: 76.75%, Val Loss: 0.4970, Val Acc: 81.40%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.5522, Train Acc: 81.44%, Val Loss: 0.4605, Val Acc: 84.76%
    ✅ Done! Val Acc: 0.847571 | Test Acc: 0.847714 | Time: 121.56s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=32 | Adam | LR=0.001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.723520     0.767510     0.496966     0.814000
    2        0.552217     0.814408     0.460524     0.847571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.847714
    ├── F1 Score:  0.846837
    ├── Precision: 0.853615
    └── Recall:    0.847714

    ⏱️  ETA: 86.8 min remaining (22 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs32_Adam_lr0.001_pinFalse_ep2.pth

[107/128] (83.6%) >>> Running: FashionMNIST | ResNet18 | BS=32 | Adam | LR=0.001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.4730, Train Acc: 83.09%, Val Loss: 0.3540, Val Acc: 86.90%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.3347, Train Acc: 87.84%, Val Loss: 0.3035, Val Acc: 89.17%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.2949, Train Acc: 89.19%, Val Loss: 0.2773, Val Acc: 89.64%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.2672, Train Acc: 90.08%, Val Loss: 0.2538, Val Acc: 90.56%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.2415, Train Acc: 91.05%, Val Loss: 0.2655, Val Acc: 90.39%
    ✅ Done! Val Acc: 0.903857 | Test Acc: 0.907643 | Time: 164.19s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=32 | Adam | LR=0.001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.472985     0.830939     0.354036     0.869000
    2        0.334721     0.878429     0.303490     0.891714
    3        0.294857     0.891918     0.277298     0.896429
    4        0.267162     0.900816     0.253766     0.905571
    5        0.241500     0.910469     0.265467     0.903857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.907643
    ├── F1 Score:  0.907080
    ├── Precision: 0.907552
    └── Recall:    0.907643

    ⏱️  ETA: 82.7 min remaining (21 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs32_Adam_lr0.001_pinFalse_ep5.pth

[108/128] (84.4%) >>> Running: FashionMNIST | ResNet50 | BS=32 | Adam | LR=0.001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.7348, Train Acc: 76.55%, Val Loss: 0.6395, Val Acc: 77.11%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.4289, Train Acc: 84.97%, Val Loss: 0.3684, Val Acc: 86.39%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.4418, Train Acc: 85.52%, Val Loss: 0.3654, Val Acc: 86.10%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.4488, Train Acc: 85.25%, Val Loss: 0.3460, Val Acc: 87.21%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.3447, Train Acc: 87.74%, Val Loss: 0.2835, Val Acc: 89.49%
    ✅ Done! Val Acc: 0.894857 | Test Acc: 0.894000 | Time: 319.76s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=32 | Adam | LR=0.001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.734829     0.765531     0.639453     0.771143
    2        0.428860     0.849673     0.368365     0.863857
    3        0.441780     0.855224     0.365359     0.861000
    4        0.448764     0.852490     0.346001     0.872143
    5        0.344727     0.877429     0.283483     0.894857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.894000
    ├── F1 Score:  0.893539
    ├── Precision: 0.893851
    └── Recall:    0.894000

    ⏱️  ETA: 79.0 min remaining (20 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs32_Adam_lr0.001_pinFalse_ep5.pth

[109/128] (85.2%) >>> Running: FashionMNIST | ResNet18 | BS=32 | Adam | LR=0.0001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.4804, Train Acc: 82.58%, Val Loss: 0.3525, Val Acc: 86.31%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.3233, Train Acc: 88.02%, Val Loss: 0.3179, Val Acc: 87.99%
    ✅ Done! Val Acc: 0.879857 | Test Acc: 0.881000 | Time: 71.70s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=32 | Adam | LR=0.0001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.480415     0.825816     0.352451     0.863143
    2        0.323277     0.880245     0.317908     0.879857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.881000
    ├── F1 Score:  0.881158
    ├── Precision: 0.882527
    └── Recall:    0.881000

    ⏱️  ETA: 74.6 min remaining (19 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs32_Adam_lr0.0001_pinFalse_ep2.pth

[110/128] (85.9%) >>> Running: FashionMNIST | ResNet50 | BS=32 | Adam | LR=0.0001 | PinMem=False | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.8876, Train Acc: 67.56%, Val Loss: 0.5548, Val Acc: 79.74%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.5312, Train Acc: 80.44%, Val Loss: 0.4678, Val Acc: 83.17%
    ✅ Done! Val Acc: 0.831714 | Test Acc: 0.826857 | Time: 127.51s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=32 | Adam | LR=0.0001 | PinMem=False | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.887614     0.675592     0.554758     0.797429
    2        0.531199     0.804449     0.467816     0.831714
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.826857
    ├── F1 Score:  0.821220
    ├── Precision: 0.828215
    └── Recall:    0.826857

    ⏱️  ETA: 70.4 min remaining (18 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs32_Adam_lr0.0001_pinFalse_ep2.pth

[111/128] (86.7%) >>> Running: FashionMNIST | ResNet18 | BS=32 | Adam | LR=0.0001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.4898, Train Acc: 82.36%, Val Loss: 0.3395, Val Acc: 87.60%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.3261, Train Acc: 87.94%, Val Loss: 0.3051, Val Acc: 88.94%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.2677, Train Acc: 90.01%, Val Loss: 0.2992, Val Acc: 88.77%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.2218, Train Acc: 91.56%, Val Loss: 0.2768, Val Acc: 90.06%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.1878, Train Acc: 92.95%, Val Loss: 0.2849, Val Acc: 89.73%
    ✅ Done! Val Acc: 0.897286 | Test Acc: 0.894714 | Time: 172.63s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=32 | Adam | LR=0.0001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.489753     0.823592     0.339522     0.876000
    2        0.326082     0.879408     0.305138     0.889429
    3        0.267682     0.900122     0.299191     0.887714
    4        0.221760     0.915592     0.276779     0.900571
    5        0.187811     0.929490     0.284948     0.897286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.894714
    ├── F1 Score:  0.892964
    ├── Precision: 0.895128
    └── Recall:    0.894714

    ⏱️  ETA: 66.4 min remaining (17 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs32_Adam_lr0.0001_pinFalse_ep5.pth

[112/128] (87.5%) >>> Running: FashionMNIST | ResNet50 | BS=32 | Adam | LR=0.0001 | PinMem=False | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.9197, Train Acc: 66.34%, Val Loss: 0.5648, Val Acc: 79.19%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.5335, Train Acc: 80.77%, Val Loss: 0.4550, Val Acc: 83.11%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.4304, Train Acc: 84.59%, Val Loss: 0.4151, Val Acc: 84.73%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.3639, Train Acc: 86.68%, Val Loss: 0.3908, Val Acc: 85.24%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.3182, Train Acc: 88.40%, Val Loss: 0.3535, Val Acc: 86.90%
    ✅ Done! Val Acc: 0.869000 | Test Acc: 0.869071 | Time: 309.26s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=32 | Adam | LR=0.0001 | PinMem=False | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.919739     0.663449     0.564773     0.791857
    2        0.533532     0.807694     0.455004     0.831143
    3        0.430390     0.845898     0.415068     0.847286
    4        0.363879     0.866837     0.390775     0.852429
    5        0.318161     0.884020     0.353534     0.869000
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.869071
    ├── F1 Score:  0.867758
    ├── Precision: 0.868796
    └── Recall:    0.869071

    ⏱️  ETA: 62.7 min remaining (16 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs32_Adam_lr0.0001_pinFalse_ep5.pth

[113/128] (88.3%) >>> Running: FashionMNIST | ResNet18 | BS=32 | SGD | LR=0.001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.4938, Train Acc: 82.19%, Val Loss: 0.3350, Val Acc: 87.44%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.3233, Train Acc: 88.03%, Val Loss: 0.3105, Val Acc: 88.67%
    ✅ Done! Val Acc: 0.886714 | Test Acc: 0.883429 | Time: 62.35s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=32 | SGD | LR=0.001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.493840     0.821878     0.335044     0.874429
    2        0.323343     0.880327     0.310494     0.886714
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.883429
    ├── F1 Score:  0.884216
    ├── Precision: 0.886208
    └── Recall:    0.883429

    ⏱️  ETA: 58.4 min remaining (15 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs32_SGD_lr0.001_pinTrue_ep2.pth

[114/128] (89.1%) >>> Running: FashionMNIST | ResNet50 | BS=32 | SGD | LR=0.001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.8430, Train Acc: 71.04%, Val Loss: 0.4958, Val Acc: 82.03%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.4896, Train Acc: 82.29%, Val Loss: 0.4108, Val Acc: 84.96%
    ✅ Done! Val Acc: 0.849571 | Test Acc: 0.848643 | Time: 117.84s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=32 | SGD | LR=0.001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.842978     0.710429     0.495802     0.820286
    2        0.489588     0.822939     0.410758     0.849571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.848643
    ├── F1 Score:  0.848365
    ├── Precision: 0.853034
    └── Recall:    0.848643

    ⏱️  ETA: 54.3 min remaining (14 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs32_SGD_lr0.001_pinTrue_ep2.pth

[115/128] (89.8%) >>> Running: FashionMNIST | ResNet18 | BS=32 | SGD | LR=0.001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.4915, Train Acc: 82.37%, Val Loss: 0.3318, Val Acc: 87.90%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.3252, Train Acc: 88.04%, Val Loss: 0.2931, Val Acc: 89.23%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.2685, Train Acc: 90.09%, Val Loss: 0.2768, Val Acc: 90.19%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.2291, Train Acc: 91.45%, Val Loss: 0.2805, Val Acc: 89.60%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.2011, Train Acc: 92.47%, Val Loss: 0.2783, Val Acc: 89.80%
    ✅ Done! Val Acc: 0.898000 | Test Acc: 0.898357 | Time: 160.20s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=32 | SGD | LR=0.001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.491490     0.823694     0.331799     0.879000
    2        0.325248     0.880388     0.293070     0.892286
    3        0.268487     0.900878     0.276769     0.901857
    4        0.229082     0.914531     0.280504     0.896000
    5        0.201067     0.924714     0.278330     0.898000
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.898357
    ├── F1 Score:  0.897566
    ├── Precision: 0.899422
    └── Recall:    0.898357

    ⏱️  ETA: 50.3 min remaining (13 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs32_SGD_lr0.001_pinTrue_ep5.pth

[116/128] (90.6%) >>> Running: FashionMNIST | ResNet50 | BS=32 | SGD | LR=0.001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.8110, Train Acc: 72.12%, Val Loss: 0.5365, Val Acc: 81.20%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.4942, Train Acc: 82.34%, Val Loss: 0.3776, Val Acc: 85.23%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.3951, Train Acc: 85.58%, Val Loss: 0.3485, Val Acc: 87.19%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.3372, Train Acc: 87.58%, Val Loss: 0.3392, Val Acc: 87.24%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.3020, Train Acc: 88.81%, Val Loss: 0.3139, Val Acc: 87.94%
    ✅ Done! Val Acc: 0.879429 | Test Acc: 0.885643 | Time: 274.49s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=32 | SGD | LR=0.001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.810954     0.721204     0.536504     0.812000
    2        0.494156     0.823388     0.377623     0.852286
    3        0.395103     0.855776     0.348477     0.871857
    4        0.337219     0.875776     0.339175     0.872429
    5        0.302003     0.888102     0.313903     0.879429
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.885643
    ├── F1 Score:  0.885926
    ├── Precision: 0.887307
    └── Recall:    0.885643

    ⏱️  ETA: 46.5 min remaining (12 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs32_SGD_lr0.001_pinTrue_ep5.pth

[117/128] (91.4%) >>> Running: FashionMNIST | ResNet18 | BS=32 | SGD | LR=0.0001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.7259, Train Acc: 75.52%, Val Loss: 0.4539, Val Acc: 83.61%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.4342, Train Acc: 84.50%, Val Loss: 0.3883, Val Acc: 86.06%
    ✅ Done! Val Acc: 0.860571 | Test Acc: 0.856071 | Time: 61.94s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=32 | SGD | LR=0.0001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.725876     0.755224     0.453902     0.836143
    2        0.434249     0.844980     0.388294     0.860571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.856071
    ├── F1 Score:  0.854581
    ├── Precision: 0.855910
    └── Recall:    0.856071

    ⏱️  ETA: 42.4 min remaining (11 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs32_SGD_lr0.0001_pinTrue_ep2.pth

[118/128] (92.2%) >>> Running: FashionMNIST | ResNet50 | BS=32 | SGD | LR=0.0001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 1.2386, Train Acc: 55.69%, Val Loss: 0.7089, Val Acc: 73.51%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.6772, Train Acc: 74.96%, Val Loss: 0.5722, Val Acc: 78.33%
    ✅ Done! Val Acc: 0.783286 | Test Acc: 0.782643 | Time: 110.14s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=32 | SGD | LR=0.0001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        1.238572     0.556939     0.708856     0.735143
    2        0.677190     0.749571     0.572238     0.783286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.782643
    ├── F1 Score:  0.778106
    ├── Precision: 0.776889
    └── Recall:    0.782643

    ⏱️  ETA: 38.4 min remaining (10 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs32_SGD_lr0.0001_pinTrue_ep2.pth

[119/128] (93.0%) >>> Running: FashionMNIST | ResNet18 | BS=32 | SGD | LR=0.0001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.6924, Train Acc: 76.70%, Val Loss: 0.4448, Val Acc: 84.20%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.4251, Train Acc: 84.84%, Val Loss: 0.3833, Val Acc: 85.93%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.3587, Train Acc: 87.15%, Val Loss: 0.3541, Val Acc: 87.27%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.3141, Train Acc: 88.69%, Val Loss: 0.3428, Val Acc: 87.53%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.2793, Train Acc: 89.90%, Val Loss: 0.3264, Val Acc: 88.26%
    ✅ Done! Val Acc: 0.882571 | Test Acc: 0.878643 | Time: 154.29s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=32 | SGD | LR=0.0001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.692407     0.766980     0.444806     0.842000
    2        0.425052     0.848388     0.383305     0.859286
    3        0.358669     0.871531     0.354108     0.872714
    4        0.314095     0.886898     0.342799     0.875286
    5        0.279342     0.899000     0.326379     0.882571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.878643
    ├── F1 Score:  0.878013
    ├── Precision: 0.878469
    └── Recall:    0.878643

    ⏱️  ETA: 34.5 min remaining (9 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs32_SGD_lr0.0001_pinTrue_ep5.pth

[120/128] (93.8%) >>> Running: FashionMNIST | ResNet50 | BS=32 | SGD | LR=0.0001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 1.1832, Train Acc: 57.38%, Val Loss: 0.6946, Val Acc: 73.57%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.6682, Train Acc: 75.41%, Val Loss: 0.5565, Val Acc: 79.66%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.5790, Train Acc: 78.78%, Val Loss: 0.4966, Val Acc: 82.07%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.5209, Train Acc: 80.92%, Val Loss: 0.4638, Val Acc: 82.61%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.4809, Train Acc: 82.41%, Val Loss: 0.4406, Val Acc: 83.76%
    ✅ Done! Val Acc: 0.837571 | Test Acc: 0.833643 | Time: 274.79s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=32 | SGD | LR=0.0001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        1.183233     0.573755     0.694615     0.735714
    2        0.668240     0.754143     0.556497     0.796571
    3        0.579022     0.787796     0.496617     0.820714
    4        0.520917     0.809204     0.463805     0.826143
    5        0.480945     0.824143     0.440619     0.837571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.833643
    ├── F1 Score:  0.827978
    ├── Precision: 0.833309
    └── Recall:    0.833643

    ⏱️  ETA: 30.7 min remaining (8 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs32_SGD_lr0.0001_pinTrue_ep5.pth

[121/128] (94.5%) >>> Running: FashionMNIST | ResNet18 | BS=32 | Adam | LR=0.001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.4704, Train Acc: 83.06%, Val Loss: 0.3345, Val Acc: 87.84%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.3354, Train Acc: 87.88%, Val Loss: 0.3056, Val Acc: 88.63%
    ✅ Done! Val Acc: 0.886286 | Test Acc: 0.883786 | Time: 68.12s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=32 | Adam | LR=0.001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.470446     0.830592     0.334503     0.878429
    2        0.335429     0.878755     0.305634     0.886286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.883786
    ├── F1 Score:  0.883794
    ├── Precision: 0.884756
    └── Recall:    0.883786

    ⏱️  ETA: 26.7 min remaining (7 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs32_Adam_lr0.001_pinTrue_ep2.pth

[122/128] (95.3%) >>> Running: FashionMNIST | ResNet50 | BS=32 | Adam | LR=0.001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.6655, Train Acc: 78.13%, Val Loss: 0.7463, Val Acc: 75.41%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.5868, Train Acc: 81.14%, Val Loss: 0.5994, Val Acc: 81.29%
    ✅ Done! Val Acc: 0.812857 | Test Acc: 0.807143 | Time: 124.16s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=32 | Adam | LR=0.001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.665492     0.781286     0.746308     0.754143
    2        0.586840     0.811367     0.599388     0.812857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.807143
    ├── F1 Score:  0.799533
    ├── Precision: 0.821794
    └── Recall:    0.807143

    ⏱️  ETA: 22.8 min remaining (6 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs32_Adam_lr0.001_pinTrue_ep2.pth

[123/128] (96.1%) >>> Running: FashionMNIST | ResNet18 | BS=32 | Adam | LR=0.001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.4755, Train Acc: 82.99%, Val Loss: 0.3811, Val Acc: 86.27%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.3362, Train Acc: 87.79%, Val Loss: 0.3502, Val Acc: 87.64%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.2942, Train Acc: 89.31%, Val Loss: 0.3006, Val Acc: 88.46%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.2720, Train Acc: 90.09%, Val Loss: 0.2702, Val Acc: 89.63%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.2420, Train Acc: 91.21%, Val Loss: 0.2747, Val Acc: 89.77%
    ✅ Done! Val Acc: 0.897714 | Test Acc: 0.897857 | Time: 166.93s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=32 | Adam | LR=0.001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.475456     0.829939     0.381061     0.862714
    2        0.336229     0.877878     0.350213     0.876429
    3        0.294203     0.893143     0.300611     0.884571
    4        0.271975     0.900918     0.270184     0.896286
    5        0.242019     0.912061     0.274742     0.897714
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.897857
    ├── F1 Score:  0.898472
    ├── Precision: 0.901197
    └── Recall:    0.897857

    ⏱️  ETA: 19.0 min remaining (5 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs32_Adam_lr0.001_pinTrue_ep5.pth

[124/128] (96.9%) >>> Running: FashionMNIST | ResNet50 | BS=32 | Adam | LR=0.001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.6807, Train Acc: 77.83%, Val Loss: 0.4893, Val Acc: 82.13%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.5492, Train Acc: 81.73%, Val Loss: 0.3883, Val Acc: 86.07%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.4907, Train Acc: 83.91%, Val Loss: 0.3869, Val Acc: 85.37%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.3797, Train Acc: 86.92%, Val Loss: 0.3522, Val Acc: 86.67%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.3863, Train Acc: 87.24%, Val Loss: 0.3948, Val Acc: 86.59%
    ✅ Done! Val Acc: 0.865857 | Test Acc: 0.864071 | Time: 304.44s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=32 | Adam | LR=0.001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.680735     0.778327     0.489271     0.821286
    2        0.549224     0.817265     0.388332     0.860714
    3        0.490669     0.839082     0.386911     0.853714
    4        0.379676     0.869184     0.352164     0.866714
    5        0.386301     0.872388     0.394839     0.865857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.864071
    ├── F1 Score:  0.863819
    ├── Precision: 0.866362
    └── Recall:    0.864071

    ⏱️  ETA: 15.2 min remaining (4 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs32_Adam_lr0.001_pinTrue_ep5.pth

[125/128] (97.7%) >>> Running: FashionMNIST | ResNet18 | BS=32 | Adam | LR=0.0001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.4909, Train Acc: 82.40%, Val Loss: 0.3473, Val Acc: 87.10%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.3256, Train Acc: 88.27%, Val Loss: 0.3138, Val Acc: 88.04%
    ✅ Done! Val Acc: 0.880429 | Test Acc: 0.880143 | Time: 68.98s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=32 | Adam | LR=0.0001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.490863     0.824041     0.347326     0.871000
    2        0.325571     0.882673     0.313805     0.880429
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.880143
    ├── F1 Score:  0.880242
    ├── Precision: 0.882556
    └── Recall:    0.880143

    ⏱️  ETA: 11.4 min remaining (3 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs32_Adam_lr0.0001_pinTrue_ep2.pth

[126/128] (98.4%) >>> Running: FashionMNIST | ResNet50 | BS=32 | Adam | LR=0.0001 | PinMem=True | Ep=2

Epoch 1/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.9050, Train Acc: 66.89%, Val Loss: 0.5912, Val Acc: 78.16%

Epoch 2/2 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.5411, Train Acc: 80.24%, Val Loss: 0.4464, Val Acc: 83.81%
    ✅ Done! Val Acc: 0.838143 | Test Acc: 0.830286 | Time: 125.37s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=32 | Adam | LR=0.0001 | PinMem=True | Ep=2
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.904974     0.668898     0.591175     0.781571
    2        0.541059     0.802408     0.446436     0.838143
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.830286
    ├── F1 Score:  0.829308
    ├── Precision: 0.830332
    └── Recall:    0.830286

    ⏱️  ETA: 7.6 min remaining (2 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs32_Adam_lr0.0001_pinTrue_ep2.pth

[127/128] (99.2%) >>> Running: FashionMNIST | ResNet18 | BS=32 | Adam | LR=0.0001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.4784, Train Acc: 82.79%, Val Loss: 0.3868, Val Acc: 85.34%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.3220, Train Acc: 88.13%, Val Loss: 0.3278, Val Acc: 87.77%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.2621, Train Acc: 90.26%, Val Loss: 0.2806, Val Acc: 89.66%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.2202, Train Acc: 91.71%, Val Loss: 0.2954, Val Acc: 89.21%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.1833, Train Acc: 93.03%, Val Loss: 0.3082, Val Acc: 89.39%
    ✅ Done! Val Acc: 0.893857 | Test Acc: 0.896857 | Time: 167.54s

    📊 Training Summary for: FashionMNIST | ResNet18 | BS=32 | Adam | LR=0.0001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.478359     0.827857     0.386761     0.853429
    2        0.321958     0.881265     0.327815     0.877714
    3        0.262145     0.902571     0.280649     0.896571
    4        0.220204     0.917061     0.295371     0.892143
    5        0.183313     0.930327     0.308197     0.893857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.896857
    ├── F1 Score:  0.895998
    ├── Precision: 0.896053
    └── Recall:    0.896857

    ⏱️  ETA: 3.8 min remaining (1 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet18_bs32_Adam_lr0.0001_pinTrue_ep5.pth

[128/128] (100.0%) >>> Running: FashionMNIST | ResNet50 | BS=32 | Adam | LR=0.0001 | PinMem=True | Ep=5

Epoch 1/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/5 - Train Loss: 0.9169, Train Acc: 66.49%, Val Loss: 0.6193, Val Acc: 77.43%

Epoch 2/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/5 - Train Loss: 0.5411, Train Acc: 80.46%, Val Loss: 0.4608, Val Acc: 83.07%

Epoch 3/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 3/5 - Train Loss: 0.4281, Train Acc: 84.23%, Val Loss: 0.4158, Val Acc: 84.66%

Epoch 4/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 4/5 - Train Loss: 0.3653, Train Acc: 86.52%, Val Loss: 0.3775, Val Acc: 86.43%

Epoch 5/5 [Train]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 5/5 - Train Loss: 0.3184, Train Acc: 88.12%, Val Loss: 0.3749, Val Acc: 86.29%
    ✅ Done! Val Acc: 0.862857 | Test Acc: 0.864714 | Time: 304.96s

    📊 Training Summary for: FashionMNIST | ResNet50 | BS=32 | Adam | LR=0.0001 | PinMem=True | Ep=5
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.916897     0.664939     0.619303     0.774286
    2        0.541053     0.804592     0.460780     0.830714
    3        0.428114     0.842306     0.415817     0.846571
    4        0.365279     0.865184     0.377474     0.864286
    5        0.318375     0.881163     0.374886     0.862857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.864714
    ├── F1 Score:  0.863509
    ├── Precision: 0.865531
    └── Recall:    0.864714

    ⏱️  ETA: 0.0 min remaining (0 experiments left)
    💾 Saved model to models/FashionMNIST_ResNet50_bs32_Adam_lr0.0001_pinTrue_ep5.pth

======================================================================
✅ All Q1(a) Experiments Completed: 128/128
⏱️  Total Time: 484.24 minutes
======================================================================

In [6]:
# --- Summary Tables: Compare ALL Experiments ---
print("=" * 70)
print("Q1(a) SUMMARY - TEXT ANALYSIS")
print("=" * 70)

df_plot = pd.DataFrame(results)

# 1. Best Models Summary
print("\n📊 BEST MODELS BY DATASET AND MODEL TYPE:")
print("-" * 70)
best_models = df_plot.loc[df_plot.groupby(['Dataset', 'Model'])['Test Accuracy'].idxmax()]
for _, row in best_models.iterrows():
    print(f"  {row['Dataset']} + {row['Model']}")
    print(f"    ├── Best Accuracy: {row['Test Accuracy']:.6f}%")
    print(f"    ├── Config: BS={row['Batch Size']}, {row['Optimizer']}, LR={row['Learning Rate']}, Epochs={row['Epochs']}")
    print(f"    └── Training Time: {row['Training Time (s)']:.2f}s")
    print()

# 2. Accuracy Statistics by Model and Dataset
print("\n📈 ACCURACY STATISTICS BY DATASET & MODEL:")
print("-" * 70)
stats = df_plot.groupby(['Dataset', 'Model'])['Test Accuracy'].agg(['mean', 'max', 'min', 'std'])
display(stats.round(6))

# 3. Training Time Statistics
print("\n⏱️  TRAINING TIME STATISTICS:")
print("-" * 70)
time_stats = df_plot.groupby(['Dataset', 'Model'])['Training Time (s)'].agg(['mean', 'min', 'max', 'sum'])
display(time_stats.round(2))

# 4. Accuracy by Hyperparameter
print("\n🔧 MEAN ACCURACY BY HYPERPARAMETER:")
print("-" * 70)

print("\n  By Optimizer:")
opt_stats = df_plot.groupby('Optimizer')['Test Accuracy'].agg(['mean', 'std']).round(6)
display(opt_stats)

print("\n  By Learning Rate:")
lr_stats = df_plot.groupby('Learning Rate')['Test Accuracy'].agg(['mean', 'std']).round(6)
display(lr_stats)

print("\n  By Batch Size:")
bs_stats = df_plot.groupby('Batch Size')['Test Accuracy'].agg(['mean', 'std']).round(6)
display(bs_stats)

print("\n  By Epochs:")
ep_stats = df_plot.groupby('Epochs')['Test Accuracy'].agg(['mean', 'std']).round(6)
display(ep_stats)

# 5. Complete Metrics Summary Table
print("\n📋 COMPLETE METRICS SUMMARY:")
print("-" * 70)
metrics_summary = df_plot.groupby(['Dataset', 'Model']).agg({
    'Test Accuracy': ['mean', 'max', 'std'],
    'F1 Score': ['mean', 'max', 'std'],
    'Precision': ['mean', 'max', 'std'],
    'Recall': ['mean', 'max', 'std'],
    'Training Time (s)': ['mean', 'min', 'max']
}).round(6)
display(metrics_summary)
metrics_summary.to_csv('Q1a_metrics_summary.csv')
print("✅ Saved metrics summary to Q1a_metrics_summary.csv")

======================================================================
Q1(a) SUMMARY - TEXT ANALYSIS
======================================================================

📊 BEST MODELS BY DATASET AND MODEL TYPE:
----------------------------------------------------------------------
  FashionMNIST + ResNet18
    ├── Best Accuracy: 90.764286%
    ├── Config: BS=32, Adam, LR=0.001, Epochs=5
    └── Training Time: 164.19s

  FashionMNIST + ResNet50
    ├── Best Accuracy: 89.400000%
    ├── Config: BS=32, Adam, LR=0.001, Epochs=5
    └── Training Time: 319.76s

  MNIST + ResNet18
    ├── Best Accuracy: 99.014286%
    ├── Config: BS=16, Adam, LR=0.001, Epochs=5
    └── Training Time: 279.89s

  MNIST + ResNet50
    ├── Best Accuracy: 98.700000%
    ├── Config: BS=32, SGD, LR=0.001, Epochs=5
    └── Training Time: 269.34s


📈 ACCURACY STATISTICS BY DATASET & MODEL:
----------------------------------------------------------------------

                           mean       max       min      std
Dataset      Model
FashionMNIST ResNet18 88.551339 90.764286 85.607143 1.327344
             ResNet50 85.032366 89.400000 78.264286 2.934548
MNIST        ResNet18 98.259821 99.014286 96.357143 0.611813
             ResNet50 96.845982 98.700000 92.957143 1.556477

⏱️  TRAINING TIME STATISTICS:
----------------------------------------------------------------------

                            mean        min        max         sum
Dataset      Model
FashionMNIST ResNet18 147.970000  59.810000 278.840000 4735.130000
             ResNet50 281.610000 106.740000 552.130000 9011.530000
MNIST        ResNet18 148.630000  60.010000 281.350000 4756.130000
             ResNet50 279.670000 105.760000 550.710000 8949.550000

🔧 MEAN ACCURACY BY HYPERPARAMETER:
----------------------------------------------------------------------

  By Optimizer:

               mean      std
Optimizer
Adam      92.282143 5.520811
SGD       92.062612 6.200690

  By Learning Rate:

                   mean      std
Learning Rate
0.000100      91.483594 6.218110
0.001000      92.861161 5.415126

  By Batch Size:

                mean      std
Batch Size
16         92.395759 5.732749
32         91.948996 5.998883

  By Epochs:

            mean      std
Epochs
2      91.165513 6.290233
5      93.179241 5.227392

📋 COMPLETE METRICS SUMMARY:
----------------------------------------------------------------------

                      Test Accuracy                    F1 Score           \
                               mean       max      std     mean      max
Dataset      Model
FashionMNIST ResNet18     88.551339 90.764286 1.327344 0.885329 0.907080
             ResNet50     85.032366 89.400000 2.934548 0.848243 0.893539
MNIST        ResNet18     98.259821 99.014286 0.611813 0.982573 0.990150
             ResNet50     96.845982 98.700000 1.556477 0.968394 0.986984

                               Precision                     Recall           \
                           std      mean      max      std     mean      max
Dataset      Model
FashionMNIST ResNet18 0.013165  0.887028 0.907552 0.012851 0.885513 0.907643
             ResNet50 0.031336  0.852383 0.893851 0.029799 0.850324 0.894000
MNIST        ResNet18 0.006174  0.982814 0.990194 0.005740 0.982598 0.990143
             ResNet50 0.015699  0.969128 0.987025 0.014661 0.968460 0.987000

                               Training Time (s)
                           std              mean        min        max
Dataset      Model
FashionMNIST ResNet18 0.013273        147.972895  59.814627 278.839568
             ResNet50 0.029345        281.610265 106.742092 552.127002
MNIST        ResNet18 0.006118        148.628926  60.006474 281.352159
             ResNet50 0.015565        279.673539 105.760104 550.711372

✅ Saved metrics summary to Q1a_metrics_summary.csv

## 5. Q1(a) Results Analysis
The table below shows the classification accuracy on the test set for all configurations.

In [7]:
df = pd.DataFrame(results)

# Pivot table to match the requested format: Columns for ResNet-18 and ResNet-50
pivot_df = df.pivot_table(index=['Dataset', 'Batch Size', 'Optimizer', 'Learning Rate'], 
                          columns='Model', 
                          values=['Test Accuracy', 'F1 Score', 'Precision', 'Recall']).reset_index()

pivot_df.columns.name = None # Remove 'Model' as name of columns index

display(pivot_df)

pivot_df.to_csv('final_results.csv', index=False)

            Dataset Batch Size Optimizer Learning Rate F1 Score           \
Model                                                  ResNet18 ResNet50
0      FashionMNIST         16      Adam      0.000100 0.882132 0.857597
1      FashionMNIST         16      Adam      0.001000 0.888686 0.863650
2      FashionMNIST         16       SGD      0.000100 0.877178 0.828783
3      FashionMNIST         16       SGD      0.001000 0.894592 0.863930
4      FashionMNIST         32      Adam      0.000100 0.887590 0.845449
5      FashionMNIST         32      Adam      0.001000 0.894032 0.850932
6      FashionMNIST         32       SGD      0.000100 0.866127 0.806371
7      FashionMNIST         32       SGD      0.001000 0.892294 0.869228
8             MNIST         16      Adam      0.000100 0.985612 0.968577
9             MNIST         16      Adam      0.001000 0.985544 0.958191
10            MNIST         16       SGD      0.000100 0.981351 0.969939
11            MNIST         16       SGD      0.001000 0.987222 0.982430
12            MNIST         32      Adam      0.000100 0.982640 0.960808
13            MNIST         32      Adam      0.001000 0.977164 0.972020
14            MNIST         32       SGD      0.000100 0.973998 0.952588
15            MNIST         32       SGD      0.001000 0.987051 0.982600

      Precision            Recall          Test Accuracy
Model  ResNet18 ResNet50 ResNet18 ResNet50      ResNet18  ResNet50
0      0.885637 0.861576 0.881679 0.857643     88.167857 85.764286
1      0.892502 0.867324 0.888268 0.863018     88.826786 86.301786
2      0.877474 0.829882 0.877446 0.831893     87.744643 83.189286
3      0.895773 0.873071 0.894929 0.869071     89.492857 86.907143
4      0.889066 0.848218 0.888178 0.847732     88.817857 84.773214
5      0.895294 0.858905 0.894232 0.853232     89.423214 85.323215
6      0.866896 0.808430 0.866911 0.810250     86.691071 81.025000
7      0.893579 0.871657 0.892464 0.869750     89.246428 86.975000
8      0.985672 0.969035 0.985625 0.968572     98.562500 96.857143
9      0.985654 0.961903 0.985553 0.958607     98.555357 95.860715
10     0.981391 0.970111 0.981357 0.969982     98.135714 96.998214
11     0.987305 0.982567 0.987232 0.982447     98.723214 98.244643
12     0.982782 0.961232 0.982643 0.960839     98.264285 96.083929
13     0.978563 0.972675 0.977303 0.972018     97.730357 97.201786
14     0.974064 0.952819 0.974018 0.952607     97.401786 95.260715
15     0.987078 0.982681 0.987054 0.982607     98.705357 98.260715

### Detailed Analysis for Q1(a)

**Impact of Learning Rate:**
- Higher learning rate (0.001) generally leads to faster convergence but may cause instability
- Lower learning rate (0.0001) provides more stable training but requires more epochs to converge
- Adam optimizer is less sensitive to learning rate choices compared to SGD

**Optimizer Performance (SGD vs Adam):**
- Adam typically achieves higher accuracy in fewer epochs due to adaptive learning rates
- SGD with momentum can match or exceed Adam's performance with proper learning rate tuning
- Adam is more robust to hyperparameter choices

**Model Depth (ResNet18 vs ResNet50):**
- ResNet-50 has more capacity but may overfit on simpler datasets like MNIST
- ResNet-18 often performs comparably or better on MNIST/FashionMNIST due to their simplicity
- Training time significantly increases with ResNet-50

**Batch Size Effects:**
- Larger batch sizes (32) provide more stable gradients but may generalize worse
- Smaller batch sizes (16) introduce more noise which can help escape local minima
- pin_memory=True improves data loading speed when using GPU

**Epochs Analysis:**
- More epochs (5) generally improve accuracy but risk overfitting
- Early stopping based on validation accuracy is recommended
- Training curves help identify optimal stopping point

---
## Q1(b): SVM Classifier on MNIST and FashionMNIST
Train SVM classifiers with different kernels ('poly', 'rbf') and report Testing Classification Accuracy with training time.

In [8]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix
import time

def get_flattened_data(dataset_name, max_samples=10000):
    """Load and flatten dataset for SVM (subsample for speed)"""
    transform = transforms.Compose([transforms.ToTensor()])
    
    if dataset_name == 'MNIST':
        train_data = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
        test_data = datasets.MNIST(root='./data', train=False, download=True, transform=transform)
    else:
        train_data = datasets.FashionMNIST(root='./data', train=True, download=True, transform=transform)
        test_data = datasets.FashionMNIST(root='./data', train=False, download=True, transform=transform)
    
    # Subsample for SVM (full dataset is too slow)
    train_indices = np.random.choice(len(train_data), min(max_samples, len(train_data)), replace=False)
    test_indices = np.random.choice(len(test_data), min(max_samples // 5, len(test_data)), replace=False)
    
    X_train = np.array([train_data[i][0].numpy().flatten() for i in train_indices])
    y_train = np.array([train_data[i][1] for i in train_indices])
    X_test = np.array([test_data[i][0].numpy().flatten() for i in test_indices])
    y_test = np.array([test_data[i][1] for i in test_indices])
    
    # Standardize features
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)
    
    return X_train, y_train, X_test, y_test

def display_svm_metrics(metrics_dict, config_str):
    """Display SVM metrics as text summary"""
    print(f"\n    📈 SVM Evaluation Metrics:")
    print(f"    ├── Accuracy:  {metrics_dict['accuracy']:.6f}%")
    print(f"    ├── F1 Score:  {metrics_dict['f1']:.6f}")
    print(f"    ├── Precision: {metrics_dict['precision']:.6f}")
    print(f"    └── Recall:    {metrics_dict['recall']:.6f}")

# SVM Experiments
svm_results = []
svm_kernels = ['poly', 'rbf']
svm_datasets = ['MNIST', 'FashionMNIST']
svm_C_values = [0.1, 1.0, 10.0]  # Regularization parameter
svm_gamma_values = ['scale', 'auto']

print("=" * 60)
print("Q1(b): SVM Classification Experiments")
print("=" * 60)

# Calculate total SVM experiments
total_svm_experiments = len(svm_datasets) * len(svm_kernels) * len(svm_C_values) * len(svm_gamma_values)
current_svm_experiment = 0
svm_start_time = time.time()
print(f"Total SVM experiments to run: {total_svm_experiments}")

for dataset_name in svm_datasets:
    print(f"\n--- Dataset: {dataset_name} ---")
    X_train, y_train, X_test, y_test = get_flattened_data(dataset_name, max_samples=10000)
    print(f"Train samples: {len(X_train)}, Test samples: {len(X_test)}")
    
    for kernel in svm_kernels:
        for C in svm_C_values:
            for gamma in svm_gamma_values:
                current_svm_experiment += 1
                svm_progress_pct = (current_svm_experiment / total_svm_experiments) * 100
                config_str = f"{dataset_name} | kernel={kernel} | C={C} | gamma={gamma}"
                print(f"\n[{current_svm_experiment}/{total_svm_experiments}] ({svm_progress_pct:.1f}%) >>> Running: {config_str}")
                
                try:
                    # Train SVM
                    if kernel == 'poly':
                        svm = SVC(kernel=kernel, C=C, gamma=gamma, degree=3)
                    else:
                        svm = SVC(kernel=kernel, C=C, gamma=gamma)
                    
                    t0 = time.time()
                    svm.fit(X_train, y_train)
                    train_time_ms = (time.time() - t0) * 1000
                    
                    # Predict
                    y_pred = svm.predict(X_test)
                    
                    # Metrics
                    acc = accuracy_score(y_test, y_pred) * 100
                    f1 = f1_score(y_test, y_pred, average='weighted')
                    prec = precision_score(y_test, y_pred, average='weighted')
                    rec = recall_score(y_test, y_pred, average='weighted')
                    
                    print(f"    ✅ Done! Train Time: {train_time_ms:.2f} ms")
                    
                    # --- DISPLAY SVM METRICS AS TEXT ---
                    metrics_dict = {
                        'accuracy': acc,
                        'f1': f1,
                        'precision': prec,
                        'recall': rec
                    }
                    display_svm_metrics(metrics_dict, config_str)
                    
                    # ETA for SVM
                    svm_elapsed = time.time() - svm_start_time
                    svm_avg_time = svm_elapsed / current_svm_experiment
                    svm_remaining = total_svm_experiments - current_svm_experiment
                    svm_eta_min = (svm_avg_time * svm_remaining) / 60
                    print(f"\n    ⏱️  ETA: {svm_eta_min:.1f} min remaining ({svm_remaining} experiments left)")
                    
                    svm_results.append({
                        'Dataset': dataset_name,
                        'Kernel': kernel,
                        'C': C,
                        'Gamma': gamma,
                        'Test Accuracy (%)': round(acc, 6),
                        'F1 Score': round(f1, 6),
                        'Precision': round(prec, 6),
                        'Recall': round(rec, 6),
                        'Training Time (ms)': round(train_time_ms, 6)
                    })
                    
                    # Crash-safe: Save after each experiment
                    pd.DataFrame(svm_results).to_csv('svm_results_q1b.csv', index=False)
                    
                except Exception as e:
                    print(f"❌ Error: {e}")

# SVM Results DataFrame
df_svm = pd.DataFrame(svm_results)
svm_total_time = time.time() - svm_start_time
print(f"\n{'=' * 60}")
print(f"✅ Q1(b) SVM Experiments Completed: {current_svm_experiment}/{total_svm_experiments}")
print(f"⏱️  Total Time: {svm_total_time/60:.2f} minutes")
print("=" * 60)
display(df_svm)
df_svm.to_csv('svm_results_q1b.csv', index=False)

# --- SVM Summary (Text-based) ---
print("\n" + "=" * 60)
print("Q1(b) SVM SUMMARY - TEXT ANALYSIS")
print("=" * 60)

# Best SVM models
print("\n📊 BEST SVM MODELS BY DATASET:")
print("-" * 60)
best_svm = df_svm.loc[df_svm.groupby('Dataset')['Test Accuracy (%)'].idxmax()]
for _, row in best_svm.iterrows():
    print(f"  {row['Dataset']}")
    print(f"    ├── Best Accuracy: {row['Test Accuracy (%)']:.6f}%")
    print(f"    ├── Config: kernel={row['Kernel']}, C={row['C']}, gamma={row['Gamma']}")
    print(f"    └── Training Time: {row['Training Time (ms)']:.2f} ms")
    print()

# Accuracy by Kernel
print("\n📈 MEAN ACCURACY BY KERNEL:")
kernel_stats = df_svm.groupby('Kernel')['Test Accuracy (%)'].agg(['mean', 'max', 'std']).round(6)
display(kernel_stats)

# Accuracy by C value
print("\n📈 MEAN ACCURACY BY C VALUE:")
c_stats = df_svm.groupby('C')['Test Accuracy (%)'].agg(['mean', 'max', 'std']).round(6)
display(c_stats)

# Training time statistics
print("\n⏱️  TRAINING TIME STATISTICS:")
time_stats = df_svm.groupby(['Dataset', 'Kernel'])['Training Time (ms)'].agg(['mean', 'min', 'max']).round(2)
display(time_stats)

print("\n✅ Saved SVM results to svm_results_q1b.csv")

============================================================
Q1(b): SVM Classification Experiments
============================================================
Total SVM experiments to run: 24

--- Dataset: MNIST ---
Train samples: 10000, Test samples: 2000

[1/24] (4.2%) >>> Running: MNIST | kernel=poly | C=0.1 | gamma=scale
    ✅ Done! Train Time: 39593.34 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  54.750000%
    ├── F1 Score:  0.578604
    ├── Precision: 0.833002
    └── Recall:    0.547500

    ⏱️  ETA: 18.9 min remaining (23 experiments left)

[2/24] (8.3%) >>> Running: MNIST | kernel=poly | C=0.1 | gamma=auto
    ✅ Done! Train Time: 41302.34 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  38.300000%
    ├── F1 Score:  0.415198
    ├── Precision: 0.841698
    └── Recall:    0.383000

    ⏱️  ETA: 18.0 min remaining (22 experiments left)

[3/24] (12.5%) >>> Running: MNIST | kernel=poly | C=1.0 | gamma=scale
    ✅ Done! Train Time: 22815.17 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  91.500000%
    ├── F1 Score:  0.918552
    ├── Precision: 0.930848
    └── Recall:    0.915000

    ⏱️  ETA: 14.6 min remaining (21 experiments left)

[4/24] (16.7%) >>> Running: MNIST | kernel=poly | C=1.0 | gamma=auto
    ✅ Done! Train Time: 25878.82 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  87.950000%
    ├── F1 Score:  0.887632
    ├── Precision: 0.915480
    └── Recall:    0.879500

    ⏱️  ETA: 13.1 min remaining (20 experiments left)

[5/24] (20.8%) >>> Running: MNIST | kernel=poly | C=10.0 | gamma=scale
    ✅ Done! Train Time: 16029.76 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  95.500000%
    ├── F1 Score:  0.955114
    ├── Precision: 0.955722
    └── Recall:    0.955000

    ⏱️  ETA: 11.1 min remaining (19 experiments left)

[6/24] (25.0%) >>> Running: MNIST | kernel=poly | C=10.0 | gamma=auto
    ✅ Done! Train Time: 16236.43 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  95.350000%
    ├── F1 Score:  0.953705
    ├── Precision: 0.954689
    └── Recall:    0.953500

    ⏱️  ETA: 9.8 min remaining (18 experiments left)

[7/24] (29.2%) >>> Running: MNIST | kernel=rbf | C=0.1 | gamma=scale
    ✅ Done! Train Time: 20014.38 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  89.350000%
    ├── F1 Score:  0.894577
    ├── Precision: 0.899443
    └── Recall:    0.893500

    ⏱️  ETA: 9.1 min remaining (17 experiments left)

[8/24] (33.3%) >>> Running: MNIST | kernel=rbf | C=0.1 | gamma=auto
    ✅ Done! Train Time: 19743.94 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  89.850000%
    ├── F1 Score:  0.898856
    ├── Precision: 0.901761
    └── Recall:    0.898500

    ⏱️  ETA: 8.5 min remaining (16 experiments left)

[9/24] (37.5%) >>> Running: MNIST | kernel=rbf | C=1.0 | gamma=scale
    ✅ Done! Train Time: 11361.69 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  94.850000%
    ├── F1 Score:  0.948441
    ├── Precision: 0.948676
    └── Recall:    0.948500

    ⏱️  ETA: 7.6 min remaining (15 experiments left)

[10/24] (41.7%) >>> Running: MNIST | kernel=rbf | C=1.0 | gamma=auto
    ✅ Done! Train Time: 10717.61 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  95.200000%
    ├── F1 Score:  0.951952
    ├── Precision: 0.952157
    └── Recall:    0.952000

    ⏱️  ETA: 6.7 min remaining (14 experiments left)

[11/24] (45.8%) >>> Running: MNIST | kernel=rbf | C=10.0 | gamma=scale
    ✅ Done! Train Time: 10730.04 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  95.600000%
    ├── F1 Score:  0.956006
    ├── Precision: 0.956258
    └── Recall:    0.956000

    ⏱️  ETA: 6.0 min remaining (13 experiments left)

[12/24] (50.0%) >>> Running: MNIST | kernel=rbf | C=10.0 | gamma=auto
    ✅ Done! Train Time: 9775.64 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  95.550000%
    ├── F1 Score:  0.955471
    ├── Precision: 0.955628
    └── Recall:    0.955500

    ⏱️  ETA: 5.3 min remaining (12 experiments left)

--- Dataset: FashionMNIST ---
Train samples: 10000, Test samples: 2000

[13/24] (54.2%) >>> Running: FashionMNIST | kernel=poly | C=0.1 | gamma=scale
    ✅ Done! Train Time: 21222.20 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  69.050000%
    ├── F1 Score:  0.716332
    ├── Precision: 0.809386
    └── Recall:    0.690500

    ⏱️  ETA: 4.9 min remaining (11 experiments left)

[14/24] (58.3%) >>> Running: FashionMNIST | kernel=poly | C=0.1 | gamma=auto
    ✅ Done! Train Time: 21332.99 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  69.050000%
    ├── F1 Score:  0.716332
    ├── Precision: 0.809386
    └── Recall:    0.690500

    ⏱️  ETA: 4.5 min remaining (10 experiments left)

[15/24] (62.5%) >>> Running: FashionMNIST | kernel=poly | C=1.0 | gamma=scale
    ✅ Done! Train Time: 11343.18 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  82.150000%
    ├── F1 Score:  0.827252
    ├── Precision: 0.838125
    └── Recall:    0.821500

    ⏱️  ETA: 3.9 min remaining (9 experiments left)

[16/24] (66.7%) >>> Running: FashionMNIST | kernel=poly | C=1.0 | gamma=auto
    ✅ Done! Train Time: 11507.88 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  82.150000%
    ├── F1 Score:  0.827252
    ├── Precision: 0.838125
    └── Recall:    0.821500

    ⏱️  ETA: 3.4 min remaining (8 experiments left)

[17/24] (70.8%) >>> Running: FashionMNIST | kernel=poly | C=10.0 | gamma=scale
    ✅ Done! Train Time: 9358.36 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  85.150000%
    ├── F1 Score:  0.852235
    ├── Precision: 0.853310
    └── Recall:    0.851500

    ⏱️  ETA: 2.9 min remaining (7 experiments left)

[18/24] (75.0%) >>> Running: FashionMNIST | kernel=poly | C=10.0 | gamma=auto
    ✅ Done! Train Time: 9229.09 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  85.150000%
    ├── F1 Score:  0.852235
    ├── Precision: 0.853310
    └── Recall:    0.851500

    ⏱️  ETA: 2.4 min remaining (6 experiments left)

[19/24] (79.2%) >>> Running: FashionMNIST | kernel=rbf | C=0.1 | gamma=scale
    ✅ Done! Train Time: 14453.42 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  78.650000%
    ├── F1 Score:  0.783113
    ├── Precision: 0.784877
    └── Recall:    0.786500

    ⏱️  ETA: 2.0 min remaining (5 experiments left)

[20/24] (83.3%) >>> Running: FashionMNIST | kernel=rbf | C=0.1 | gamma=auto
    ✅ Done! Train Time: 14829.97 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  78.650000%
    ├── F1 Score:  0.783113
    ├── Precision: 0.784877
    └── Recall:    0.786500

    ⏱️  ETA: 1.6 min remaining (4 experiments left)

[21/24] (87.5%) >>> Running: FashionMNIST | kernel=rbf | C=1.0 | gamma=scale
    ✅ Done! Train Time: 9352.65 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  85.000000%
    ├── F1 Score:  0.848744
    ├── Precision: 0.848974
    └── Recall:    0.850000

    ⏱️  ETA: 1.2 min remaining (3 experiments left)

[22/24] (91.7%) >>> Running: FashionMNIST | kernel=rbf | C=1.0 | gamma=auto
    ✅ Done! Train Time: 9144.47 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  85.000000%
    ├── F1 Score:  0.848744
    ├── Precision: 0.848974
    └── Recall:    0.850000

    ⏱️  ETA: 0.8 min remaining (2 experiments left)

[23/24] (95.8%) >>> Running: FashionMNIST | kernel=rbf | C=10.0 | gamma=scale
    ✅ Done! Train Time: 9091.31 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  86.300000%
    ├── F1 Score:  0.861900
    ├── Precision: 0.861476
    └── Recall:    0.863000

    ⏱️  ETA: 0.4 min remaining (1 experiments left)

[24/24] (100.0%) >>> Running: FashionMNIST | kernel=rbf | C=10.0 | gamma=auto
    ✅ Done! Train Time: 9032.87 ms

    📈 SVM Evaluation Metrics:
    ├── Accuracy:  86.300000%
    ├── F1 Score:  0.861900
    ├── Precision: 0.861476
    └── Recall:    0.863000

    ⏱️  ETA: 0.0 min remaining (0 experiments left)

============================================================
✅ Q1(b) SVM Experiments Completed: 24/24
⏱️  Total Time: 8.98 minutes
============================================================

,Dataset,Kernel,C,Gamma,Test Accuracy (%),F1 Score,Precision,Recall,Training Time (ms)
0,MNIST,poly,0.100000,scale,54.750000,0.578604,0.833002,0.547500,39593.338728
1,MNIST,poly,0.100000,auto,38.300000,0.415198,0.841698,0.383000,41302.342892
2,MNIST,poly,1.000000,scale,91.500000,0.918552,0.930848,0.915000,22815.172195
3,MNIST,poly,1.000000,auto,87.950000,0.887632,0.915480,0.879500,25878.817797
4,MNIST,poly,10.000000,scale,95.500000,0.955114,0.955722,0.955000,16029.763937
5,MNIST,poly,10.000000,auto,95.350000,0.953705,0.954689,0.953500,16236.431122
6,MNIST,rbf,0.100000,scale,89.350000,0.894577,0.899443,0.893500,20014.378786
7,MNIST,rbf,0.100000,auto,89.850000,0.898856,0.901761,0.898500,19743.942261
8,MNIST,rbf,1.000000,scale,94.850000,0.948441,0.948676,0.948500,11361.692667
9,MNIST,rbf,1.000000,auto,95.200000,0.951952,0.952157,0.952000,10717.605114
10,MNIST,rbf,10.000000,scale,95.600000,0.956006,0.956258,0.956000,10730.041981
11,MNIST,rbf,10.000000,auto,95.550000,0.955471,0.955628,0.955500,9775.640726
12,FashionMNIST,poly,0.100000,scale,69.050000,0.716332,0.809386,0.690500,21222.198963
13,FashionMNIST,poly,0.100000,auto,69.050000,0.716332,0.809386,0.690500,21332.985163
14,FashionMNIST,poly,1.000000,scale,82.150000,0.827252,0.838125,0.821500,11343.184471
15,FashionMNIST,poly,1.000000,auto,82.150000,0.827252,0.838125,0.821500,11507.883310
16,FashionMNIST,poly,10.000000,scale,85.150000,0.852235,0.853310,0.851500,9358.361483
17,FashionMNIST,poly,10.000000,auto,85.150000,0.852235,0.853310,0.851500,9229.094982
18,FashionMNIST,rbf,0.100000,scale,78.650000,0.783113,0.784877,0.786500,14453.416824
19,FashionMNIST,rbf,0.100000,auto,78.650000,0.783113,0.784877,0.786500,14829.966784
20,FashionMNIST,rbf,1.000000,scale,85.000000,0.848744,0.848974,0.850000,9352.647066
21,FashionMNIST,rbf,1.000000,auto,85.000000,0.848744,0.848974,0.850000,9144.469976
22,FashionMNIST,rbf,10.000000,scale,86.300000,0.861900,0.861476,0.863000,9091.307163
23,FashionMNIST,rbf,10.000000,auto,86.300000,0.861900,0.861476,0.863000,9032.866955

============================================================
Q1(b) SVM SUMMARY - TEXT ANALYSIS
============================================================

📊 BEST SVM MODELS BY DATASET:
------------------------------------------------------------
  FashionMNIST
    ├── Best Accuracy: 86.300000%
    ├── Config: kernel=rbf, C=10.0, gamma=scale
    └── Training Time: 9091.31 ms

  MNIST
    ├── Best Accuracy: 95.600000%
    ├── Config: kernel=rbf, C=10.0, gamma=scale
    └── Training Time: 10730.04 ms


📈 MEAN ACCURACY BY KERNEL:

            mean       max       std
Kernel
poly   78.004167 95.500000 17.325946
rbf    88.358333 95.600000  6.148571

📈 MEAN ACCURACY BY C VALUE:

               mean       max       std
C
0.100000  70.956250 89.850000 17.525623
1.000000  87.975000 95.200000  5.311107
10.000000 90.612500 95.600000  5.243482

⏱️  TRAINING TIME STATISTICS:

                            mean          min          max
Dataset      Kernel
FashionMNIST poly   13998.950000  9229.090000 21332.990000
             rbf    10984.110000  9032.870000 14829.970000
MNIST        poly   26975.980000 16029.760000 41302.340000
             rbf    13723.880000  9775.640000 20014.380000

✅ Saved SVM results to svm_results_q1b.csv

In [9]:
%pip install thop

Collecting thop
  Downloading thop-0.1.1.post2209072238-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from thop) (2.8.0+cu126)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->thop) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->thop) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->thop) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->thop) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch->thop) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->thop) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch->thop) (2025.10.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch->thop) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch->thop) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch->thop) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->thop) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->thop) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch->thop) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch->thop) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch->thop) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch->thop) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->thop) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch->thop) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch->thop) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch->thop) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch->thop) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch->thop) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->thop) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->thop) (3.0.3)
Downloading thop-0.1.1.post2209072238-py3-none-any.whl (15 kB)
Installing collected packages: thop
Successfully installed thop-0.1.1.post2209072238
Note: you may need to restart the kernel to use updated packages.

---
## Q2: CPU vs GPU Performance Comparison (FashionMNIST)
Compare training time, FLOPs, and classification accuracy on CPU vs GPU for FashionMNIST dataset.

In [10]:
# Install thop for FLOPs calculation if not already installed
try:
    from thop import profile, clever_format
except ImportError:
    import subprocess
    subprocess.check_call(['pip', 'install', 'thop'])
    from thop import profile, clever_format

import copy

def calculate_flops(model, input_size=(1, 1, 28, 28)):
    """Calculate FLOPs for a model (uses a copy to avoid modifying original model)"""
    # Create a deep copy on CPU for FLOPs calculation to avoid moving original model
    model_copy = copy.deepcopy(model).cpu()
    model_copy.eval()
    dummy_input = torch.randn(input_size)
    flops, params = profile(model_copy, inputs=(dummy_input,), verbose=False)
    del model_copy  # Clean up
    gc.collect()
    return flops, params

def display_q2_training_summary(train_losses, train_accs, val_losses, val_accs, config_str):
    """Display Q2 training curves as text summary"""
    print(f"\n    📊 Training Summary:")
    print("    " + "-" * 60)
    print(f"    {'Epoch':<8} {'Train Loss':<12} {'Train Acc':<12} {'Val Loss':<12} {'Val Acc':<12}")
    print("    " + "-" * 60)
    for i in range(len(train_losses)):
        print(f"    {i+1:<8} {train_losses[i]:<12.6f} {train_accs[i]:<12.6f} {val_losses[i]:<12.6f} {val_accs[i]:<12.6f}")
    print("    " + "-" * 60)

def display_q2_metrics(metrics_dict, config_str):
    """Display Q2 evaluation metrics as text summary"""
    print(f"\n    📈 Evaluation Metrics:")
    print(f"    ├── Accuracy:  {metrics_dict['accuracy']:.6f}")
    print(f"    ├── F1 Score:  {metrics_dict['f1']:.6f}")
    print(f"    ├── Precision: {metrics_dict['precision']:.6f}")
    print(f"    └── Recall:    {metrics_dict['recall']:.6f}")

def train_and_evaluate_device(model_name, device_type, train_loader, val_loader, test_loader, 
                               optimizer_name, lr, epochs, use_amp=True):
    """Train model on specified device and return metrics with memory optimization"""
    # Create device object for this specific run
    target_device = torch.device(device_type)
    
    # Get model on the target device (pass target_device explicitly)
    model = get_model(model_name, target_device=target_device)
    criterion = nn.CrossEntropyLoss()
    
    if optimizer_name == 'SGD':
        optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0.9)
    else:
        optimizer = optim.Adam(model.parameters(), lr=lr)
    
    # AMP only for CUDA
    amp_enabled = use_amp and device_type == 'cuda'
    scaler = torch.amp.GradScaler('cuda', enabled=amp_enabled)
    
    # Calculate FLOPs (uses a copy, doesn't affect original model)
    flops, params = calculate_flops(model)
    
    # Train with tracking
    train_losses, train_accs, val_losses, val_accs = [], [], [], []
    t0 = time.time()
    
    for epoch in range(epochs):
        model.train()
        running_loss = 0.0
        correct = 0
        total = 0
        
        # Progress bar for training batches - set leave=True to keep visible
        pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs} [{device_type.upper()}]", leave=True)
        
        for inputs, labels in pbar:
            inputs, labels = inputs.to(target_device, non_blocking=True), labels.to(target_device, non_blocking=True)
            optimizer.zero_grad(set_to_none=True)  # Memory optimization: set_to_none=True
            
            if amp_enabled:
                with torch.amp.autocast('cuda'):
                    outputs = model(inputs)
                    loss = criterion(outputs, labels)
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()
            else:
                outputs = model(inputs)
                loss = criterion(outputs, labels)
                loss.backward()
                optimizer.step()
            
            running_loss += loss.item() * inputs.size(0)
            _, predicted = outputs.max(1)
            total += labels.size(0)
            correct += predicted.eq(labels).sum().item()
            
            # Update progress bar with current metrics
            pbar.set_postfix({
                'loss': f'{running_loss/total:.4f}',
                'acc': f'{100*correct/total:.2f}%'
            })
        
        train_loss = running_loss / total
        train_acc = correct / total
        train_losses.append(train_loss)
        train_accs.append(train_acc)
        
        # Validation - pass target_device explicitly
        val_loss, val_acc = evaluate(model, val_loader, criterion, target_device=target_device)
        val_losses.append(val_loss)
        val_accs.append(val_acc)
        
        # Print epoch summary
        print(f"    Epoch {epoch+1}/{epochs} - Train Loss: {train_loss:.4f}, Train Acc: {100*train_acc:.2f}%, Val Acc: {100*val_acc:.2f}%")
    
    train_time_ms = (time.time() - t0) * 1000
    
    # Test evaluation with predictions for metrics
    model.eval()
    all_preds = []
    all_labels = []
    with torch.no_grad():
        for inputs, labels in tqdm(test_loader, desc="Testing", leave=False):
            inputs, labels = inputs.to(target_device, non_blocking=True), labels.to(target_device, non_blocking=True)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    
    test_acc = accuracy_score(all_labels, all_preds)
    f1 = f1_score(all_labels, all_preds, average='weighted')
    precision = precision_score(all_labels, all_preds, average='weighted')
    recall = recall_score(all_labels, all_preds, average='weighted')
    
    # Memory cleanup
    result = {
        'test_acc': test_acc * 100,
        'train_time_ms': train_time_ms,
        'flops': flops,
        'params': params,
        'train_losses': train_losses,
        'train_accs': train_accs,
        'val_losses': val_losses,
        'val_accs': val_accs,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }
    
    # Cleanup model and optimizer
    del model, optimizer, criterion, scaler
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    gc.collect()
    
    return result

# Q2 Experiments: CPU vs GPU comparison
print("=" * 70)
print("Q2: CPU vs GPU Performance Comparison on FashionMNIST")
print("=" * 70)

q2_results = []
q2_models = ['ResNet18', 'ResNet50']
q2_optimizers = ['SGD', 'Adam']
q2_batch_size = 32  # Increased batch size for better GPU utilization
q2_lr = 0.001
q2_epochs = 2  # Reduced epochs for CPU (can increase for final run)

# Check available devices
devices_to_test = ['cpu']
if torch.cuda.is_available():
    devices_to_test.append('cuda')
    # GPU optimizations
    torch.backends.cudnn.benchmark = True
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True
    print(f"GPU available: {torch.cuda.get_device_name(0)}")
    print("CUDA optimizations enabled: cudnn.benchmark=True, TF32=True")
else:
    print("WARNING: No GPU available, only CPU results will be generated")

print("=" * 70)

# Calculate total Q2 experiments
total_q2_experiments = len(devices_to_test) * len(q2_models) * len(q2_optimizers)
current_q2_experiment = 0
q2_start_time = time.time()
print(f"Total Q2 experiments to run: {total_q2_experiments}")

for device_type in devices_to_test:
    # Create dataloaders optimized for each device type
    # pin_memory=True only helps with GPU, use False for CPU to avoid overhead
    use_pin_memory = (device_type == 'cuda')
    train_loader, val_loader, test_loader = get_dataloaders('FashionMNIST', q2_batch_size, pin_memory=use_pin_memory)
    print(f"\n--- Device: {device_type.upper()} (pin_memory={use_pin_memory}) ---")
    
    for model_name in q2_models:
        for opt_name in q2_optimizers:
            current_q2_experiment += 1
            q2_progress_pct = (current_q2_experiment / total_q2_experiments) * 100
            config_str = f"{device_type.upper()} | {model_name} | {opt_name} | LR={q2_lr}"
            print(f"\n[{current_q2_experiment}/{total_q2_experiments}] ({q2_progress_pct:.1f}%) >>> Running: {config_str}")
            
            try:
                result = train_and_evaluate_device(
                    model_name, device_type, train_loader, val_loader, test_loader,
                    opt_name, q2_lr, q2_epochs, use_amp=True
                )
                
                flops_formatted, params_formatted = clever_format([result['flops'], result['params']], "%.2f")
                
                print(f"\n    ✅ Done! Test Acc: {result['test_acc']:.6f}% | Train Time: {result['train_time_ms']:.2f} ms | FLOPs: {flops_formatted}")
                
                # --- DISPLAY TRAINING CURVES AS TEXT ---
                display_q2_training_summary(
                    result['train_losses'], result['train_accs'], 
                    result['val_losses'], result['val_accs'],
                    config_str
                )
                
                # --- DISPLAY EVALUATION METRICS AS TEXT ---
                metrics_dict = {
                    'accuracy': result['test_acc'] / 100,
                    'f1': result['f1'],
                    'precision': result['precision'],
                    'recall': result['recall']
                }
                display_q2_metrics(metrics_dict, config_str)
                
                # ETA for Q2
                q2_elapsed = time.time() - q2_start_time
                q2_avg_time = q2_elapsed / current_q2_experiment
                q2_remaining = total_q2_experiments - current_q2_experiment
                q2_eta_min = (q2_avg_time * q2_remaining) / 60
                print(f"\n    ⏱️  ETA: {q2_eta_min:.1f} min remaining ({q2_remaining} experiments left)")
                
                q2_results.append({
                    'Compute': device_type.upper(),
                    'Batch Size': q2_batch_size,
                    'Optimizer': opt_name,
                    'Learning Rate': q2_lr,
                    'Model': model_name,
                    'Test Accuracy (%)': round(result['test_acc'], 6),
                    'Training Time (ms)': round(result['train_time_ms'], 6),
                    'FLOPs': flops_formatted,
                    'Parameters': params_formatted,
                    'F1 Score': round(result['f1'], 6),
                    'Precision': round(result['precision'], 6),
                    'Recall': round(result['recall'], 6)
                })
                
                # Crash-safe: Save after each experiment
                pd.DataFrame(q2_results).to_csv('cpu_gpu_comparison_q2.csv', index=False)
                
                # Memory cleanup after each experiment
                del result
                gc.collect()
                
            except Exception as e:
                print(f"❌ Error: {e}")
                import traceback
                traceback.print_exc()
                # Cleanup on error
                if torch.cuda.is_available():
                    torch.cuda.empty_cache()
                gc.collect()
    
    # Cleanup data loaders after all experiments for this device
    del train_loader, val_loader, test_loader
    gc.collect()

# Q2 Results DataFrame
df_q2 = pd.DataFrame(q2_results)
q2_total_time = time.time() - q2_start_time
print(f"\n{'=' * 70}")
print(f"✅ Q2 Experiments Completed: {current_q2_experiment}/{total_q2_experiments}")
print(f"⏱️  Total Time: {q2_total_time/60:.2f} minutes")
print("=" * 70)
display(df_q2)
df_q2.to_csv('cpu_gpu_comparison_q2.csv', index=False)

# --- Q2 Summary (Text-based) ---
print("\n" + "=" * 70)
print("Q2 SUMMARY - CPU vs GPU COMPARISON")
print("=" * 70)

# Training time comparison
print("\n⏱️  TRAINING TIME COMPARISON:")
print("-" * 70)
time_pivot = df_q2.pivot_table(index='Model', columns='Compute', values='Training Time (ms)', aggfunc='mean')
display(time_pivot.round(2))

if 'CPU' in time_pivot.columns and 'CUDA' in time_pivot.columns:
    print("\n📈 GPU SPEEDUP FACTOR:")
    speedup = time_pivot['CPU'] / time_pivot['CUDA']
    for model in speedup.index:
        print(f"    {model}: {speedup[model]:.2f}x faster on GPU")

# Accuracy comparison
print("\n🎯 ACCURACY COMPARISON:")
print("-" * 70)
acc_pivot = df_q2.pivot_table(index='Model', columns='Compute', values='Test Accuracy (%)', aggfunc='mean')
display(acc_pivot.round(6))

# Best configurations
print("\n🏆 BEST CONFIGURATIONS:")
print("-" * 70)
best_q2 = df_q2.loc[df_q2.groupby('Compute')['Test Accuracy (%)'].idxmax()]
for _, row in best_q2.iterrows():
    print(f"  {row['Compute']}")
    print(f"    ├── Best Accuracy: {row['Test Accuracy (%)']:.6f}%")
    print(f"    ├── Model: {row['Model']}, Optimizer: {row['Optimizer']}")
    print(f"    ├── Training Time: {row['Training Time (ms)']:.2f} ms")
    print(f"    └── FLOPs: {row['FLOPs']}")
    print()

# Full metrics summary
print("\n📋 FULL METRICS SUMMARY:")
print("-" * 70)
metrics_summary = df_q2.groupby(['Compute', 'Model']).agg({
    'Test Accuracy (%)': 'mean',
    'Training Time (ms)': 'mean',
    'F1 Score': 'mean',
    'Precision': 'mean',
    'Recall': 'mean'
}).round(6)
display(metrics_summary)

print("\n✅ Saved Q2 results to cpu_gpu_comparison_q2.csv")

======================================================================
Q2: CPU vs GPU Performance Comparison on FashionMNIST
======================================================================
GPU available: Tesla T4
CUDA optimizations enabled: cudnn.benchmark=True, TF32=True
======================================================================
Total Q2 experiments to run: 8

--- Device: CPU (pin_memory=False) ---

[1/8] (12.5%) >>> Running: CPU | ResNet18 | SGD | LR=0.001

Epoch 1/2 [CPU]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.4965, Train Acc: 82.12%, Val Acc: 86.77%

Epoch 2/2 [CPU]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.3254, Train Acc: 88.03%, Val Acc: 88.96%

Testing:   0%|          | 0/438 [00:00<?, ?it/s]

    ✅ Done! Test Acc: 88.535714% | Train Time: 341621.31 ms | FLOPs: 33.18M

    📊 Training Summary:
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.496539     0.821204     0.355573     0.867714
    2        0.325383     0.880286     0.292334     0.889571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.885357
    ├── F1 Score:  0.884884
    ├── Precision: 0.885081
    └── Recall:    0.885357

    ⏱️  ETA: 41.6 min remaining (7 experiments left)

[2/8] (25.0%) >>> Running: CPU | ResNet18 | Adam | LR=0.001

Epoch 1/2 [CPU]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.4799, Train Acc: 83.01%, Val Acc: 86.59%

Epoch 2/2 [CPU]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.3388, Train Acc: 87.77%, Val Acc: 88.76%

Testing:   0%|          | 0/438 [00:00<?, ?it/s]

    ✅ Done! Test Acc: 88.228571% | Train Time: 470803.36 ms | FLOPs: 33.18M

    📊 Training Summary:
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.479902     0.830082     0.365593     0.865857
    2        0.338845     0.877694     0.299171     0.887571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.882286
    ├── F1 Score:  0.883286
    ├── Precision: 0.885930
    └── Recall:    0.882286

    ⏱️  ETA: 42.1 min remaining (6 experiments left)

[3/8] (37.5%) >>> Running: CPU | ResNet50 | SGD | LR=0.001

Epoch 1/2 [CPU]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.8322, Train Acc: 71.55%, Val Acc: 82.17%

Epoch 2/2 [CPU]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.5058, Train Acc: 81.89%, Val Acc: 84.23%

Testing:   0%|          | 0/438 [00:00<?, ?it/s]

    ✅ Done! Test Acc: 84.835714% | Train Time: 1064107.57 ms | FLOPs: 78.76M

    📊 Training Summary:
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.832164     0.715510     0.489492     0.821714
    2        0.505818     0.818918     0.424033     0.842286
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.848357
    ├── F1 Score:  0.846369
    ├── Precision: 0.849258
    └── Recall:    0.848357

    ⏱️  ETA: 54.0 min remaining (5 experiments left)

[4/8] (50.0%) >>> Running: CPU | ResNet50 | Adam | LR=0.001

Epoch 1/2 [CPU]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.7056, Train Acc: 77.40%, Val Acc: 85.24%

Epoch 2/2 [CPU]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.4692, Train Acc: 83.85%, Val Acc: 87.46%

Testing:   0%|          | 0/438 [00:00<?, ?it/s]

    ✅ Done! Test Acc: 87.114286% | Train Time: 1281027.97 ms | FLOPs: 78.76M

    📊 Training Summary:
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.705564     0.774041     0.409676     0.852429
    2        0.469180     0.838469     0.343849     0.874571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.871143
    ├── F1 Score:  0.872734
    ├── Precision: 0.879313
    └── Recall:    0.871143

    ⏱️  ETA: 54.3 min remaining (4 experiments left)

--- Device: CUDA (pin_memory=True) ---

[5/8] (62.5%) >>> Running: CUDA | ResNet18 | SGD | LR=0.001

Epoch 1/2 [CUDA]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.4882, Train Acc: 82.43%, Val Acc: 87.11%

Epoch 2/2 [CUDA]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.3272, Train Acc: 87.81%, Val Acc: 88.14%

Testing:   0%|          | 0/438 [00:00<?, ?it/s]

    ✅ Done! Test Acc: 87.971429% | Train Time: 62967.30 ms | FLOPs: 33.18M

    📊 Training Summary:
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.488158     0.824286     0.355939     0.871143
    2        0.327203     0.878143     0.317899     0.881429
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.879714
    ├── F1 Score:  0.881725
    ├── Precision: 0.888232
    └── Recall:    0.879714

    ⏱️  ETA: 33.3 min remaining (3 experiments left)

[6/8] (75.0%) >>> Running: CUDA | ResNet18 | Adam | LR=0.001

Epoch 1/2 [CUDA]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.4716, Train Acc: 83.15%, Val Acc: 87.36%

Epoch 2/2 [CUDA]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.3422, Train Acc: 87.55%, Val Acc: 87.19%

Testing:   0%|          | 0/438 [00:00<?, ?it/s]

    ✅ Done! Test Acc: 86.142857% | Train Time: 69793.64 ms | FLOPs: 33.18M

    📊 Training Summary:
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.471570     0.831531     0.349189     0.873571
    2        0.342165     0.875469     0.349330     0.871857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.861429
    ├── F1 Score:  0.854543
    ├── Precision: 0.872785
    └── Recall:    0.861429

    ⏱️  ETA: 18.9 min remaining (2 experiments left)

[7/8] (87.5%) >>> Running: CUDA | ResNet50 | SGD | LR=0.001

Epoch 1/2 [CUDA]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.8284, Train Acc: 71.25%, Val Acc: 81.20%

Epoch 2/2 [CUDA]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.5088, Train Acc: 81.78%, Val Acc: 84.59%

Testing:   0%|          | 0/438 [00:00<?, ?it/s]

    ✅ Done! Test Acc: 84.178571% | Train Time: 111651.03 ms | FLOPs: 78.76M

    📊 Training Summary:
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.828425     0.712510     0.518154     0.812000
    2        0.508839     0.817816     0.421209     0.845857
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.841786
    ├── F1 Score:  0.834821
    ├── Precision: 0.845138
    └── Recall:    0.841786

    ⏱️  ETA: 8.4 min remaining (1 experiments left)

[8/8] (100.0%) >>> Running: CUDA | ResNet50 | Adam | LR=0.001

Epoch 1/2 [CUDA]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 1/2 - Train Loss: 0.6824, Train Acc: 77.82%, Val Acc: 82.60%

Epoch 2/2 [CUDA]:   0%|          | 0/1532 [00:00<?, ?it/s]

    Epoch 2/2 - Train Loss: 0.4672, Train Acc: 84.68%, Val Acc: 86.56%

Testing:   0%|          | 0/438 [00:00<?, ?it/s]

    ✅ Done! Test Acc: 86.964286% | Train Time: 125692.88 ms | FLOPs: 78.76M

    📊 Training Summary:
    ------------------------------------------------------------
    Epoch    Train Loss   Train Acc    Val Loss     Val Acc
    ------------------------------------------------------------
    1        0.682361     0.778245     0.448457     0.826000
    2        0.467167     0.846837     0.369443     0.865571
    ------------------------------------------------------------

    📈 Evaluation Metrics:
    ├── Accuracy:  0.869643
    ├── F1 Score:  0.869952
    ├── Precision: 0.871337
    └── Recall:    0.869643

    ⏱️  ETA: 0.0 min remaining (0 experiments left)

======================================================================
✅ Q2 Experiments Completed: 8/8
⏱️  Total Time: 60.94 minutes
======================================================================

,Compute,Batch Size,Optimizer,Learning Rate,Model,Test Accuracy (%),Training Time (ms),FLOPs,Parameters,F1 Score,Precision,Recall
0,CPU,32,SGD,0.001000,ResNet18,88.535714,341621.314049,33.18M,11.18M,0.884884,0.885081,0.885357
1,CPU,32,Adam,0.001000,ResNet18,88.228571,470803.363562,33.18M,11.18M,0.883286,0.885930,0.882286
2,CPU,32,SGD,0.001000,ResNet50,84.835714,1064107.572794,78.76M,23.52M,0.846369,0.849258,0.848357
3,CPU,32,Adam,0.001000,ResNet50,87.114286,1281027.967453,78.76M,23.52M,0.872734,0.879313,0.871143
4,CUDA,32,SGD,0.001000,ResNet18,87.971429,62967.304468,33.18M,11.18M,0.881725,0.888232,0.879714
5,CUDA,32,Adam,0.001000,ResNet18,86.142857,69793.638468,33.18M,11.18M,0.854543,0.872785,0.861429
6,CUDA,32,SGD,0.001000,ResNet50,84.178571,111651.034355,78.76M,23.52M,0.834821,0.845138,0.841786
7,CUDA,32,Adam,0.001000,ResNet50,86.964286,125692.883253,78.76M,23.52M,0.869952,0.871337,0.869643

======================================================================
Q2 SUMMARY - CPU vs GPU COMPARISON
======================================================================

⏱️  TRAINING TIME COMPARISON:
----------------------------------------------------------------------

Compute             CPU          CUDA
Model
ResNet18  406212.340000  66380.470000
ResNet50 1172567.770000 118671.960000

📈 GPU SPEEDUP FACTOR:
    ResNet18: 6.12x faster on GPU
    ResNet50: 9.88x faster on GPU

🎯 ACCURACY COMPARISON:
----------------------------------------------------------------------

Compute        CPU      CUDA
Model
ResNet18 88.382142 87.057143
ResNet50 85.975000 85.571428

🏆 BEST CONFIGURATIONS:
----------------------------------------------------------------------
  CPU
    ├── Best Accuracy: 88.535714%
    ├── Model: ResNet18, Optimizer: SGD
    ├── Training Time: 341621.31 ms
    └── FLOPs: 33.18M

  CUDA
    ├── Best Accuracy: 87.971429%
    ├── Model: ResNet18, Optimizer: SGD
    ├── Training Time: 62967.30 ms
    └── FLOPs: 33.18M


📋 FULL METRICS SUMMARY:
----------------------------------------------------------------------

                  Test Accuracy (%)  Training Time (ms)  F1 Score  Precision  \
Compute Model
CPU     ResNet18          88.382142       406212.338805  0.884085   0.885506
        ResNet50          85.975000      1172567.770124  0.859552   0.864286
CUDA    ResNet18          87.057143        66380.471468  0.868134   0.880508
        ResNet50          85.571428       118671.958804  0.852386   0.858238

                   Recall
Compute Model
CPU     ResNet18 0.883822
        ResNet50 0.859750
CUDA    ResNet18 0.870572
        ResNet50 0.855714

✅ Saved Q2 results to cpu_gpu_comparison_q2.csv

---
## Final Results Summary
Tables formatted as per assignment requirements.

In [11]:
# --- Q1(a) Table: Test Classification Accuracy (in %) ---
print("=" * 80)
print("Q1(a) RESULTS TABLE: Test Classification Accuracy (in %)")
print("=" * 80)

# Filter results for the required table format
df_q1a = pd.DataFrame(results)

# Create pivot table for each dataset
for dataset in ['MNIST', 'FashionMNIST']:
    print(f"\n### {dataset} Dataset ###")
    df_dataset = df_q1a[df_q1a['Dataset'] == dataset]
    
    # Aggregate by taking max accuracy across pin_memory and epochs variations
    pivot = df_dataset.pivot_table(
        index=['Batch Size', 'Optimizer', 'Learning Rate'],
        columns='Model',
        values='Test Accuracy',
        aggfunc='max'
    ).reset_index()
    
    # Reorder columns
    pivot = pivot[['Batch Size', 'Optimizer', 'Learning Rate', 'ResNet18', 'ResNet50']]
    display(pivot)
    pivot.to_csv(f'q1a_{dataset}_results.csv', index=False)

# --- Q1(b) Table: SVM Results ---
print("\n" + "=" * 80)
print("Q1(b) RESULTS TABLE: SVM Classification")
print("=" * 80)

for dataset in ['MNIST', 'FashionMNIST']:
    print(f"\n### {dataset} Dataset ###")
    df_svm_dataset = df_svm[df_svm['Dataset'] == dataset]
    pivot_svm = df_svm_dataset.pivot_table(
        index=['Kernel', 'C', 'Gamma'],
        values=['Test Accuracy (%)', 'Training Time (ms)'],
        aggfunc='first'
    ).reset_index()
    display(pivot_svm)

# --- Q2 Table: CPU vs GPU Comparison ---
print("\n" + "=" * 80)
print("Q2 RESULTS TABLE: CPU vs GPU Comparison (FashionMNIST)")
print("=" * 80)

pivot_q2 = df_q2.pivot_table(
    index=['Compute', 'Batch Size', 'Optimizer', 'Learning Rate'],
    columns='Model',
    values=['Test Accuracy (%)', 'Training Time (ms)', 'FLOPs'],
    aggfunc='first'
).reset_index()

display(pivot_q2)
pivot_q2.to_csv('q2_cpu_gpu_results.csv', index=False)

# --- Save Best Model ---
print("\n" + "=" * 80)
print("BEST MODEL SELECTION")
print("=" * 80)

# Find best model from Q1(a)
best_idx = df_q1a['Test Accuracy'].idxmax()
best_model_info = df_q1a.loc[best_idx]
print(f"\nBest Model Configuration:")
print(f"  Dataset: {best_model_info['Dataset']}")
print(f"  Model: {best_model_info['Model']}")
print(f"  Batch Size: {best_model_info['Batch Size']}")
print(f"  Optimizer: {best_model_info['Optimizer']}")
print(f"  Learning Rate: {best_model_info['Learning Rate']}")
print(f"  Epochs: {best_model_info['Epochs']}")
print(f"  Test Accuracy: {best_model_info['Test Accuracy']}%")
print(f"  Model Path: {best_model_info['Model Path']}")

================================================================================
Q1(a) RESULTS TABLE: Test Classification Accuracy (in %)
================================================================================

### MNIST Dataset ###

Model  Batch Size Optimizer  Learning Rate  ResNet18  ResNet50
0              16      Adam       0.000100 98.757143 97.742857
1              16      Adam       0.001000 99.014286 98.314286
2              16       SGD       0.000100 98.478571 97.907143
3              16       SGD       0.001000 98.950000 98.550000
4              32      Adam       0.000100 98.657143 97.021429
5              32      Adam       0.001000 98.778571 98.535714
6              32       SGD       0.000100 97.914286 96.871429
7              32       SGD       0.001000 98.821429 98.700000

### FashionMNIST Dataset ###

Model  Batch Size Optimizer  Learning Rate  ResNet18  ResNet50
0              16      Adam       0.000100 89.350000 87.914286
1              16      Adam       0.001000 90.571429 87.421429
2              16       SGD       0.000100 88.657143 85.600000
3              16       SGD       0.001000 90.064286 89.021429
4              32      Adam       0.000100 89.685714 86.907143
5              32      Adam       0.001000 90.764286 89.400000
6              32       SGD       0.000100 87.864286 83.600000
7              32       SGD       0.001000 89.928571 89.292857

================================================================================
Q1(b) RESULTS TABLE: SVM Classification
================================================================================

### MNIST Dataset ###

   Kernel         C  Gamma  Test Accuracy (%)  Training Time (ms)
0    poly  0.100000   auto          38.300000        41302.342892
1    poly  0.100000  scale          54.750000        39593.338728
2    poly  1.000000   auto          87.950000        25878.817797
3    poly  1.000000  scale          91.500000        22815.172195
4    poly 10.000000   auto          95.350000        16236.431122
5    poly 10.000000  scale          95.500000        16029.763937
6     rbf  0.100000   auto          89.850000        19743.942261
7     rbf  0.100000  scale          89.350000        20014.378786
8     rbf  1.000000   auto          95.200000        10717.605114
9     rbf  1.000000  scale          94.850000        11361.692667
10    rbf 10.000000   auto          95.550000         9775.640726
11    rbf 10.000000  scale          95.600000        10730.041981

### FashionMNIST Dataset ###

   Kernel         C  Gamma  Test Accuracy (%)  Training Time (ms)
0    poly  0.100000   auto          69.050000        21332.985163
1    poly  0.100000  scale          69.050000        21222.198963
2    poly  1.000000   auto          82.150000        11507.883310
3    poly  1.000000  scale          82.150000        11343.184471
4    poly 10.000000   auto          85.150000         9229.094982
5    poly 10.000000  scale          85.150000         9358.361483
6     rbf  0.100000   auto          78.650000        14829.966784
7     rbf  0.100000  scale          78.650000        14453.416824
8     rbf  1.000000   auto          85.000000         9144.469976
9     rbf  1.000000  scale          85.000000         9352.647066
10    rbf 10.000000   auto          86.300000         9032.866955
11    rbf 10.000000  scale          86.300000         9091.307163

================================================================================
Q2 RESULTS TABLE: CPU vs GPU Comparison (FashionMNIST)
================================================================================

      Compute Batch Size Optimizer Learning Rate    FLOPs           \
Model                                            ResNet18 ResNet50
0         CPU         32      Adam      0.001000   33.18M   78.76M
1         CPU         32       SGD      0.001000   33.18M   78.76M
2        CUDA         32      Adam      0.001000   33.18M   78.76M
3        CUDA         32       SGD      0.001000   33.18M   78.76M

      Test Accuracy (%)           Training Time (ms)
Model          ResNet18  ResNet50           ResNet18       ResNet50
0             88.228571 87.114286      470803.363562 1281027.967453
1             88.535714 84.835714      341621.314049 1064107.572794
2             86.142857 86.964286       69793.638468  125692.883253
3             87.971429 84.178571       62967.304468  111651.034355

================================================================================
BEST MODEL SELECTION
================================================================================

Best Model Configuration:
  Dataset: MNIST
  Model: ResNet18
  Batch Size: 16
  Optimizer: Adam
  Learning Rate: 0.001
  Epochs: 5
  Test Accuracy: 99.014286%
  Model Path: models/MNIST_ResNet18_bs16_Adam_lr0.001_pinFalse_ep5.pth

### Detailed Analysis for Q2: CPU vs GPU Comparison

**Training Time Analysis:**
- GPU training is significantly faster (typically 10-50x) compared to CPU
- The speedup is more pronounced for larger models (ResNet-50 vs ResNet-18)
- AMP (Automatic Mixed Precision) provides additional speedup on GPU with minimal accuracy loss

**FLOPs Analysis:**
- ResNet-50 has approximately 4x more FLOPs than ResNet-18
- FLOPs count remains constant regardless of CPU/GPU (it's a model property)
- Higher FLOPs correlate with longer training times

**Classification Accuracy:**
- Accuracy should be similar between CPU and GPU (same model, same data)
- Minor differences may occur due to floating-point precision differences
- GPU with AMP may show slight variations due to mixed precision

**Recommendations:**
- Always use GPU when available for deep learning training
- Use AMP for additional speedup without significant accuracy loss
- For inference on edge devices, consider model quantization or pruning